### ISSUE TITLE
Mechanism for customizing/overriding default views

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#10]
Related to #6 
By removing institution-specific layouts/logos/etc. we need a mechanism to override the default views and put the custom views in place (maybe it's useful to replace only some of them).

@nics Do you think we could use Template Toolkit's `INCLUDE_PATH` option (which can handle an array of paths)?

```
INCLUDE_PATH => '/my/path1:/my/path2'
```

And do we know if this usage is safe? (i.e. always searches /my/path1 first?)

Any other ideas?

**Comment by nics** [comment]
The feature_layers branch has a bare bones layering mechanism for templates and static files.

**Comment by vpeil** [comment]
Maybe the branch `feature_layes` is right place for a small feature (and we talked about that earlier): Moving the dancer configuration `config.yml` to a `catmandu.dancer.yml`. This would allow users to override all dancer settings via `catmandu.local.yml`.

**Comment by nics** [comment]
ok, will do

**Comment by nics** [comment]
merged into dev now
