### ISSUE TITLE
Search account is broken

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#100]
http://localhost:5001/librecat/admin/account/search?q=

Dies with a 

    {
       "error": "cql error: missing term at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 27.\n",
       "exception": "cql error: missing term at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 27.\n"
    }

**Comment by vpeil** [comment]
only the empty search is broken?

**Comment by phochste** [comment]
Also searching for a name containing spaces is broken
