### ISSUE TITLE
Fix get_department_tree 

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#103]
Display the hierachical tree in :

http://localhost:5001/department

Display a list of all  deparments in the facet list

**Comment by vpeil** [comment]
It is not necessary to fix the sub `get_department_tree`. Commit e76a80911ca3d7727c53c16c07fb4af07bcda485 shows a better way of doing this. So we only need to refactor the department facet (if this is of any use, displaying hundreds of items within a facet ....)

**Comment by vpeil** [comment]
department filter opens a modal and display basically the same like on public page.
