### ISSUE TITLE
Uppercase queries that contains words with boolean names endings fail

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#106]
brand test => ok

BRAND TEST => 

    {
      "exception" : "cql error: unknown first class relation: test at    /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 27.\n",
       "error" : "cql error: unknown first class relation: test at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 27.\n"
    }

BROR TEST

    {
      "exception" : "cql error: unknown first class relation: test at    /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 27.\n",
       "error" : "cql error: unknown first class relation: test at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 27.\n"
    }

BRNOT TEST 

    {
       "exception" : "Catmandu::Error",
       "error" : "cql error: unknown index brbasic\n\nTrace begun at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 109\nCatmandu::Store::ElasticSearch::CQL::_parse_term_node('Catmandu::Store::ElasticSearch::CQL=HASH(0x947f2e8)', 'CQL::TermNode=HASH(0x93f7378)', 'HASH(0x85a9088)') called at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 54\nCatmandu::Store::ElasticSearch::CQL::parse_node('Catmandu::Store::ElasticSearch::CQL=HASH(0x947f2e8)', 'CQL::AndNode=HASH(0x83ed2b8)') called at /opt/librecat/lib/Catmandu/Store/ElasticSearch/CQL.pm line 32\nCatmandu::Store::ElasticSearch::CQL::parse('Catmandu::Store::ElasticSearch::CQL=HASH(0x947f2e8)', 'brbasic<>test AND status<>deleted') called at /opt/librecat/local/lib/perl5/Catmandu/Store/ElasticSearch/Bag.pm line 236\nCatmandu::Store::ElasticSearch::Bag::translate_cql_query('Catmandu::Store::ElasticSearch::Bag=HASH(0x6938d80)', 'brbasic<>test AND status<>deleted') called at /opt/librecat/local/lib/perl5/Catmandu/Searchable.pm line 41\nCatmandu::Searchable::__ANON__('CODE(0x691bef8)', 'Catmandu::Store::ElasticSearch::Bag=HASH(0x6938d80)', 'cql_query', 'brbasic<>test AND status<>deleted', 'limit', 20, 'facets', 'HASH(0x49e1748)', 'start', 0, 'sru_sortkeys', 'date_updated,,0 year,,0') called at (eval 536) line 1\nCatmandu::Store::ElasticSearch::Bag::__ANON__('Catmandu::Store::ElasticSearch::Bag=HASH(0x6938d80)', 'cql_query', 'brbasic<>test AND status<>deleted', 'limit', 20, 'facets', 'HASH(0x49e1748)', 'start', 0, 'sru_sortkeys', 'date_updated,,0 year,,0') called at (eval 538) line 2\nCatmandu::Store::ElasticSearch::Bag::search('Catmandu::Store::ElasticSearch::Bag=HASH(0x6938d80)', 'cql_query', 'brbasic<>test AND status<>deleted', 'limit', 20, 'facets', 'HASH(0x49e1748)', 'start', 0, 'sru_sortkeys', 'date_updated,,0 year,,0') called at /opt/librecat/lib/LibreCat/Search.pm line 53\nLibreCat::Search::search('LibreCat::Search=HASH(0x4985900)', 'publication', 'HASH(0x9361140)') called at /opt/librecat/lib/LibreCat/App/Catalogue/Route/search.pm line 54\nLibreCat::App::Catalogue::Route::search::__ANON__ at /opt/librecat/local/lib/perl5/Dancer/Route.pm line 263\nDancer::Route::execute('Dancer::Route=HASH(0x75a00b8)') called at /opt/librecat/local/lib/perl5/Dancer/Route.pm line 186\nDancer::Route::try {...}  at /opt/librecat/local/lib/perl5/Try/Tiny.pm line 101\neval {...} at /opt/librecat/local/lib/perl5/Try/Tiny.pm line 94\nTry::Tiny::try('CODE(0x8791cc8)', 'Try::Tiny::Catch=REF(0x8790df8)') called at /opt/librecat/local/lib/perl5/Dancer/Route.pm line 200\nDancer::Route::run('Dancer::Route=HASH(0x75a00b8)', 'Dancer::Request=HASH(0x83a9cd0)') called at /opt/librecat/local/lib/perl5/Dancer/Renderer.pm line 137\nDancer::Renderer::try {...}  at /opt/librecat/local/lib/perl5/Try/Tiny.pm line 103\neval {...} at /opt/librecat/local/lib/perl5/Try/Tiny.pm line 94\nTry::Tiny::try('CODE(0x8715ae0)', 'Try::Tiny::Catch=REF(0x8694630)') called at /opt/librecat/local/lib/perl5/Dancer/Renderer.pm line 146\nDancer::Renderer::get_action_response('Dancer::Renderer') called at /opt/librecat/local/lib/perl5/Dancer/Renderer.pm line 33\nDancer::Renderer::render_action('Dancer::Renderer') called at /opt/librecat/local/lib/perl5/Dancer/Handler.pm line 84\nDancer::Handler::try {...}  at /opt/librecat/local/lib/perl5/Try/Tiny.pm line 101\neval {...} at /opt/librecat/local/lib/perl5/Try/Tiny.pm line 94\nTry::Tiny::try('CODE(0x48f3550)', 'Try::Tiny::Catch=REF(0x8678978)') called at /opt/librecat/local/lib/perl5/Dancer/Handler.pm line 113\nDancer::Handler::render_request('Dancer::Request=HASH(0x83a9cd0)') called at /opt/librecat/local/lib/perl5/Dancer/Handler.pm line 76\nDancer::Handler::handle_request('Dancer::Handler', 'Dancer::Request=HASH(0x83a9cd0)') called at /opt/librecat/local/lib/perl5/Dancer.pm line 491\nDancer::_start('Dancer', 'Dancer::Request=HASH(0x83a9cd0)') called at /opt/librecat/bin/app.pl line 64\nPlack::Sandbox::_2fopt_2flibrecat_2fbin_2fapp_2epl::__ANON__('HASH(0x8724ac8)') called at /opt/librecat/local/lib/perl5/Plack/App/Cascade.pm line 48\nPlack::App::Cascade::__ANON__('CODE(0x7e95988)') called at /opt/librecat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x947f270)') called at /opt/librecat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x9346008)') called at /opt/librecat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x7e966c0)') called at /opt/librecat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x8696588)') called at /opt/librecat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x8419ff8)') called at /opt/librecat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x87288c0)') called at /opt/librecat/local/lib/perl5/HTTP/Server/PSGI.pm line 181\nHTTP::Server::PSGI::handle_connection('HTTP::Server::PSGI=HASH(0x780ffe0)', 'HASH(0x8724ac8)', 'IO::Socket::INET=GLOB(0x83ec8e0)', 'CODE(0x7878cf0)') called at /opt/librecat/local/lib/perl5/HTTP/Server/PSGI.pm line 129\nHTTP::Server::PSGI::accept_loop('HTTP::Server::PSGI=HASH(0x780ffe0)', 'CODE(0x4b99f10)') called at /opt/librecat/local/lib/perl5/HTTP/Server/PSGI.pm line 55\nHTTP::Server::PSGI::run('HTTP::Server::PSGI=HASH(0x780ffe0)', 'CODE(0x4b99f10)') called at /opt/librecat/local/lib/perl5/Plack/Handler/HTTP/Server/PSGI.pm line 14\nPlack::Handler::HTTP::Server::PSGI::run('Plack::Handler::Standalone=HASH(0x2c27148)', 'CODE(0x4b99f10)') called at /opt/librecat/local/lib/perl5/Plack/Loader/Restarter.pm line 32\nPlack::Loader::Restarter::_fork_and_start('Plack::Loader::Restarter=HASH(0x2a29fc8)', 'Plack::Handler::Standalone=HASH(0x2c27148)') called at /opt/librecat/local/lib/perl5/Plack/Loader/Restarter.pm line 89\nPlack::Loader::Restarter::run('Plack::Loader::Restarter=HASH(0x2a29fc8)', 'Plack::Handler::Standalone=HASH(0x2c27148)') called at /opt/librecat/local/lib/perl5/Plack/Runner.pm line 277\nPlack::Runner::run('Plack::Runner=HASH(0x2736638)') called at /opt/librecat/local/bin/plackup line 7\n"
    }

BRPROX TEST => ok ...

**Comment by phochste** [comment]
Also queries containing parentheses fail:

    "Digging into the (c)Ubaid period bitumen from DosariyahDigging into the (c)Ubaid period bitumen from Dosariyah"

Why aren't these send to ElasticSearch as phrases there is a whole machinery for that

**Comment by vpeil** [comment]
This is fixed in the branch `bug/search_params`. Please check!
