### ISSUE TITLE
Export records links are broken

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#107]
What ever you want to export. It always exports the first 20 hits of an 'any publication' search.

**Comment by vpeil** [comment]
question: should the limit parameter have any effect on the exports? 
That is:
1) Export what you see (with limit parameter)
or
2) Export everything for the current query.

**Comment by phochste** [comment]
At least you should be able to export what you are seeing. And probably a max limit on export size ? E.g. not exporting 100.000 marked citations into RTF

**Comment by vpeil** [comment]
ha! and it's about route matching: this one

```
qr{/(data|publication)/(\S+)}
```
matches earlier than this
```
get '/publication/:id.:fmt'
```

**Comment by phochste** [comment]
@vpeil  No, that one is working. It is the templates that don't have anything on the paths to /export. Whatever 'Export as' you do ....it returns all publicaitons
