### ISSUE TITLE
Include EPrints OAI Stylesheet

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#114]
The [EPrints OAI Stylesheet](http://wiki.eprints.org/w/OAI_XSLT) is a nice way to make a OAI endpoint user friendly. It is basically a client which runs inside a browser.

**Comment by vpeil** [comment]
Has be to implemented in `Dancer::Plugin::Catmandu::OAI`

https://github.com/LibreCat/Dancer-Plugin-Catmandu-OAI/issues/11

**Comment by vpeil** [comment]
thanks @nics for implementing LibreCat/Dancer-Plugin-Catmandu-OAI#11 so quickly.
