### ISSUE TITLE
Embeds don't work

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#115]
All embed point to the same URL whatever page you are currently on. E.g.

Embed publication list:

```(html)
<div class="publ"><script type="text/javascript" charset="UTF-8" src="http://localhost:5001/publication?&ftyp=js"></script><noscript><a href="http://localhost:5001/publication?" target="_blank">My Publication List</a></noscript></div>
```

Embed publication list for an author (exactly the same URL as showing all publications):

```(html)
<div class="publ"><script type="text/javascript" charset="UTF-8" src="http://localhost:5001/publication?&ftyp=js"></script><noscript><a href="http://localhost:5001/publication?" target="_blank">My Publication List</a></noscript></div>
```

The ftype=js doesn't have any effect. When you include the above fragments into an HTML page you don't see anything . `http://localhost:5001/publication?&ftyp=js` returns a HTML page not a JavaScript fragment.

**Comment by dbeucke** [comment]
Nearly the same bug appears again. 

Embed publication list:

```(html)
<div class="publ"><script type="text/javascript" charset="UTF-8" src="http://demo.librecat.org/embed?cql=type%3C%3Eresearch_data&fmt=js"></script><noscript><a href="http://demo.librecat.org/embed?cql=type%3C%3Eresearch_data" target="_blank">My Publication List</a></noscript></div>
```

The link works, but it seems that all publications will be shown. Also if there are chosen a sub list.

**Comment by vpeil** [comment]
It seems that the links generated in the facets are not correct. the embedding itself works (if you use the correct URL...)
