### ISSUE TITLE
What is the use of 'first_author' and 'add_autorenansetzung' in the codebase

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#12]
I see the 'first_author' is a field defined in the EL configuration and is used in the templates, but it is never set? There is a 'add_autorenansetzung' fix but it is not used?

**Comment by vpeil** [comment]
You're right. I removed this part from the code in 9bd359e9e107951b188827b0da5dbba8e19a2dd0.
And the fixed is not used for now. Maybe it'll be useful, so I leave it there, but changed the name into an english version. Thanx for figuring this out.
