### ISSUE TITLE
What is/does /scss/mypub.scss?

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#130]

**Comment by nilswindisch** [comment]
seems to be necessary to get the familiar look, a tad less important than bielestrap, but still things shift around (visually) file if the files contents are not present in the main.css

**Comment by verheyenkoen** [comment]
That appears to be the file with all custom css definitions (in SASS/SCSS format). I added some rules there for issue #124. There's not much structure in that file though.

**Comment by vpeil** [comment]
@verheyenkoen Please, can you clean this up and provide a nice structure for this (if possible at all)? Also the naming is weird (same with #129 ).

**Comment by vpeil** [comment]
@verheyenkoen solved this with f6bcc1e
