### ISSUE TITLE
Use fontawesome 5

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#133]
Do not mix up glyphicons and font awesome!

Use font awesome 5 only (wait until this is released).
https://www.kickstarter.com/projects/232193852/font-awesome-5

**Comment by nilswindisch** [comment]
helpful in that context: https://github.com/LibreCat/LibreCat/search?utf8=%E2%9C%93&q=glyphicon

**Comment by nilswindisch** [comment]
maybe use a rather dirty overwrite fix: http://stackoverflow.com/questions/26638215/how-to-replace-glyphicons-with-fontawesome-in-bootstrap-3-without-changing-html

**Comment by verheyenkoen** [comment]
Related to #311

**Comment by vpeil** [comment]
Fontawesome 5 has been released: https://fontawesome.com/

Could be done in a frontend refactoring in combination with #136.

@verheyenkoen @phochste @petrakohorst what do you think?

**Comment by verheyenkoen** [comment]
Looks nice
