### ISSUE TITLE
Provide Perl ENV

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#146]
To make development / installation easy, provide some helpful environment variables.

**Comment by phochste** [comment]
Already there? https://github.com/LibreCat/LibreCat/wiki/Installation#perl

**Comment by vpeil** [comment]
well, I mean, environment variables, so you don't need e.g. to type `carton exec...` for the commands.

**Comment by phochste** [comment]
That is what the instructions do. Doesn't it?

On 3 Feb 2017, at 07:39, Vitali Peil <notifications@github.com<mailto:notifications@github.com>> wrote:


well, I mean, environment variables, so you don't need e.g. to type carton exec... for the commands.

-

**Comment by vpeil** [comment]
you're right. Sorry, I was a bit confused.
