### ISSUE TITLE
Sort by Title

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#147]
Does not work correctly for special characters, i.e. ä is put after z....

**Comment by phochste** [comment]
This is language dependent. German sorting is different than French sorting or Swedish sorting.
To do this correctly an extra Elastic Search plugin needs to be installed as explained in our installation wiki pages:

     sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.7.0

In the `store.yml` you can edit a `my_language` filter to the language of your choice. Add the 'my_language' to the 'tag' filters to make 'title' searches the German way:

         tag:
            type: custom
            tokenizer: keyword
            filter: [lowercase,my_language]

To use this plugin the entire elasticsearch index has to be dropped (or deleted from the filesystem) and needs to be recreated...

**Comment by vpeil** [comment]
Thanks for explaining. Since english is the preferred language for all installations I am closing with one. But it's good to it documented here if the issue appears in another context.

**Comment by phochste** [comment]
See also https://github.com/LibreCat/LibreCat/wiki/Cookbook
