### ISSUE TITLE
Prevent uploading multiple files with exactly the same name

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#148]
Make LibreCat file upload behave more like a normal file system: filter out all duplicate file names.

**Comment by vpeil** [comment]
Indeed: If you upload to files the the same name, only one will be on the FS.

**Comment by nicolasfranck** [comment]
In a case-insensitive way also?

**Comment by phochste** [comment]
Case-sensitive or not can be a configuration option

**Comment by nicolasfranck** [comment]
Note: uploader module should push forward an "id" parameter when uploading, so the receiving route can put all files into the same folder.

**Comment by phochste** [comment]
See #832
