### ISSUE TITLE
Add some security enhancers

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#15]
E.g.

https://metacpan.org/pod/Plack::Middleware::CSRFBlock

**Comment by vpeil** [comment]
is merged into dev. Make sure to run `carton install` to get the new dependencies....

**Comment by vpeil** [comment]
javascripts need also some consideration

**Comment by nicolasfranck** [comment]
@vpeil what do yo mean exactly?

**Comment by vpeil** [comment]
If activated in https://github.com/LibreCat/LibreCat/blob/dev/bin/app.pl#L60, the file upload does not work. @phochste said that javascripts have to be condsidered, too. See also https://metacpan.org/pod/Plack::Middleware::CSRFBlock#javascript

**Comment by nics** [comment]
CSRF protection works everywhere now.

**Comment by phochste** [comment]
The file upload is still not working with the CSRF code currently in the 'dev' branch. When going to the form to edit a record and upload any file I get a red CSRF error bar in view and the file upload stops.
