### ISSUE TITLE
Return button in the edit form doens't update the publication

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#151]
Reviewers complain in Ghent that publication updates don't get saved (e.g. comments) when clicking on the "return" button.

Also they would like to see records automatically unlocked when the "return" is clicked.

**Comment by vpeil** [comment]
The return button does only this: changes the status from public to return. No other fields are updated.
I am open to change this behviour.

**Comment by vpeil** [comment]
fixed with PR #173
