### ISSUE TITLE
Add Catmandu::Importer::LDAP to cpanfile

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#155]
According to the [new documentation](https://github.com/LibreCat/LibreCat/wiki/Import-Users) on user management one should use `bin/librecat` but can this actually work? `Catmandu::Importer::LDAP` is not in the  `cpanfile` of the dev branch.

**Comment by vpeil** [comment]
Has been added by @phochste some days ago on dev branch
https://github.com/LibreCat/LibreCat/commit/e9d963fa7750ec52265f51179fac35abaf0f26da
