### ISSUE TITLE
Citation processing can't be made optional

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#156]
In the configuration file `citation.engine: none` option is ignored

**Comment by phochste** [comment]
Also only the `citation.engine: csl` seems to work. All other options are ignored

**Comment by vpeil** [comment]
IMO that behaviour is covered by the test: https://github.com/LibreCat/LibreCat/blob/dev/t/LibreCat/Cmd/publication.t

is there a mistake?

**Comment by phochste** [comment]
There is an option to switch of citations completely by configuration (which isn't working).

**Comment by vpeil** [comment]
WHERE does this not work? command line or web?

**Comment by phochste** [comment]
Some things that I see:

- The none/template options in the configuration files aren't respected in LibreCat::Citation and Catmandu::Fix::add_citation
- The option citation.yml citation.zotero_styles isnt the same as is needed in LibreCat::Citation
- The only option that is used in the LibreCat code base is 'csl' it seems, all the rest are ignored.

**Comment by phochste** [comment]
There is also a memory leak in the citation processing. When a bulk publication upload is started via the command line with citation process on the memory of the Perl process will grow and grow.

**Comment by vpeil** [comment]
Ok, that's critical! Any suggestions which part of the code is responsible for that?

**Comment by phochste** [comment]
I'll try to investigate it further today

**Comment by phochste** [comment]
@vpeil  It is in catmandu itself..

**Comment by vpeil** [comment]
:open_mouth:

**Comment by phochste** [comment]
@vpeil The source is in Log::Any...

**Comment by vpeil** [comment]
switch off logging would solve it?

**Comment by phochste** [comment]
@vpeil No. Nicolas is creating for us a patch around it.

**Comment by nics** [comment]
Catmandu >=  1.0306 memoizes loggers and avoids the leak

**Comment by vpeil** [comment]
solved by @nics and @phochste on dev branch. Thank you, guys!
