### ISSUE TITLE
List of departments limited to 20 items

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#157]
The list of departments is limited to show 20 items.

Possible solutions:
1. display the full list (maybe very long!)
2. pagination
3. tree-like display

![bildschirmfoto 2017-02-08 um 10 28 53](https://cloud.githubusercontent.com/assets/4047340/22730990/6dc76938-ede9-11e6-9a6a-4fc1c267e7cc.png)

**Comment by vpeil** [comment]
1. oh yes, the limit of 20 items is the default in the search, can be changed easily (will do)
2. pagination: have to look into it. But code and templates should be generic with regard to pagination. Hence, should be an easy task, too.
3. hmm. we have to check this.

**Comment by dbeucke** [comment]
1. and 2. would be very helpful for us. 

Maybe we could find a frontend solution for 3. if we have a full list (1.).
