### ISSUE TITLE
How we could influence the order of departments list?

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#158]
We will have a list with several hundreds of departments. 
How we could influence the order of display the list?

**Comment by vpeil** [comment]
Commit e76a80911ca3d7727c53c16c07fb4af07bcda485 shows how to do it. If you don't like the sorting, put your own `department/nodes.tt` in your layer (yes, and you can sort in template toolkit).

**Comment by phochste** [comment]
@dbeucke @vpeil See also: https://github.com/LibreCat/LibreCat/wiki/Import-Departments#tree-display-sorting
