### ISSUE TITLE
Make the generation of thumbnails optional

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#162]
Uploading a giant batch file with records slows down because of citation processing and thumbnail processing.

Make it an option to stop citation **and** thumbnail processing. Provide examples how to generate these citations/thumbnails afterwards or via workers

**Comment by nicolasfranck** [comment]
CSL is now optional in the dev branch:

https://github.com/LibreCat/LibreCat/pull/289

**Comment by vpeil** [comment]
Since a [worker is used](https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Controller/File.pm#L302) for thumbnail generation is it still necessary to make it optional?

Is a huge queue a problem?

**Comment by phochste** [comment]
@vpeil Existence of a worker doesn't mean it is spawned into a gearman process. Currently sending of emails (and audit if configured) are the only real Gearman workers. All the rest executes in the thread of the single process handling files.

Sometimes you just want to switch thumbnail creation completely off. E.g. when doing mass edits on publications. This could also trigger mass regeneration of thumbnails.

**Comment by vpeil** [comment]
Basically, this comes down to the feature-flag "ignore-files", because when adding records with file-metadata via command line (i.e. `bin/librecat publication add some-publication.yml`) file-handling makes no sense. If you agree, I have almost a solution for that (and can push it).
