### ISSUE TITLE
The '+All' link ink the public interface for downloads doesn't work

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#166]
See: http://demo.librecat.org/publication/20#

What does it suppose to do?

**Comment by vpeil** [comment]
It should display all files, in this case all 5 of them. (There should be a js which triggers it)

This UI solution is not optimal. Any better ideas are very welcome.

**Comment by phochste** [comment]
It is due to Javascript errors. With the combination of JavaScript and Template Toolkit you get templates which are very long lines and very hard to debug. There has to be better ways to do this.
