### ISSUE TITLE
Exception after Login

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#176]
Hi all,
with 0.3.2 and the fix for the citations I get the following message after I log in:

{
   "error" : "core - template - date error - bad time/date string:  expects 'h:m:s d:m:y'  got: '2.012' at /srv/LibreCat/local/lib/perl5/Dancer/Template/Abstract.pm line 91.\n",
   "exception" : "Core::Template"
}

But after this I am logged in and click around normally.

**Comment by christianmahnke** [comment]
This only happens if you log in as admin, might be data related. We are currently thinking about a clean reimport, since this seems to be data typing related this might help.

**Comment by vpeil** [comment]
yes, could be data related.
