### ISSUE TITLE
Projects tab only shows the first 20 projects

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#177]
We have 11.000 projects in our Ghent environment. Need a paging or alphabetic browse like authors

**Comment by vpeil** [comment]
seems, that we need to inlcude `pagination.tt` in views/project/list.tt

**Comment by phochste** [comment]
@vpeil And a bit more..it is not user friendly to just browse 532 result pages

**Comment by vpeil** [comment]
:smiley_cat: search box?
