### ISSUE TITLE
Missing translation for meta data title in publication detail view

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#185]
Some meta data title are not translated in publication detail view:

e.g.
![bildschirmfoto 2017-03-02 um 14 51 27](https://cloud.githubusercontent.com/assets/4047340/23509912/bc75012e-ff57-11e6-8f63-c8e8aa94084d.png)
http://demo.librecat.org/publication/2737389

or
![bildschirmfoto 2017-03-02 um 14 51 56](https://cloud.githubusercontent.com/assets/4047340/23509920/cdf5868a-ff57-11e6-9009-a85ad55a3f4a.png)
http://demo.librecat.org/publication/20

**Comment by vpeil** [comment]
just add the missings part to config/locale.xx.yml, PR is welcome!

**Comment by dbeucke** [comment]
OK. Thanks. 
I will look.

**Comment by dbeucke** [comment]
DONE: https://github.com/LibreCat/LibreCat/commit/6cda16a6bed0ae67c3057fcc44eb43dd24755f3d
