### ISSUE TITLE
Broken citation tabs in publication detail view

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#186]
The tabs have strange array names and show now results.

<img width="780" alt="bildschirmfoto 2017-03-06 um 10 02 49" src="https://cloud.githubusercontent.com/assets/4047340/23603137/1a966d8e-0254-11e7-8738-5dab6a0397e3.png">

**Comment by vpeil** [comment]
tab names fixed. if there is no tab content, please check your record (e.g. with the "internal view"). Seems that there are no citations in the record.
