### ISSUE TITLE
InnoDB vs MyISAM

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#188]
Is there a special reason why InnoDB has been chosen as the default engine for MySQL over MyISAM? Some queries like:

   SELECT COUNT(*) from publication;

are awfully slow compared with the MyISAM version

**Comment by pietsch** [comment]
Just out of curiosity: What is the answer to this question?

**Comment by nics** [comment]
InnoDB is a much more robust and safe engine. MyISAM is faster for some operations. Data safety seems to me the more important factor.

**Comment by pietsch** [comment]
I just thought I should mention that a friend of mine has recently been bitten by this InnoDB bug which was filed in 2003 and is supposed to be fixed in an upcoming release: [Innodb autoincrement stats los on restart](https://bugs.mysql.com/bug.php?id=199).
