### ISSUE TITLE
Quick and Easy upload support for delegates and reviewers doesn't work

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#19]
The QAE upload has support in code to set a reviewer or a delegate, but the fields are never set by any controller or route and are always left empty in the forms as presented in the webinterface.

Is this setting of delegates/reviewers a feature/bug that needs to be solved or a work in progress that needs to be implemented, or something else?

**Comment by petrakohorst** [comment]
It's neither a bug, nor a work in progress. It's more of a conceptual problem that needs a solution.

We want to pre-set an author and a department in each new record, no matter if that's via the empty form or via quick-and-easy upload.

For regular users we already do that, but for delegates and reviewers this is not (always) possible. A person can be a delegate for several other people or a reviewer for several departments and once they open a new form or do a quick-and-easy upload, we don't know which of the delegate/department ids this record is meant for.

So the code you see in views/backend/qae.tt is in preparation of something I have not yet had the time to finish. I just don't know which id to use.

**Comment by vpeil** [comment]
We can display the quick and easy upload for **users only**. That is just sugar for researchers, delegates/reviewers can do the bibliographic stuff on their own, right?
