### ISSUE TITLE
DOI import make an error

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#193]
Add publication wit example DOI: 10.1371/journal.pbio.0020449
--> worked

use "edit" button
--> worked

use "Home" button
--> An internal error occured

http://demo.librecat.org/librecat?
--> don't work

**Comment by dbeucke** [comment]
On my local system (0.4.1) I got this message after upload the DOI.
```
{
   "error" : "Warning caught during route execution: Wide character in print at /srv/LibreCat/local/lib/perl5/Log/Log4perl/Appender/File.pm line 313.\n",
   "exception" : "Warning caught during route execution: Wide character in print at /srv/LibreCat/local/lib/perl5/Log/Log4perl/Appender/File.pm line 313.\n"
}
```

**Comment by vpeil** [comment]
The example DOI has no authors, which causes the problem.

Won't fix now, but need a way to catch this.
