### ISSUE TITLE
In the department page the hit counters are wrong

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#195]
In http://demo.librecat.org/department page there is a list of departments, and after each department there is a hit counter. Now all the counters are 0 (zero), however some departments really have hist, namely:

* http://demo.librecat.org/publication?cql=department=9997: 15 publications
* http://demo.librecat.org/publication?cql=department=9996: 15 publications
* http://demo.librecat.org/publication?cql=department=2685177: 1 publication
* http://demo.librecat.org/publication?cql=department=10085: 1 publication

**Comment by vpeil** [comment]
@phochste that's true, and you run
```
carton exec bin/librecat generate departments
```

it is still 0.
