### ISSUE TITLE
Creating Selenium based testing

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#196]

**Comment by vpeil** [comment]
I have investigated Travis-CI running Selenium tests: There is an external service https://saucelabs.com/ which can be integrated into travis (https://docs.travis-ci.com/user/sauce-connect/). But saucelabs is not for free...

have to search for other solutions

**Comment by vpeil** [comment]
merged into dev.

The easiest way to run selenium tests is:
```bash
$ docker run -d -p 4444:4444 selenium/standalone-chrome
$ SELENIUM_TEST=1 prove -lv t/selenium.t
```
By now these selenium test are running against http://demo.librecat.org. This should change in the future to a locally started server.

Thanks @pkiraly for your efforts with selenium.
