### ISSUE TITLE
Alias page doesn't work 

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#197]
Using the alias URL give no result (local -> 404; demo -> authors page)

**Comment by dbeucke** [comment]
Test wit test user on demo server: http://demo.librecat.org/person/test

**Comment by christianmahnke** [comment]
There also seem to be issues if a author ID contains a dot.

**Comment by dbeucke** [comment]
In our system it works with IDs (name+number like mschuh1); it isn't works with IDs (only name like glauer); and give an error with IDs contains a dot.

**Comment by vpeil** [comment]
ok, that's a case for more tests...(but today I 'm on the road)

**Comment by dbeucke** [comment]
The commit/patch work for us. So I close this issue.
