### ISSUE TITLE
Crossref CLI importer not working

### ISSUE THREAD

**Issue by njahn82** [LibreCat/LibreCat#199]
It seems that the [cookbook examples](https://github.com/LibreCat/LibreCat/wiki/Cookbook#import-one-more-many-crossref-records) for importing from Crossref are not working:

```
librecat@ddd557ea4d6f:~$ bin/librecat publication fetch 10.1371/journal.pone.0169754 > /tmp/data
need an identifier at /srv/LibreCat/local/lib/perl5/App/Cmd.pm line 468.
```

**Comment by vpeil** [comment]
the syntax is 
```
bin/librecat publication fetch crossref 10.1371/journal.pone.0169754
```
you need to specify the source

**Comment by njahn82** [comment]
ah great, will add it in the cookbook

**Comment by njahn82** [comment]
Works great, thanks! Have also fixed the cookbook.
