### ISSUE TITLE
Default sort options

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#208]
In `config/catmandu.yml`are definitions for default sort options.

But on demo server (and our own server) the default order seems to be different. 
http://demo.librecat.org/publication

**Comment by vpeil** [comment]
not confirmed. I see on the demo server exactly the sort options defined in `config/catmandu.yml`, both content and order. Does your layer cause the problem?

**Comment by dbeucke** [comment]
I mean the order in publication list.

In the yaml file I see:
```
    default_sort:
      - year.desc
      - date_updated.desc 
    default_sort_backend:
      - date_updated.desc
      - year.desc
```

But it looks like:

![bildschirmfoto 2017-03-20 um 15 29 48](https://cloud.githubusercontent.com/assets/4047340/24104277/1615857c-0d82-11e7-9b1e-0fb36b04986f.png)

This is not sorted by year!

**Comment by vpeil** [comment]
ah ok, is fixed now. (I've been looking at another line in the config. Let's reference the lines exactly we talk about. Will be much easier to follow up)
