### ISSUE TITLE
Sort order of author list

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#220]
Could I affect the sort order of the author list?

Yes -> where?

No -> please add this feature.

http://demo.librecat.org/person

![bildschirmfoto 2017-03-20 um 15 48 15](https://cloud.githubusercontent.com/assets/4047340/24105286/a76b90a0-0d84-11e7-8be6-ebb3b45ae079.png)

**Comment by vpeil** [comment]
we should sort by lastname per default

**Comment by phochste** [comment]
lastname was not configured as being sortable...
the catmandu.yml file now also contains a configurable parameter: `default_person_sort` to select how you want to see the persons sorted
