### ISSUE TITLE
Mark/unmark doesn't work

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#221]
The button "Mark/Unmark publication" doesn't work in current version (0.5.3). 
E.g. http://demo.librecat.org/publication/2737388

I get a JS error (see screenshot).
<img width="1348" alt="bildschirmfoto 2017-03-21 um 21 36 36" src="https://cloud.githubusercontent.com/assets/4047340/24169648/9243a9c4-0e7e-11e7-9d83-f48e23aecf32.png">

**Comment by vpeil** [comment]
any volunteers? or at least JS experts?

**Comment by vpeil** [comment]
thanks @petrakohorst for pointing out the problem
