### ISSUE TITLE
HTML-Tags in RTF export (APA style)

### ISSUE THREAD

**Issue by dbeucke** [LibreCat/LibreCat#223]
The exported RTF document (tested with APA style) contains HTML-Tags (`<i>` and `<a>`).

BTW: the DOI links looks strange.

![bildschirmfoto 2017-03-22 um 11 43 54](https://cloud.githubusercontent.com/assets/4047340/24194073/dbf3f648-0ef4-11e7-8ec4-594fca4fafba.png)

**Comment by vpeil** [comment]
no problem for the `<i>-Tags`. More problems with the DOI handling: it behaves differently between the CSL Processors (if we compare it to our php with still use in production)...

**Comment by dbeucke** [comment]
OK. `<i>-Tags` would be very helpful for us. 
The DOI links works with our data on our system.
