### ISSUE TITLE
Add language field to CSL json

### ISSUE THREAD

**Issue by njahn82** [LibreCat/LibreCat#224]
Would be great to have an language field mapped to CSL-JSON, so that non-english titles are not displayed in title case,

See

http://docs.citationstyles.org/en/stable/specification.html#non-english-items

http://demo.librecat.org/publication/2737396

**Comment by njahn82** [comment]
Any news, @vpeil ? Can I help?

**Comment by vpeil** [comment]
yes, please. Is the required field called `default-locale`? 

The language information in LibreCat is stored in `language.0.iso`.
