### ISSUE TITLE
Typing a return key in a input field triggers the submit of the form

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#23]
Edit any record. Put the focus on a input field and press 'return'. The form will be automatically submitted (but any changes are cancelled).

**Comment by vpeil** [comment]
@petrakohorst can you have a look, please. Probably, the return key is binded to the cancel button?

**Comment by vpeil** [comment]
@phochste yes, the return button triggers the submission of the form. But I cannot confirm, that changes are cancelled. Everything is saved correctly.

So, which behaviour would you like to have for the return button?

**Comment by phochste** [comment]
@vpeil Return and tab button are normally used to have a control of the form input without needing a mouse pointer to switch the focus to a new field. With Tab/return one puts the focus of the form to the next field in the form until the last field has been reached at that point the form will be submitted.
