### ISSUE TITLE
Routes for persons should be considered wrong

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#238]
See #214 and the discussion on Slack:

```
/person/*([a-z,A-Z])*
```
First problem I see is the asterisk behind the slash, why is it zero or more times? It should be zero or one time (?). Why is the group repeated? And why not using a end of string mark? BTW A '`,`' in a '`[]`’ will match a literal '`,`', it is not a seperator.
Replace it with `/person/?([a-zA-Z]?)$` and keep in mind this isn't the optimal solution either. It will fail for names starting with Umlauts ("Ücker") or names in other alphabets.
```
/person/(\d+|\w+|[a-fA-F\d]{8}(?:-[a-fA-F\d]{4}){3}-[a-fA-F\d]{12})/*(\w+)*/*
```
Is used to match numeric or UUID identifiers, this breaks the Alias feature, which we use in Göttingen.
The first group should match `(.[^/]{2,})`

Check all routes which are using the `qr()` syntax if the usage of asterisk is right. For me it tseems that there is a little confusion about which rules to use, either [Dancer wildcards](http://search.cpan.org/~bigpresh/Dancer-1.3202/lib/Dancer/Introduction.pod#WILDCARDS_MATCHING) or regular expressions. And don't use repeated grouping unless you really know what you are doing. Hint: If you repeat the grouping instead of an character you will end up in selection the last occurrance.

**Comment by vpeil** [comment]
Hi, I wanted to reopen your PR #214, but that wasn't possible. Do you know why?

**Comment by christianmahnke** [comment]
No, but I can't do this either. Maybe GitHub thinks that it's cheap enough to create new one. But from my point of view we should do that, since we've found out that this will have another implication as well: 
```
diff --git a/views/filters.tt b/views/filters.tt
index ebe2422..455d678 100644
--- a/views/filters.tt
+++ b/views/filters.tt
@@ -186,7 +186,7 @@ searchParams = [% qp.json %];
 
 $('#id_button_embed_[% tabmodus %][% menu %]').click(function() {
     var embed_link = window.location.href;
-    var person_id  = embed_link.match(/\/person\/([0-9ABCDEF-]{1,})/);
+    var person_id  = embed_link.match(/\/person\/(.[^\/]{2,})/);
 
     if (embed_link.match(/\/publication/)) {
       searchParams.cql.push("type<>research_data");
```
`filters.tt` has to reflect this change, otherwise it will break there later on. And we haven't tested yet how this will behave is there really is a suffix (what the second regex looks for, after the slash). I don't see that we catch this case.

**Comment by vpeil** [comment]
can you check this? I broke my dev box on friday and little time to fix this today.

**Comment by christianmahnke** [comment]
I'll try but I have a similar issue, I broke our dev server on Friday as well and need to fix this first...

**Comment by vpeil** [comment]
:face_with_head_bandage:

**Comment by christianmahnke** [comment]
I can create a PR for a temporal solution (I wouldn't call it a real solution since some things won't be addressed). I'll sketch it up here and list possible problems or left open questions.

Files#Lines to be changed:

- [lib/LibreCat/App/Search/Route/person.pm#L19](https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Search/Route/person.pm#L19)
`/person/?([a-zA-Z]?)$` should be the route for listing, this has the following issues:
  - Works only for names starting with A-Z in both cases, ÜÖÄ or other Unicode points won't work. But they are also not part of the alphabet navigation thing. I would think that the user is expecting a implied mapping like `Ä`->`A`, `Ü`->`U`, `À`-> `A` and so on, but this solution don't do this. A good solution would probably generate the alphabet navigation bar from whats in the index. This way even letters from other alphabets will be usable, these use cases aren't that far away as one might think. [One Example](https://bg.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%BB_%D0%A4%D1%80%D0%B8%D0%B4%D1%80%D0%B8%D1%85_%D0%93%D0%B0%D1%83%D1%81)  
   - Maybe it is possible to let Elastic search do the mapping to the base form of the characters. But this would probably a special query.

- [lib/LibreCat/App/Search/Route/person.pm#L59](https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Search/Route/person.pm#L59)
This is a bit more tricky since these matches two groups and the use of the second isn't completly understood. We will focus on the first part and remove problematic parts from the second.
 `(.[^/]{2,})/?(\w+)?/?` 
   - The first issue here that there isn't a way to use the second part, whats the use case and what' the click way, when do one end up here? From the code the use case is to filter for publication or research data. So probably you can get there if you click on a persons name while you are in the research data section, but since we have removed it, we aren't able to test.
  - The next problem is there is currently no limitation on the alias name of a researcher, so we need to actually work with `.`here.

- [views/filters.tt#L189](https://github.com/LibreCat/LibreCat/blob/master/views/filters.tt#L189)
  The regex should be changed to `\/person\/(.[^\/]{2,})` since we now allow a broad range of characters in here. This might change if there is a way to put constrains on an alias and enforce these in the editing form and during data import.
   - This imposes a risk if the uses uses the second group of the second regex. I'm not sure if this regex will find such a case.

**Comment by vpeil** [comment]
the following route are now supported and covered by a test!

```
/person/1
/person/124234
/person/1/data
/person/mycustomalias
/person/mycustomalias/data
```

the person list uses the following scheme
```
/person
/person?browse=a
```
