### ISSUE TITLE
Fields Links->Link to external source are not clear how they work

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#24]
These fields are not stored in the 'dev' branch

**Comment by phochste** [comment]
The field 'Link to external source' works but the interface is not very clear. You need to fill out this part of the form and you are required to click the 'Plus (+)' button to store the relation.

**Comment by vpeil** [comment]
yes, you 're right: the usability is not perfect. So we changed that a while ago on our production version.... we will try to merge this into dev.

**Comment by vpeil** [comment]
Should be working in dev branch, now.
