### ISSUE TITLE
Order of citation styles is random

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#242]
This is minor, and we thought it is somehow random for each server.
But this is on the same Docker image
![google chrome](https://cloud.githubusercontent.com/assets/2511875/24367586/7413a6ae-131d-11e7-9dcd-5e17c0827184.png)
Restart
![google chrome](https://cloud.githubusercontent.com/assets/2511875/24367588/762896c0-131d-11e7-90da-1a7db2e1452c.png)

You get the idea, but at last it seems to be stable for every user session.

**Comment by vpeil** [comment]
yes, that a perl "feature". if you read keys from a hash they are random in order. but we can sort them...at least all but Bibtex and RIS (because these are added to the one defined in config/citation.yml).
