### ISSUE TITLE
Malformed deleted records

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#245]
We've got some malformed records in our exports, which looks like this:
```
---
_id: 3145227
_version: 1
date_created: 2017-03-21T08:27:39Z
date_deleted: 2017-03-21T08:27:39Z
date_updated: 2017-03-21T08:27:39Z
status: deleted
```
Maybe this happens if imported records aren't stored by deleted (look at the timestamps).

**Comment by christianmahnke** [comment]
Related to #246

**Comment by phochste** [comment]
See #246

**Comment by christianmahnke** [comment]
This is also a ugly hack since it means it should be still possible to create malformed records using forged requests...

**Comment by phochste** [comment]
@christianmahnke No  there are extra checks that it is not possible to forge these requests

**Comment by christianmahnke** [comment]
Right, my bad, found it in https://github.com/LibreCat/LibreCat/commit/ad2f3081a842954b1ca2808dfc1d1d2cafd696a5
