### ISSUE TITLE
Output of internal view and `bin/librecat publication get` is different

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#248]
It's a huge problem to track down problems that the internal view and the command line output (`bin/librecat publication get`) of LibreCat is different. This also can cause problems if one wants to use the output of the internal view, put it in a file and reimport it on the command line. The result will be #247.

I can provide you an example if you can't reproduce this.

**Comment by vpeil** [comment]
#247 is a problem of its own, I think. The difference between these two are the quotation marks. The reason is, that we use two different implementations for the YAML export: `Catmandu::Exporter::YAML` on the command line and `to_yaml` method in the internal_view.

**Comment by christianmahnke** [comment]
Sure #247 is a problem of its own. The example was only that on can trigger #247 by using the output of the internal view. This is because the quotation marks have a meaning, they are a hint for the data type (string vs. integer). I would suggest that the internal serialization method should be used. That would be `Catmandu::Exporter::YAML`.
