### ISSUE TITLE
No validation against schema after import

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#250]
We tested #249 with a change to the schema (find a patch [here](https://github.com/subugoe/pubdev_docker/blob/master/patches/9054fix-schema.patch)). And we have the feeling that data that is imported via DOI from Crossref is not only not validated against the schema (which this issue should cover) but also that the mapping for the year field is wrong. I create another issue on this.

Please add schema validation on import via web UI. Make sure it is done after (!) the fixes run.

**Comment by vpeil** [comment]
look at this: https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Helper.pm#L347

first, records are fixed then validated. if it's ok the record is stored. This code is used for command line tools and in web UI.

**Comment by christianmahnke** [comment]
If this would be true, than we wouldn't have such a huge load of issues. #244 is about this. And it is also possible to create a #247 with a patched schema like [this](https://github.com/subugoe/pubdev_docker/blob/master/patches/9054fix-schema.patch) if the 
file `fixes/crossref_mapping.fix` isn't [patched](https://github.com/subugoe/pubdev_docker/blob/master/patches/9054crossref-fix.patch).

**Comment by phochste** [comment]
There are validation issues in LibreCat that must be solved. There are two mechanims, one via Javascript and one via the JSONSchema. Other than states above the JSONSchema validation is only for the command line tools. On the web the only way to communicate with the user on validation issues is via the jQuery-s..and that is problematic. When you store the record, there is nothing in the code to report back to the user "hey there is something wrong". This need to be fixed. The jQuery stuff needs get out and JSONSchema everywhere needs to be in.

**Comment by phochste** [comment]
It is a complicated knot to solve:

(1)

`views/backend/generator/fields/jquery_tab1.tt` contains the jQuery validation for the records. There  seems to be some things that are validated that can't be part of the JSONSchema. The web forms you see don't contain verbatim the same as the JSONSchema (for layout and user-friendly) reasons. The JSONSchema is also agnostic of the document type, the web forms not.

(2)

`lib/LibreCat/App/Catalogue/Route/publication.pm` contains code to store the record (e.g. line 232 `h->update_record('publication', $p);` but it doesn't have any code what to do when the record can't be stored (e.g. in case of a validation error).

At least problem(2) needs to be solved. Validation code needs to be added the the Helpers and everywhere code needs to be included when and why the validation doesn't like the input. 

(3)

In case of the imports from 'crossef' , 'bibtex' etc. .. the end-user can't do anything to solve validation errors. Here a validation error means: "libercat programmers the importer is buggy".

**Comment by vpeil** [comment]
I agree that (2) should be tackled (i.e. solved) first.

(3) Devs should look into error logs, improve mappings / schema. Add more example data to `xt/importer-fixes.t`

**Comment by nicolasfranck** [comment]
One reason why the json schema isn't all comprehensive is because of the complexity. There is too much hierarchical validation, that json schema cannot solve. Something like "if the type is a journal, then you should also check that field". Maybe it is better to split these forms? Otherwise the question will arise: "can you hide that field, when the field type is a journal, because it is not relevant in that case".
