### ISSUE TITLE
Citation style `short` isn't regarded as valid by `config/schemas.yml` 

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#252]
We also found a small problem during export of our user list and reimporting on the test system. The  citation style `short` isn't regarded as valid by `config/schemas.yml`. We've created a small [patch](https://github.com/subugoe/pubdev_docker/blob/master/patches/9054fix-citation-style.patch) that solves the issue for us. PR?

**Comment by vpeil** [comment]
we should do it like in https://github.com/LibreCat/LibreCat/blob/master/config/schemas.yml#L748

otherwise, you have to specify the styles in `config/citation.yml` and in `config/schemasyml`...
