### ISSUE TITLE
Make routes that require a login configurable

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#255]
Required for my local projects

**Comment by nics** [comment]
I tink the plugin only has support for username/password authentication

**Comment by vpeil** [comment]
yes, and it is a huge amount of work to migrate to Dancer2 (as my experiments on local dancer2 branch show)

**Comment by phochste** [comment]
I already have some code that does this. Trying to finish today

**Comment by phochste** [comment]
this=configurable authentication and roles
