### ISSUE TITLE
The hash_array() fix used in update_publication need to be made easier or removed completely

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#272]
In the `update_publication.fix` is a `hash_array()` function that cleans a bit arrays. Fields that need to be arrays are forced into arrays. Fields that don't need to be arrays are forced to be be objects (or strings).

Why is needed? What is the original reason why this fix was introduced (it feels a bit strange...)

The implementation needs to know which fields will be stored as arrays. For this the `forms.yml` configuration file is used to check the `multiple: 0|1` or `hash_array` parameter. Shouldn't this be set via the `schema.yml`?

**Comment by vpeil** [comment]
agreed. this need to be changed for consistency reasons. so maybe changes within the forms are required, too.

**Comment by vpeil** [comment]
branch https://github.com/LibreCat/LibreCat/tree/pr/issue_272 tackles this problem

**Comment by vpeil** [comment]
has been merged into dev.
it removes the hash_array() fix completly and aligns the code to this change.
