### ISSUE TITLE
bin/librecat delete search --bag publication doesn't work with Search::Elasticsearch 5.X

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#274]

**Comment by phochste** [comment]
Downgrading to Search::Elasticsearch 2.03 helps

**Comment by vpeil** [comment]
@phochste shouldn't this be done in the cpanfile? It contains something different by now https://github.com/LibreCat/LibreCat/blob/dev/cpanfile#L24

**Comment by phochste** [comment]
This was a configuration issue that is solved now
