### ISSUE TITLE
embargo_to field can be deleted when the embargo date is processed

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#276]

**Comment by phochste** [comment]
Do 

   bin/librecat publication embargo update > /tmp/data.txt
   bin/librecat publication files /tmp/data.txt

The script must delete the emargo_to field when the embargo field is removed.

**Comment by vpeil** [comment]
Some magic happens here: Where is the code snippet which deletes the `embargo` field? I guess, that would be to correct place to delete the `embargo_to` field, too.

**Comment by phochste** [comment]
It is a cron job that needs to run periodically that executes the bin/librecat publication embargo command.

See also `etc/librecat.crond`

**Comment by vpeil** [comment]
that clear to me. I mean if you run`this command
```
bin/librecat publication files /tmp/data.txt
```
embargo gets deleted, but not embargo_to. But I can't see the exact lines of code in lib/LibreCat/Cmd/publication.pm where this happens.

**Comment by phochste** [comment]
The `bin/librecat publication files` command is a procedure to view and change the metadata of the `files` section in publications. You give it a TSV file with the changes you want to do. Giving a column a `NA` values deletes the column-named keys from the file section:

https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Cmd/publication.pm#L636

The 'NA' field will be set for things out of embargo here:

https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Cmd/publication.pm#L480

**Comment by vpeil** [comment]
the solution is on branch https://github.com/LibreCat/LibreCat/tree/pr/delete_embargo_to

I switch the output format from TSV to YAML. Some complexity was hidden in prinft.... (producing TSV).
Now, the code is clearer and cleaner at this point with YAML output.
Is that change ok for you?

**Comment by vpeil** [comment]
fixed.
