### ISSUE TITLE
Helper-><bag> functions shouldn't be used to retrieve records

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#277]
In `LibreCat::App::Helper::Helpers` there these methods to get easy access to `publication` , `researcher` , `project`, `department` and `research_group`: 

    h->publication
    h->researcher
    h->project
    ...

These functions shouldn't be used to retrieve metadata records because they are connected to the ElasticSearch store and not to the backup primary database store. In general there is no guarantee that the ElasticSearch will contain exactly the same metadata fields as the backend store (most scenarios they contain the same data, but nothing forbids adding more data to the elastic search e.g. when creating new facets).

All the web interfaces should work like the command line tools: read always data from the backup store and only search the ElasticSearch store.

In case of `LibreCat::App::Catalogue::Controller::Material` the usage of the ElasticSearch store is even wrong (it updates the ElastricSearch store not the primary database)

**Comment by vpeil** [comment]
fixed on dev.
