### ISSUE TITLE
quote characters in CSV export

### ISSUE THREAD

**Issue by ckrempe** [LibreCat/LibreCat#280]
creating a CSV file from MARC record I get CSV fields with and without quote characters:

sepid,titel,subtitel,publart,quelle,auflage,erscheinungsort,verlag,erscheinungsjahr,bandheftjahr,schriftenreihe,url,isbn,issn,doi,url,patentnummer,sprache,seiten,aufsatzart,jahrgang
43894,"New species of Graphidaceae from the Neotropics and Southeast Asia.",,Z,Phytotaxa,,Auckland,"Magnolia Press",2014,"189, 1, (2014), S. 289-311",,,,1179-3155,10.11646/phytotaxa.189.1.21,,,eng,,,2014

Is it possible to force (or force not) quotes?

**Comment by vpeil** [comment]
Probably, you are in the wrong repo: https://github.com/LibreCat/Catmandu
The CSV Exporter has the option "always_quote".
```
catmandu .... to CSV --always_quote 1 > file.csv
```
