### ISSUE TITLE
Changing publication type of an already created publication fails

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#288]
A user opens an existing publication for editing and changes the publication type. After confirming the message "Changing the publication type may result in loss of data if the new type uses different fields from the previous one! Proceed with caution" with ok the user is redirected to his home.
(Redirect from https://host.de/librecat/record/change_mode to http://host.de/librecat [https-> http!])
Catmandu.local contains:
host: "https://host.de"
person:
  staffdirectory: "https://host.de/person/"
Why is librecat using http and not https? Is this the reason for redirection to /librecat?
We are using librecat behind an apache proxy.

**Comment by nicolasfranck** [comment]
Librecat isn't using https. The communication between the proxy and the backend server is http (and should be as librecat isn't communicating directly with the outside world).

It's hard too see what actually happens here without including the proxy configuration of apache.
Check out if there any uses of "http://host.de" in one of your yaml-files:

```
grep config.yml "http://host.de"
grep config/*.yml "http://host.de"
```

**Comment by datango** [comment]
This is the apache config:
Listen *:80
Listen *:443

<VirtualHost *:80>
  ServerName host-short.de:80
  ServerAlias host   #without .de
  RedirectMatch ^/(.*) https://host.de/$1
</VirtualHost>

<VirtualHost *:443>
  ServerName host.de
  RewriteEngine On
  ProxyPass / http://localhost:5000/
  ProxyPassReverse / http://localhost:5000/
  DocumentRoot /var/librecat/LibreCat/public

   SSLEngine on
   SSLCertificateFile /etc/ssl/certs/host.de.pem
   SSLCertificateKeyFile /etc/ssl/private/host.de.key
   # avoid BREACH attack
   SetEnv no-gzip

</VirtualHost>

These are the occurrences of host.de in catmandu.local.yml
default_lang: en

host: "https://host.de"

# Specity the ipranges which can download (local) files
ip_range:
    - 127.0.0.1
    - 10.0.0.0/8

person:
  staffdirectory: "https://host.de/person/"

**Comment by nicolasfranck** [comment]
Mm, seems like apache isn't sending the header "X-Forwarded-Protcol" by default.
Should be added:
```
RequestHeader set X-Forwarded-Proto "https"
```

**Comment by nicolasfranck** [comment]
By the way, you shouldn't configure the staffdirectory like this. The default already redirects
```
/staffdirectory/:id
```
to
```
/person/:id
```
(note: these are internal routes)

This configuration option is used to redirect from /staffdirectory/:id to an external website, like your institutional phone book.

**Comment by datango** [comment]
Thanks for your replies. 

Adding the X-Forwarded-Header didn't work. Also i tried it with http://. Also this doesn't work.
I'm always been redirected to the host.de/librecat-Page

**Comment by vpeil** [comment]
I don't think that the arguments above have sth. to do with the problem.
Commit 7159e46474db391d2ea47aad94d936d2ba9653bd solves this problem. This was due to a cleanup and a route which handled **two** different tasks. So this route was partially restored and renamed.

Should be released soon.

**Comment by nicolasfranck** [comment]
Ok, and part of the current branch "dev". @datango : could you retry from that branch and see if your problem is fixed?

**Comment by datango** [comment]
I pulled the dev branch. Changing the publication type resultet in the following erorr:

{

    "error": "No such package: LibreCat::Hook::form2schema(publication_identifier)\n\nTrace begun at /var/librecat/LibreCat/local/lib/perl5/Catmandu/Util.pm line 683\nCatmandu::Util::require_package('form2schema(publication_identifier)', 'LibreCat::Hook') called at /var/librecat/LibreCat/lib/LibreCat.pm line 65\nLibreCat::hook('LibreCat', 'publication-change-type') called at /var/librecat/LibreCat/lib/LibreCat/App/Helper.pm line 33\nLibreCat::App::Helper::Helpers::hook('LibreCat::App::Helper::Helpers=HASH(0x4429068)', 'publication-change-type') called at /var/librecat/LibreCat/lib/LibreCat/App/Catalogue/Route/publication.pm line 410\nLibreCat::App::Catalogue::Route::publication::__ANON__ at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 263\nDancer::Route::execute('Dancer::Route=HASH(0x5dffb08)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 186\nDancer::Route::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 101\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 94\nTry::Tiny::try('CODE(0x6c058f8)', 'Try::Tiny::Catch=REF(0x6c174e8)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 200\nDancer::Route::run('Dancer::Route=HASH(0x5dffb08)', 'Dancer::Request=HASH(0x7273990)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 137\nDancer::Renderer::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 103\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 94\nTry::Tiny::try('CODE(0x6a2fae8)', 'Try::Tiny::Catch=REF(0x68f6588)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 146\nDancer::Renderer::get_action_response('Dancer::Renderer') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 33\nDancer::Renderer::render_action('Dancer::Renderer') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 84\nDancer::Handler::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 101\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 94\nTry::Tiny::try('CODE(0x3677f18)', 'Try::Tiny::Catch=REF(0x68f6558)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 113\nDancer::Handler::render_request('Dancer::Request=HASH(0x7273990)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 76\nDancer::Handler::handle_request('Dancer::Handler', 'Dancer::Request=HASH(0x7273990)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer.pm line 491\nDancer::_start('Dancer', 'Dancer::Request=HASH(0x7273990)') called at /var/librecat/LibreCat/bin/app.pl line 64\nPlack::Sandbox::_2fvar_2flibrecat_2fLibreCat_2fbin_2fapp_2epl::__ANON__('HASH(0x6c114b8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/App/Cascade.pm line 48\nPlack::App::Cascade::__ANON__('CODE(0x374bec0)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x6c001e8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x6a1f4b8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x6c17680)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x6a1f530)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 198\nStarman::Server::dispatch_request('Starman::Server=HASH(0x3146f30)', 'HASH(0x6c114b8)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 298\nStarman::Server::process_request('Starman::Server=HASH(0x3146f30)', 'Net::Server::Proto::TCP=GLOB(0x6a852a8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server.pm line 74\nNet::Server::run_client_connection('Starman::Server=HASH(0x3146f30)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 229\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 229\nNet::Server::PreFork::run_child('Starman::Server=HASH(0x3146f30)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 187\nNet::Server::PreFork::run_n_children('Starman::Server=HASH(0x3146f30)', 5) called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 111\nNet::Server::PreFork::loop('Starman::Server=HASH(0x3146f30)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server.pm line 60\nNet::Server::run('Starman::Server=HASH(0x3146f30)', 'port', 'ARRAY(0x6802118)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 0, 'group', '0 0 0', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1, 'background', 1, 'setsid', 1) called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 94\nStarman::Server::run('Starman::Server=HASH(0x3146f30)', 'CODE(0x6059b80)', 'HASH(0x65d3df0)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Handler/Starman.pm line 25\nPlack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x65d3d30)', 'CODE(0x6059b80)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Loader.pm line 84\nPlack::Loader::run('Plack::Loader=HASH(0x14afac0)', 'Plack::Handler::Starman=HASH(0x65d3d30)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Runner.pm line 277\nPlack::Runner::run('Plack::Runner=HASH(0x12893b0)') called at /var/librecat/LibreCat/local/bin/plackup line 7\n",
    "exception": "Catmandu::NoSuchPackage"

}

**Comment by vpeil** [comment]
restart?

**Comment by vpeil** [comment]
ah! and all the rest. carton install, generate forms, restart service...

**Comment by datango** [comment]
yes, i did. And i tried it a second time. No change. The error occurs.
Is this correct?:  git pull --tags origin dev

**Comment by vpeil** [comment]
no. you have to checkout the remote branch:
git checkout -b dev origin/dev

**Comment by datango** [comment]
Same problem.
su librecat
git checkout -b dev origin/dev
git pull
carton install
carton exec bin/librecat generate forms
as root: systemctl restart librecat (also did a stop start with check)

**Comment by nicolasfranck** [comment]
@vpeil : I think the problem is here:
```
views/backend/generator/fields/document_type.tt
```
that contains this code:
```
$('#edit_form').attr('action','/librecat/record/change_type');
```
So it sends the form to "/librecat/record/change_type" that does not exist
behind a proxy server.

I'll fix this in the next release, prepending the uri_base to the path.

**Comment by nics** [comment]
The fixes can be packaged as a hook:

```
package LibreCat::Hook::bla;

use Catmandu::Sane;
use Catmandu;
use Moo;

has fixer => (is => 'lazy', handles => [qw(fix)]);

sub _build_fixer {
    Catmandu->fixer->new(fixes => ['i
      form2schema(publication_identifier)
      form2schema(external_id)
      page_range_number()
      clean_preselects()
      split_field(nasc, " ; ")
      split_field(genbank, " ; ")
      split_field(keyword, " ; ")
      vacuum()
    '])
}

```

**Comment by vpeil** [comment]
1. PR #298 introduces the above mentioned hook.

2. 
> @vpeil : any idea what changed?

No idea. It seems that this function was broken for some time, when I deleted the route. But as you mentioned, that did not solve the proxy problem.

**Comment by nicolasfranck** [comment]
@datango : could you retry the dev branch once more?

**Comment by datango** [comment]
Now it works! Thanks!
