### ISSUE TITLE
config/exporter.yml used incorrectly

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#293]
In
```
config/exporter.yml
```
does not consist of named exporters as it should be.
```
Catmandu->exporter("publication")
```
would simply crash because "publication" does not consist of the required keys "package"
(and "options"). 

The purpose of this file is to configure export formats for publications, but
it doesn't seem like the right place to do this.

Shouldn't this be moved to somewhere else?

**Comment by vpeil** [comment]
I see, it breaks with the convention of how we usually use this in Catmandu context.

Moving/renaming to `export_options` or something similar is desirable.

Any volunteers?

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/296
