### ISSUE TITLE
Output of route /export not always clear

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#294]
Looking at the code of
```
LibreCat::App::Search::Route::export
```
the output is always a list of publications,
determined by these parameters:

* q
* start
* limit
* sort
* fmt
...

But in some cases, the request "referer" is taken into account:

* /publication: cql filter "type<>research_data" is added
* /data: cql filter "type=research_data" is added
* /marked: cql filter is overriden, based on the marked ids in the session key "marked".

Not sure wether a request referrer should be used in a rest api. 

Shouldn't it be better to create an extra route for those three cases, where the cql filter
is added and the request forwarded to the route /export? Something is already done for
the export of one publication:
```
get '/publication/:id.:fmt' => sub {
    my $id = params->{id};
    my $fmt = params->{fmt} // 'yaml';

    forward "/export", {cql => "id=$id", bag => 'publication', fmt => $fmt};
};
```

**Comment by nicolasfranck** [comment]
Also explains why routes like
```
/data/123.json
```
do not exist, even while a link is available in the website.

**Comment by nicolasfranck** [comment]
Another thing:
```
/publication/1234.json
```
returns an array, not something you would expect from a "one-object-only" route.
Of course, this is caused by the forward to the route /export, that always exports
multiple things.

The route "/export" can only distinguish between array output of hash if "id" becomes a public parameter, used by the method "extract_params". When provided it should override/delete these parameters:
* q
* cql
* text
* start
* limit

**Comment by nicolasfranck** [comment]
About /export to export marked records:

/marked shows ALL marked records in one page.
(necessary when you want to reorder)

/exports pages it results using start and limit.

But /marked uses the route "/export" to export the records,
which means that only a portion of the data is exported..

**Comment by vpeil** [comment]
> Should the exporter of /marked also export ALL the records at once?

Yes, I guess that a user would expect this behaviour: Get everything you see.

**Comment by vpeil** [comment]
another issue appeared: It is not clear when private records are exported. Should `/export` be a public route only? Do we need an export feature for private records?

**Comment by nicolasfranck** [comment]
A possible solution:

* provide a route for export per record ( already exists: publication/:id.:format ? )
* provide a route to export multiple records, based query parameters

One can easily restrict access to the first route.

For the second one can store the query parameters, retrieve the records later, and send the export in an email, because there are possible a lot of records to export, and you don't want to create a vulnerability for DOS attacks.

**Comment by vpeil** [comment]
@nicolasfranck what do you mean by
> One can easily restrict access to the first route
??

And can we decide on the suggestion concerning DOS attacks? It would be nice to solve both export tickets in a coherent way.

**Comment by nicolasfranck** [comment]
@vpeil by use of the configuration file config/permissions.yml

A request to a single record is hardly considered a DOS attack, let alone one can easily determine all possible urls, and request them all. 

But a request that can take a while can easily slow down your server. Either one pages the result, or one sends the full export in an email.

**Comment by datango** [comment]
We use the Export url like https://librecatserverdemo.de/export?fmt=json&q=person%3D1234 for our CMS-Plugin. So i need access to the date directly. Sending/getting an email is not an option. For direct export response you could require a login.

**Comment by vpeil** [comment]
Concerning @datango's last comment. In the future this CMS-Plugin should be powered by an internal data API, which we plan for LibreCat. So that /export should be used for UI interactions
