### ISSUE TITLE
Autocompletion of department: If no department is found the field loses the focus

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#299]
When you edit a publication and try to add a department you start typing some letters. While some departments are found you can delete chars. But if no departments are found the input field loses the focus and pressing the delete key loads the previous page in the browser ("going back").

**Comment by verheyenkoen** [comment]
Additional related bug: sometimes the suggestion list is hidden and focus is lost when just typing the next letter. Eg: when you type "Department " you get the suggestion list. When you then type "o" it is gone again and the focus is lost, even though almost all options start with "Department of ...".

**Comment by verheyenkoen** [comment]
Added 2 tests for this in branch [issues/299](https://github.com/LibreCat/LibreCat-Frontend-Tests/tree/issues/299). Can be merged in master when issue is fixed.

To run tests:
```
$ $(bin npm)/cypress run --spec cypress/integration/issues/issue-299.spec.js
```

**Comment by verheyenkoen** [comment]
I addressed the focus part of this issue. That test now works.

The other part is in the backend. For some routes, no results are returned which is very inconsistent:

> http://localhost:5001/get_department?term=Department
6 results
>http://localhost:5001/get_department?term=Department+
6 results
> http://localhost:5001/get_department?term=Department+o
0 results
> http://localhost:5001/get_department?term=Department+of
6 results

**Comment by vpeil** [comment]
I checked this, too. It must be the indexing: e.g. Typing "math" should retrieve results for "math*". But one only gets resutls for "mathematics". 

@phochste any ideas what went wrong with the index?

**Comment by verheyenkoen** [comment]
@vpeil I don't think there are any departments that contain "math" but not "mathematics" (in the default data):

![image](https://user-images.githubusercontent.com/599538/33010067-64fe2a96-cdd9-11e7-8b95-689bdcf9a41f.png)

**Comment by verheyenkoen** [comment]
I now noticed it seems to match only whole words. So "department" matches, but "dep" or "departmen" doesn't.

**Comment by vpeil** [comment]
@verheyenkoen that's exactly what I meant!

**Comment by verheyenkoen** [comment]
Oh ok, misread your comment there.

**Comment by phochste** [comment]
There was a wrong implementation of search in the Route::ajax. It uses the sanitized CQL query search for the front-end where all special characters are taken literal. E.g. so that you can search on: "Are Be*-atoms stable?" (escaping the `*` and `?`).
I'm fixing this for the Ajax requests to use raw cql queries.

**Comment by phochste** [comment]
The issue with typing 'dep' and not finding 'department' should be solved now in the `dev` branch.
