### ISSUE TITLE
dev master merge

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/LibreCat#30]
I have merged our current master branch into the dev branch and created a new branch called test_merge_dev (I know, I'm not very creative when it comes to branch names...).

There are still some issues with file upload (or the file store?): dropzone in the edit form doesn't work. And with request a copy: creation of rac link doesn't work. But maybe these are problems that already existed in the original dev branch?

Once these problems have been solved, you should be able to merge the test_merge_dev branch into dev.

**Comment by phochste** [comment]
The file upload works for me in the 'dev' an the 'test_merge_dev' branch.  Are your local settings correct for the filestore paths?

**Comment by phochste** [comment]
test_merege_dev and dev are merged now
