### ISSUE TITLE
File - Access Level - ReadOnly

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#300]
For external project reviewer it would be great to grant access to publication files but not giving them write access to the publications at all.

Posible solution:
Additional to Project Reviewer or Reviewer two new rights:  Project Reviewer (readonly) or Reviewer (readonly). Then we could grant access to files by restriction to "Closed Access (Author/Reviewer only)"

**Comment by vpeil** [comment]
Has been fixed by f7fb2f0 (long time ago). See `config/permissions.yml` for related configuration options.
