### ISSUE TITLE
Does the author.id.exact have any effect?

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#303]
https://github.com/LibreCat/LibreCat/blob/dev/config/store.yml#L500

**Comment by vpeil** [comment]
What is this question about? The link above point to something different than expected.

**Comment by petrakohorst** [comment]
Is this maybe in relation to this PR https://github.com/LibreCat/LibreCat/pull/549 ?

**Comment by phochste** [comment]
Forgot what this issue was and it is badly explained by me. Closing
