### ISSUE TITLE
Hard-coded URL in scss/print.scss

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#327]
What is this for?

https://github.com/LibreCat/LibreCat/blob/dev/scss/print.scss#L26

**Comment by verheyenkoen** [comment]
This has to do with a print feature where the url of hyperlinks is appended after the anchor text when you print a page. This rule only works on relative urls (starting with "/") and adds the bielefeld domain name.

You can see the result in this screenshot for the publications anchor. I tossed the domain out of the href attribute there and this is what you get:

![image](https://user-images.githubusercontent.com/599538/31543841-646c1af4-b018-11e7-83fc-119ef0a8fb09.png)

Obviously, this should not be in this repo. I guess you can add this rule in a layer?

**Comment by vpeil** [comment]
thanks for explaning!

So, do we want the people to print our pages? Do we need print.scss at all?

**Comment by verheyenkoen** [comment]
I meant only that particular CSS rule with the the reference to the Bielefeld domain should not be in there.

It's never a bad thing to think about how a print should be styled. The url's behind the anchors is actually a smart feature.

**Comment by vpeil** [comment]
ok, could you please add it like suggested and generate a fresh main.css?

**Comment by vpeil** [comment]
fixed in commit a4ceca35267c033d2cb315b802fa320b6ac6d554
thanks @verheyenkoen
