### ISSUE TITLE
Missing quick link to marked publications on publication overview page

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#328]
I need to click always the details of one publication to find a list to all marked publications. Put also this link on the publication overview page.

**Comment by verheyenkoen** [comment]
Where do you want this in the sidebar? 
![image](https://user-images.githubusercontent.com/599538/31828049-889f82fc-b5b9-11e7-92d2-6a05ca6155aa.png)

**Comment by phochste** [comment]
For now under Export/Embed. This is the position the "Marked publication" has on the detail page.
