### ISSUE TITLE
Installation doesn't work as documented, dependency missing in CPAN

### ISSUE THREAD

**Issue by cmahnke** [LibreCat/LibreCat#33]
Running the cpanminus application to install dependencies fails for Catmandu::Importer::CrossRef

> MacBook-Pro-5:LibreCat cm$ sudo cpanm-5.22 --notest --installdeps .
> --> Working on .
> Configuring /Users/cm/projects/LibreCat ... OK
> ==> Found dependencies: Catmandu::Importer::CrossRef
> ! Finding Catmandu::Importer::CrossRef on cpanmetadb failed.
> ! Finding Catmandu::Importer::CrossRef (0) on mirror http://www.cpan.org failed.
> ! Couldn't find module or a distribution Catmandu::Importer::CrossRef
> ! Installing the dependencies failed: Module 'Catmandu::Importer::CrossRef' is not installed
> ! Bailing out the installation for ..

**Comment by pkiraly** [comment]
I got the same result.
```
$ carton
Installing modules using /home/pkiraly/LibreCat/cpanfile
Successfully installed Test-LeakTrace-0.15
...
Successfully installed Catmandu-Inspire-0.265
! Couldn't find module or a distribution Catmandu::CrossRef
Successfully installed Plack-Middleware-ReverseProxy-0.15
...
! Installing the dependencies failed: Module 'Catmandu::CrossRef' is not installed
! Bailing out the installation for /home/pkiraly/LibreCat/.
377 distributions installed
Installing modules failed
```

It has a consequence: some other things in Librecat are also go wrong, for example the indexing.

get the number of records in Elasticsearch before indexing:
```
$ curl -XGET 'http://localhost:9200/_cat/indices?v'
health status index    pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   librecat   5   1      39805            0    196.7mb        196.7mb 
```
drop index:
```
$ ./index.sh drop
Dropping index..
researcher...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
publication...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
department...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
research_group...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
project...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
award...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
Done
```

indexing:
```
$ ./index.sh create
Creating index...
researcher...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
publication...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
department...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
project...
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
Done
```

get the number of records in Elasticsearch after indexing:
```
$ curl -XGET 'http://localhost:9200/_cat/indices?v'
health status index    pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   librecat   5   1      39805            0    196.7mb        196.7mb 
```

You can see that the two numbers (before and after) are the same, so the dropping of index did not have any effect. If I run `carton install` as the error messages suggest, I get another error messages:

```
$ carton install
Installing modules using /home/pkiraly/LibreCat3/cpanfile
! Couldn't find module or a distribution Catmandu::CrossRef
! Installing the dependencies failed: Module 'Catmandu::CrossRef' is not installed
! Bailing out the installation for /home/pkiraly/LibreCat3/.
Installing modules failed
```

I followed the [installation Wiki page](https://github.com/LibreCat/LibreCat/wiki/Installation) on an Ubuntu 14.04 machine. Vitali's Crossref module (which was indexed by Google) is no longer available on CPAN: http://search.cpan.org/~vpeil/Catmandu-CrossRef-0.006/ gives a Not found error.

**Comment by pkiraly** [comment]
A workaround:

1) comment out the following line in `cpanfile` file (in the root of the project):
```
requires 'Catmandu::CrossRef';
```

2) run `carton install`.

The result is that a new file called `cpanfile.snapshot` will be created, and you the `./index.sh drop` and `./index.sh create` commands will work as expected.

**Comment by vpeil** [comment]
@pkiraly you are right: Catmandu::CrossRef has been deleted from CPAN, but I don't know why. I'll push a new version there. 

But this module isn't used anymore in the code, so (as you suggested) I've deleted this from cpanfile (see commit 9658714ce85249855b195da775f91580b1ab2201 on dev branch).
