### ISSUE TITLE
Marking/unmarking of publications fires 2 XHR requests

### ISSUE THREAD

**Issue by verheyenkoen** [LibreCat/LibreCat#330]
Whenever you (un)mark a publication in LibreCat it fires 2 XHR (ajax) requests. I guess that's redundant and should be just 1.

![image](https://user-images.githubusercontent.com/599538/31766863-52074a04-b4c9-11e7-9f88-6320610812e8.png)

**Comment by verheyenkoen** [comment]
@nics Can you confirm?

**Comment by nics** [comment]
looks like a bug

**Comment by vpeil** [comment]
I see the same behaviour. bug.

**Comment by vpeil** [comment]
here is the responsible js: https://github.com/LibreCat/LibreCat/blob/dev/public/javascripts/frontend.js

**Comment by verheyenkoen** [comment]
Same thing for `GET /marked_total` when opening a publication detail page.

**Comment by verheyenkoen** [comment]
Added 3 tests for this in branch [issues/330](https://github.com/LibreCat/LibreCat-Frontend-Tests/tree/issues/330). Can be merged in master when issue is fixed.

To run tests:
```
$ $(npm bin)/cypress run --spec cypress/integration/issues/issue-330.spec.js
```

**Comment by verheyenkoen** [comment]
Tests merged.
