### ISSUE TITLE
Dedup functionality

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#335]
Have a look at the Eprints plugin:
https://scholarlycommunications.jiscinvolve.org/wp/2017/10/26/weeding-out-duplicates-on-eprints-new-plug-in-makes-life-easier/

I am just collecting it here. Maybe we find time and concepts to implement dedup functionality into LibreCat.

**Comment by phochste** [comment]
What is the relation to the `Search similar titles` functionality in LibreCat?

I would like to see batch editing functionality for library admins like those exists in library catalogs via the facets on fields. Facets edit interface provides for one field and overview of an alphabetical list of all the values available in the database, together with a count. A librarian can change the
value of one value in a batch. E.g. she sees:

```
 years:
    2017                              (198)
    2016x                             (2)
    2016                              (213)
    2015                              (164
``` 

The value 2017 is used 198 in the database, 2016x 2 times..which is obvious a typo. With a batch edit she can change 2016x into 2016 for all records having this typo.

Using a facet on title also doubles can be found in the database.

**Comment by vpeil** [comment]
I like the idea. We should look at it after solving issue #341
