### ISSUE TITLE
LibreCat::App::Catalogue::Controller::Permission::Permissions can_edit is too complex for a simple record field check

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#337]
The `can_edit` method in `LibreCat::App::Catalogue::Controller::Permission::Permissions` executes a complex CQL query when a simple `get_publication` would be enough:

```
sub can_edit {
    my ($self, $id, $login, $user_role) = @_;

    my $user = h->get_person($login);

    my $cql = "id=$id AND ..."

    ...
```

All the code after `AND` and further in the method is not required when an $id of the publication is known. Fetch the known publication and check the permissions inspecting the record.

**Comment by nicolasfranck** [comment]
cf. https://github.com/LibreCat/LibreCat/tree/issue_337

I changed the signature of the permission functions to this:

```
can_edit ( $pub, user => $user_record, role => $role_name )
can_delete ( $pub, user => $user_record, role => $role_name )
can_delete_file ( $pub, user => $user_record, role => $role_name )
can_download ( $pub, user => $user_record, role => $role_name )
```

The $pub is the record as fetched from the backup store.

As @nics said, using the cached record has a disadvantage:

* fetch $pub from the backup store (you have edit rights)
* do some stuff
* someone else updates record (so you loose edit rights)
* call method can_edit is still based on old record.

He argues to use the publication identifier as the first parameter.

But you can also do all your operations within a transaction.

**Comment by vpeil** [comment]
:+1:  for using IDs as @nics suggested

**Comment by nicolasfranck** [comment]
Ok I changed a few things:

* signature is now:

```
can_edit( $id, $opts )

# $id is the publication identifiers
# $opts is a hash reference containing user_id and role
```

Yes I changed "user" to "user_id", because that is somewhat unclear in the code.
Rest is written in the perldoc

* remove dependency "Dancer" so we can use this outside of a request.

**Comment by nicolasfranck** [comment]
See PR https://github.com/LibreCat/LibreCat/pull/345

**Comment by vpeil** [comment]
PR #345 is closed. Is this issue done?

**Comment by phochste** [comment]
With the new permissions it is not possible to add new records

**Comment by nicolasfranck** [comment]
Well, it was open for review. So, if it looks ok for you all, then its considered done.

**Comment by vpeil** [comment]
Anyway, we have another test case ;-)

**Comment by phochste** [comment]
The test is covered by the integration test. A fix will follow in a minute

**Comment by vpeil** [comment]
PR #879
