### ISSUE TITLE
Prepare upgrade to ElasticSearch 5.6

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#341]
The store.yml  `type: multi_field` isn't supported anymore in EL 5.X versions. It should be replaced by a`fields`. E.g.

```(yaml)
 funder:
            type: multi_field
            fields:
              funder: {type: string, include_in_all: true}
              exact: {type: string, analyzer: name}
```

to

```(yaml)
 funder:
            type: string
            include_in_all: true
            fields:
              exact: {type: string, analyzer: name}
```

5.6 also complains about: 

```
[Request] ** [http://localhost:9200]-[599] Header lines exceeds maximum number allowed of 64, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/vagrant/LibreCat/local/lib/perl5/Catmandu/Store/ElasticSearch.pm line 27
```

**Comment by vpeil** [comment]
do you know the line of code/query which produces this error?

**Comment by phochste** [comment]
@vpeil It shows when you do `./index.sh demo` on the first install

**Comment by vpeil** [comment]
meanwhile, Elasticsearch is on version 6.x

**Comment by vpeil** [comment]
see also #579

**Comment by datango** [comment]
Any news?

**Comment by phochste** [comment]
@datango added to the the required things solved when we move to a new major release. The plan is to continue for 2018 in the current ElasticSearch and suggest start next year a new LibreCat which allows breaking changes (e.g. new ElasticSearch).

**Comment by vpeil** [comment]
current progress: see #579 

this one outdated
