### ISSUE TITLE
Saving publication with full text url fails.

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#356]
If i save a publication with a full text url like http://ieeexplore.ieee.org/document/7459438/ the server returns a 500 error.

Log:
2017/11/30 08:41:51 INFO [1321] - LibreCat.App[46] : loading LibreCat::App::Permission::demo for demo
2017/11/30 08:41:51 INFO [1321] - LibreCat.App[67] : executing handler login for /librecat/record/update
2017/11/30 08:41:51 INFO [1321] - LibreCat.App.Helper.Helpers[283] : updating publication
2017/11/30 08:41:51 ERROR [1321] - LibreCat.App.Helper.Helpers[295] : 168 not a valid publication!
2017/11/30 08:41:51 ERROR [1321] - LibreCat.App.Helper.Helpers[296] : [
   "/main_file_link: Expected object - got array."

**Comment by vpeil** [comment]
Ah, yes, this is due to the new OA option for fulltext URLs.

@petrakohorst can you take care of it?
