### ISSUE TITLE
main_file_link is hard coded in the templates as a one item array (main_file_link.0)

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#358]
If main_file_link should be an array, there should also be support in the templates for multiple array values.

**Comment by petrakohorst** [comment]
It is configurable. In the forms.yml you can set "multiple: 1" for the field "main_file_link" (here https://github.com/LibreCat/LibreCat/blob/master/config/forms.yml#L238 ) and re-generate the forms.
For the core it is currently set to be "multiple: 0".

**Comment by phochste** [comment]
But as I understand only one main_file_link will be displayed in record.tt? If there is support for multiple main_file_link's , then they should end up in all displays?

**Comment by vpeil** [comment]
@petrakohorst I guess, the forms configuration option "multiple: 0|1" has effect on edit forms only, right?
Not on public views, like frontdoor.

**Comment by petrakohorst** [comment]
That is indeed true. Only the first link is shown on the frontdoor (record.tt). I never noticed that.

It is more of a design issue, though. I'll think of something.

**Comment by vpeil** [comment]
fixed by PR #360
