### ISSUE TITLE
Link to LibreCat Record

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#359]
Open an existing publication, scroll to the end of the page.
Try to type another existing title within input field "link to LibreCat Record". Nothing happens.
Expected behaviour: autocomplete list shows some results, choose one and determine relation.

**Comment by verheyenkoen** [comment]
Is this really a bug? Don't find any clues that this has ever worked?

**Comment by vpeil** [comment]
Well, at some point it has been working. The perl sources are missing for this functionality. Let me fix this first, then you can create an frontend-test.

**Comment by feldi88** [comment]
Can I use this feature (linking one record to another) at the moment in any way? Neither typing the title with auto-complete nor entering an ID directly seems to work. Do I have to use it differently or is it completely broken at the moment?

**Comment by vpeil** [comment]
Progress on this issue can be found on the branch `pr/issue_359`. It seems to be fixed there...
