### ISSUE TITLE
Implementing an if/elseif/else branch in fix file - how?

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#36]
I am working on a mapping Web of Science metadata file into LibreCat publication file. I have a field called PT (publication type), which might have four different values: "J" (journal), "B" (book), "S" (series) and "P" (patent). I'd like to translate them to some LibreCat values, but since I haven't found construction for elsif (I tried else if, elseif, elif etc.). What I finally came up was this:

```Perl
if any_match(PT,"^J$")
  set_field(_r.type, "journal_article")
else
  if any_match(PT,"^B$")
    set_field(_r.type, "book")
  else
    if any_match(PT,"^P$")
      set_field(_r.type, "patent")
    else
      if any_match(PT,"^S$")
        set_field(_r.type, "series")
      else
        copy_field('PT', '_r.type')
      end
    end
  end
end
```

Is there a construction like the following one?

```Perl
if any_match(PT,"^J$")
  set_field(_r.type, "journal_article")
elsif any_match(PT,"^B$")
  set_field(_r.type, "book")
elsif any_match(PT,"^P$")
  set_field(_r.type, "patent")
elsif any_match(PT,"^S$")
  set_field(_r.type, "series")
else
  copy_field('PT', '_r.type')
end
```

**Comment by nics** [comment]
Hi,

currently there is no elsif statement.

Regards,
Nicolas

**Comment by pkiraly** [comment]
Thanks! OK, I got it. Do you have a plan to implement that (or a switch statement)?

**Comment by vpeil** [comment]
@pkiraly you can use a lookup fix to solve this problem.

**Comment by pkiraly** [comment]
@vpeil Thanks! I'll check it.

**Comment by vpeil** [comment]
@pkiraly were you successful? Can we close this one?

**Comment by pkiraly** [comment]
It turned out, that there are multiple complex things in my use case, so I don't use fix language for this purpose. You can close the issue.
