### ISSUE TITLE
Adding/Removing of Department Affiliation fails

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#363]
Several errors appear while adding/removing of department affliations at different pages.

To reproduce the error: I logged in with einstein at http://demo.librecat.org and changed the role to User.

- At http://demo.librecat.org/librecat I cannot remove the affliation (Department of Physics -> Relativity Theory Group) by clicking on Settings and then the minus: `An internal error occured`
- At http://demo.librecat.org/ and at http://demo.librecat.org/person/1234 Both, adding and removing affiliation via +/- fails with a JavaScript error:
`Uncaught ReferenceError: add_field is not defined at HTMLDivElement.onclick (1234:118)`
`Uncaught ReferenceError: remove_field is not defined at HTMLDivElement.onclick (1234:119)`

**Comment by vpeil** [comment]
Here are some screenshots:
If 2 or more departments are set and removing one of these, everything works fine for me:
![bildschirmfoto vom 2018-01-11 10-26-58](https://user-images.githubusercontent.com/1382060/34818109-2a328ce0-f6ba-11e7-9728-1412b075a370.png)

Removing this one leads to the reported issue:
![bildschirmfoto vom 2018-01-11 10-29-26](https://user-images.githubusercontent.com/1382060/34818220-7c374a12-f6ba-11e7-89de-e76bfdc0aa24.png)

@feldi88 Do I understand it correctly?

For the moment there's a workaround: Set a second department and then remove the first one.

**Comment by feldi88** [comment]
Yes, that's correct for the first case with the internal server error. The second case (the JavaScript error) is independent of the number of affliations.
