### ISSUE TITLE
Adding a "Link and relation to external material" without setting the link type is possible.

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#366]
When adding a new related material, the default 'relation' is empty which can be submitted. This gives at least errors in the front-end (and probably we don't want related links without relation).

**Comment by vpeil** [comment]
Cannot confirm. In the current dev branch my default relation is "Confimatin letter".

Can you check again, please? Screenshot?

**Comment by phochste** [comment]
Ok ..I can't repeat this again
