### ISSUE TITLE
ORCID ID for external authors

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#368]

**Comment by vpeil** [comment]
I think solving this issue is an easy win. @petrakohorst can you have a look please. Seems to me a forms issue only as it requires to add a **visible** orcid field for authors

**Comment by petrakohorst** [comment]
I've been mulling this over in my head for quite a while now.

Technically it's an easy solution. The problem is the design. It just looks awful, no matter where I add this field to the form.

**Comment by vpeil** [comment]
Turned into a nice-to-have list: https://github.com/LibreCat/LibreCat/wiki/Nice-to-have
