### ISSUE TITLE
Provide Vagrantfile for dev environment

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#37]
Still have problems to get gearman running or to correctly install the perl module (some C errors appear).

Maybe it is more convenient to have a Vagrantfile in this repository, where everything works...

**Comment by vpeil** [comment]
@phochste here the error message (I think, from GearmanXS):
```
$ carton exec bin/librecat schemas
XS.c: loadable library and perl binaries are mismatched (got handshake key 0x7bc0000, needed 0x7cc0000)
```

**Comment by phochste** [comment]
Did you by any chance upgrade your Perl version or have more than one perl on the systemand have things mixed up? If've seen such message more often when working with plenv and switching versions (or compiling as the wrong user).

**Comment by vpeil** [comment]
Ok, starting with a fresh box (base image "centos/7") I tried to follow the instructions from the wiki.
https://github.com/LibreCat/LibreCat/wiki/Installation

Some problems still occur:
The gearman stuff can't be found in the repos (yum always replies with "not found"). The `mysql*` stuff should be `mariadb*`.

How do I add the correct repo, so gearman can be installed?

**Comment by vpeil** [comment]
It seems that gearman was orphaned. There's an active repository https://github.com/gearman/gearmand, but no rpm/deb builds...
Install from source? :tired_face:

**Comment by phochste** [comment]
Ack...for CentOS is it available in the main yum distro.

**Comment by nics** [comment]
Lot's of install troubles with gearman, it's hard to find to find an actively maintained task queue that has good perl support. Maybe it's time to take a second look at Mojolicious, which has a good job queue: http://mojolicious.org/perldoc/Minion. And streaming support. We could run it with the existing Dancer behind a single psgi app probably.

**Comment by vpeil** [comment]
@phochste No. I had centos 7 on my Vagrant box. gearman wasn't available for yum.

@nics Minion has the advantage of being a pure perl implementation. And yes, the should evaluate Mojolicious. Could be worth a switch

**Comment by phochste** [comment]
This is my install from source on a CentOS 6.8 system:

     # yum install gcc-c++ gperf uuid-devel libuuid libuuid-devel uuid boost-devel libevent libevent-devel
     # wget https://launchpad.net/gearmand/1.2/1.1.12/+download/gearmand-1.1.12.tar.gz
     # tar -zxvf gearmand-1.1.12.tar.gz
     # cd gearmand-1.1.12
     # ./configure --prefix /opt/gearman
     # make
     # make install

**Comment by vpeil** [comment]
will try this, thanks.

**Comment by vpeil** [comment]
Installation instructions are working now. thanks.

**Comment by vpeil** [comment]
I have a working `Vagrantfile` now. For some reason it is excluded from the repo via .gitingnore. Would it cause problems for someone if I add the Vagrantfile to this repo?
