### ISSUE TITLE
Download fails on crazy file names

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#380]
Check for example: http://demo.librecat.org/publication/58

I have definitely uploaded the file, and the access_level is ok. This error occured several times with different examples.

@phochste could that error be located in the FileStore (in this case "Simple" is used)

**Comment by vpeil** [comment]
Further investigation revealed that there are also some issues within the Permissions module. I will fix them first, and then see how this issue behaves.

**Comment by phochste** [comment]
Fixed this, the /download/ permissions code was broken a few commits in the past...

**Comment by vpeil** [comment]
cool.
