### ISSUE TITLE
Hierarchical Projects

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#383]
Large research projects (like CRC or EU projects) are normally organized hierarchically in different areas and sub projects. It would be very nice to represent this hierarchy also in the LibreCat systems. That would enable us to embed different publication lists at the different levels of the project structure.
Therefore, I would suggest a similar realization as with the departments: If a publication is added to one project, it is automatically shown in all projects in the hierarchy.

A workaround, we use at the moment, is the adding of different projects to a publication (the whole CRC, the project area and the concrete project). This has at least two disadvantages: On the one hand, the views get very confusing. Imagine, you have a publication with 3 authors, working in different projects (which all have a hierarchy of 3 levels), so the publication would have 9 projects. On the other hand, it is very difficult to convince all authors to always enter of all projects at all levels.

I know that there could huge implications at different points in the software. But since it works perfectly for departments, I cannot detect any structural reasons that this should not work for the projects, too.

**Comment by datango** [comment]
+1

**Comment by vpeil** [comment]
I am in favour of that feature. But I am not sure **who** could do this **when**?
