### ISSUE TITLE
updating 'Research Group' fails and leads to 'An internal error occured' page

### ISSUE THREAD

**Issue by ThriceGood** [LibreCat/LibreCat#384]
When updating a record to have  a research group, it fails and leads to a page only displaying 'An internal error occured'.

Looking in the 'app.log' file I find this:
```
LibreCat.App.Helper.Helpers[284] : updating publication
LibreCat.App.Helper.Helpers[296] : 12 not a valid publication!
LibreCat.App.Helper.Helpers[297] : [
   "/research_group/0/_id: Missing property."
]
```
It's failing validation for some reason.

I spotted this in my own set up but it can be reproduced in 'demo.librecat.org' by logging in as einstein and adding 'testgroup' as a research group to any record. When you save the record the failure occurs.

**Comment by vpeil** [comment]
Checking the form reveals this:

```
<input type="hidden" name="research_group.0.id" id="rg_idautocomplete_0" value="" />
```

But the validation expects `research_group.0._id`

**Comment by nicolasfranck** [comment]
@ThriceGood If you want to see more errors, you need to create this Dancer environment file:

```
$ cp environments/development.yml.default environments/development.yml
```
and set the option show_errors to 1.

**Comment by vpeil** [comment]
fixed by merge of PR #394

**Comment by vpeil** [comment]
?

**Comment by phochste** [comment]
@vpeil The internal system error is gone, the research group is correctly stored in the database, but I don't see it displayed when opening again the edit form

**Comment by vpeil** [comment]
ok, this will be another PR then
