### ISSUE TITLE
Users cannot remove single filters

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#386]
If I filter the publication list with several filters (based by cql parameters in the URL), they appear as list on the right side below "Filters and Terms" and the filtering is done correctly. For example use http://demo.librecat.org/publication?cql=pmid%3D1&cql=test

![image](https://user-images.githubusercontent.com/6943048/35748797-8c53fa48-084f-11e8-9b4e-5064dbf7bae9.png)

Each filter term has now its own "x". I would assume that clicking on the "x" next to "test" would only remove the filter on test. But it always removes **all** filters together.

This is quite annoying for a user, because she expects a different behaviour.

But it's even worse if you embed a filtered publication list on another page as iframe, for example to show only the publications for one research project on the project page. If a user (on this project page) now add her own additional filters (for example for the type or year) and afterwards want to remove it again, all filters (the project **and** the type or year) are removed together and the publication list on the project page has no filters at all and shows all publications of the complete database. So the user leaves the whole context, which is a quite bad ui experience.

Is this behavior intended, or is it a bug? And if it's not a bug, what's the reason for it? In any case I would suggest to change it to the expected behavior as described.

**Comment by vpeil** [comment]
I am sure this has been working in the past. Not sure, what went wrong

**Comment by feldi88** [comment]
There are some lines of code in https://github.com/LibreCat/LibreCat/blob/master/views/search_box.tt#L10 which construct individual deletion links, but they are never used as far as I can see.
