### ISSUE TITLE
Access level problem with files

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#387]
The Access Level for files is not completely working as expected:

- `Open Access` works as expected: I can download the file with or without a login.
- `Local Access` works the same way as the Open Access. Here, I would expect a different behaviour. Either, only users which are logged in, or only users in the same network (or both). For the demo server, I can access files with this access level without any login.
- `Closed Access:` I cannot download the file, it doesn't matter if I'm logged in or not (even not as admin). The text link is not clickable, and if I click on the file icon (on the right) I get an error message ("An internal error occured")
- `Request a copy`: If I click on the file icon, the same error as before. If I click on the request button, I can enter a message; but I cannot test it in detail with the demo server. Furthermore, the icon image file is missing here.

**Comment by phochste** [comment]
- `Open Access` ok
- `Local Access` probably the demo server as a very `ip_range` setting in the `catmandy.local.yml` configuration file
- `Closed Access` indeed there was a permission bug
- `Request Access` indeed a permission bug ...and the icon was deleted from the distribution

**Comment by phochste** [comment]
Still a bug in request copy ... checking it..
