### ISSUE TITLE
Output of exports is wrong

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#397]
Almost each page with publications contains an export menu with five different export formats. Each of them has a different link which renders the export in the chosen format. While the format of the output is correct, the content (i.e. the chosen publications) is wrong.

For example on the following filtered page: http://demo.librecat.org/publication?cql=fulltext%3D1&q=test exactly 1 publications is available. The export link (for example for bibtex) is also correct (it has the same parameters): http://demo.librecat.org/export?cql=fulltext%3D1&fmt=bibtex&q=test But the output of this url and the given bibex file contains different publications compared to the rendered web view (in this example case there are 3 publications instead of only 1).

Playing around with different filters, I always get a different output of the exports then expected. But I couldn't yet find any systematic error behind it.

The error appears at all export formats with the same publications in the output.

**Comment by phochste** [comment]
I can confirm it on the demo server but can't repeat this behavior on the `dev` branch here locally. @vpeil  any ideas? The index on server is borked?

**Comment by vpeil** [comment]
@phochste wil check that, currently I am in Vienna..

**Comment by vpeil** [comment]
I found the bug!
The route `/export` has to add another cql-parameter: **status=public**. I will prepare a PR for this.

**Comment by vpeil** [comment]
The problem now is that the route `/export` is used in the public view (where we need "status=public") and additionally within the login area where one can have private records to be exported as well.

This ticket is related to #294 .

IMO we should have a separate export route for the login area.

**Comment by datango** [comment]
Also exporting all marked publications (RTF) results in a complete List of publications:
2 selected
10 public publications
Result: 16 publications 
Json,BibTex, RIS and Yaml exports work correctly (2 results)

**Comment by vpeil** [comment]
all of the mentioned issue has been solved by PR #481
