### ISSUE TITLE
Thumbnail access and privacy issues

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#4]
The thumbnail implementation needs to be improved:
- In Ghent we have a use case where thumbnails for closed access material should be hidden (the front page of an article can contain sensitive material)
- Thumbnails are now generated on an record level. This should maybe be done on a ~article~ document level?
- Thumbnails should maybe written in a FileStore separate from the fulltext content (faster access, easier to regenerate)
- Add command line tools to easy regenerate thumbnails

**Comment by vpeil** [comment]
:+1:  for separate thumbnail FileStore
