### ISSUE TITLE
Can't delete in the webinterface the first author

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#408]
E.g. got to : http://demo.librecat.org/librecat/record/edit/2737388

Try to delete `Marylin Monroe` . The fields stays visible and the record can't be saved due to missing mandatory fields.

**Comment by phochste** [comment]
All the repeated fields have the same issue where the first item can be removed (and will be reset to an empty value). I'm not sure now if this is a bug or an intended feature. It is for me confusing that a workaround would be required to remove the first item (move it first to another position and then delete it).

**Comment by petrakohorst** [comment]
I have a fix for this, I'll make a PR.
