### ISSUE TITLE
Closed Access files forbidden for everyone

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#411]
If I add a file with "Closed Access" to a publication it is not accessible by anyone, not even the author of the publication or the creator of the publictation entry.

See for example the publication 71 in the demo system (http://demo.librecat.org/publication/71) It was created by the einstein user and he is the only author. I has a file attached with access level "Closed Access", but the user "einstein" is not allowed to access it. The download link is not clickable and the thumbnail redirects to a 403 error page.

**Comment by datango** [comment]
Also Reviewers (and admins) have no access to files with access level Author/Reviewer.

**Comment by feldi88** [comment]
Completly solved with #423
