### ISSUE TITLE
Non-transparent Main Navigation

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#415]
For me and also for several further users which are not so deep in the system, the main navigation is non-tansparent if you are logged in. First of all the public navigation (if you are logged out) is fine, there is only the logo and the Home button which both redirect to the same home view.

But if you are logged in, it starts getting confusing. First of all the Home button now redirects to a new route (/librecat) and the public home page is only accessible through the logo. Additionally, you now have the /librecat (via Home) and the /person/ (via My Publication list) route which looks identical in the first step, but one is a frontend and one is a backend view.

One suggestion to make everything more clear and less confusing (perhaps not the perfect solution, but at least a first idea/try):

- Logo (-> http://demo.librecat.org/)
- Home (-> http://demo.librecat.org/) (reason for this identical target: make it consistent with the frontend view)
- My Publication List (-> http://demo.librecat.org/person/1234) (reason for the reordering: First the frontend views (home and publication list), then the backend views)
- Backend (->http://demo.librecat.org/librecat?) (perhaps a better, not so technical name instead of Backend)
- Admin (as before)

Additionally, I would like to have some headline at the /librecat page that clearly states that you are on the backend/editing view (in contrast to the publication list). And a nice-to-have would be a change of the role directly on this page.

In general it would be nice, if the current view is highlighted in the main menu.

What do you think about these suggestions? If you agree, I'm also happy to (start) implement them.

**Comment by feldi88** [comment]
A small mockup how it could look like to support my description: 
![image](https://user-images.githubusercontent.com/6943048/37984774-7ece9546-31f7-11e8-9f54-83cbaaf75c41.png)

**Comment by feldi-online** [comment]
@phochste @vpeil What do you think about the suggestion (perhaps with the name "Dashboard" instead of "Backend" to address non-technical users)?

We have more and more users which are confused about the navigation, especially because the same navigation link (Home) navigates to different views (see my argumentation in this issue).

If you give a positive feedback here, I would be happy to make a pull request (which really would only change the navigation menu and no view and features).

**Comment by vpeil** [comment]
Sorry for leaving this issue uncommented.

IMO we can do this!

**Dashboard** might be a good solution. Then we don't need the home button, right?

**Comment by feldi-online** [comment]
I created two pull request:

- #510  has the discussed dashboard link on the topbar
- #511 allows the change of role on the dashboard page (since it is very hidden in the settings menu)

**Comment by petrakohorst** [comment]
The dashboard link is a good idea and I also like the highlighting of the current location in the topbar! Much less confusing.

Isn't the link behind the LibreCat logo superfluous then? Because the home link always leads to the "homepage"?

**Comment by petrakohorst** [comment]
As for the second pull request:

LibreCat is designed to have backend (dashboard) and frontend (personal page) look alike as much as possible so that the user gets a very good idea about what his or her personal publication page will look like in public. That is why we have eliminated as many "backend visuals" from that page as possible.

If you need to feature the role change option more prominently for your users, you can do this in the local layer. In fact, in the local layer you can fully modify that page to your needs, add the "Dashboard" label to the heading and make other design changes so that the page fits the needs of your users best.

**Comment by feldi-online** [comment]
> Isn't the link behind the LibreCat logo superfluous then? Because the home link always leads to the "homepage"?

It's best practice in web design to have the logo as well as the written home link forwarded to the same home page (The default user exepcts this behavior). Therefore, I would leave it superfluous.

According to the second PR: Since there are different publications visible on the backend and frontend page (e.g. publications I have added, but which are not authored by me, appear only on the backend page), I (and also other users I have talked to) find it very confusing that both pages look so similar, but contain different information. I would even vote for more differences. But that's my personal opinion.

**Comment by phochste** [comment]
About the second PR. I agree that there can be a confusion what "My Dashboard" contains, but do agree that the "Switch role" button has the intent to view the website exactly like a not privileged user would do. 

I prefer that library admins for now are instructed to find the "Switch role" button in the "Settings" menu.
