### ISSUE TITLE
Question: is there a way to list/display departments

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#42]
I have just a question: in the data schema there is a department entity. Where it is displayed? I am working on importing the department list and connecting IDs to researchers, but I don't see where departmental info is displayed - other than in the list of authors?

**Comment by phochste** [comment]
Other then via command line:

    $  bin/librecat  department list

there is no webinterface. But would be a feature we in Ghent probably would want. We have one now in the older version of SBCat: https://biblio.ugent.be/organization

**Comment by vpeil** [comment]
If you are logged in with role super_admin, then you should see a department filter (if you have departments added).

**Comment by phochste** [comment]
Same question for Projects. There should on the homepage a new tab 'Organizations' and 'Projects' just like the Authors tab that displays all departments/projects and publications for them

**Comment by vpeil** [comment]
Projects tab appears on homepage now. 
Soon to come: Organizations/Departments

**Comment by vpeil** [comment]
department now are displayed now on dev branch!
