### ISSUE TITLE
JavaScript embed produces invalid JavaScript

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#420]
The JavaScript embedding option produces invalid JavaScript. It contains the citation data in a `document.write`, but with an invalid line break. For example, the following is produced:

```
<!-- BEGIN embed/javascript.tt -->
document.write ('<ul>') ;
document.write('<li>');
document.write('Krijger, Stefanie, <em>Listening challenges for children with cochlear implants in mainstream education</em>. Royal Belgian Society for Ear, Nose, Throat, Head and Neck Surgery, Spring meeting, Abstracts <strong></strong> (). , 2016<br />test
');
document.write('</li>');
```

The linebreak between the fourth and fifth line is invalid, so the HTML will not be rendered in most browsers.

The problem is probably the template `INCLUDE ` in https://github.com/LibreCat/LibreCat/blob/2a54792d2c06a27874fc3b212fd3f87ab78a2f84/views/embed/javascript.tt#L14 and https://github.com/LibreCat/LibreCat/blob/2a54792d2c06a27874fc3b212fd3f87ab78a2f84/views/embed/javascript.tt#L16 which produces and extra linebreak in the output.

**Comment by vpeil** [comment]
solved with PR #421
