### ISSUE TITLE
Search for departments, projects, etc. by name

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#427]
In the current implementation/configuration, you can search for some properties by their names, and for others only by their id. For example, you can search for `person="Einstein, Albert"` or `person=1234`, but only for `department=9998` and not something like `department="Department of Mathematics -> Analysis Group"`.

The reason for this behaviour is in the configuration of the elasticsearch cql_mapping:

See
https://github.com/LibreCat/LibreCat/blob/92e7eac8a1fc2fda558524d6bfc1068bdf2d4b99/config/store.yml#L477-L484

and 

https://github.com/LibreCat/LibreCat/blob/92e7eac8a1fc2fda558524d6bfc1068bdf2d4b99/config/store.yml#L493-L503

or 

https://github.com/LibreCat/LibreCat/blob/92e7eac8a1fc2fda558524d6bfc1068bdf2d4b99/config/store.yml#L280-L287

as examples.

For a user (and especially a non-technical affine user) it is very difficult or even impossible to use this search, since she has to do the mapping from department/project name to the corresponding id on her own. Additionally, if you embed or link some search result with department/project it is not really comprehensible why for example an department=9998 is used there.

From my point of view, it is very easy to improve by including also names, etc. in the corresponding cql_mapping. Or are there any reasons for not extending it which I am not aware of?

Let me know what you are thinking about it. If you agree with me, I'm happy to provide a pull request for this.

**Comment by vpeil** [comment]
IMO there's no special reason. I think this could be added without danger. @phochste (release manager) what do you think? 

In the past we used IDs for embeddings....

**Comment by vpeil** [comment]
@ALL no reaction on this one for exactly 5 months.

**Comment by phochste** [comment]
I don't see a special reason why this is the case. In the current webinterface I don't find places where something else than searching departments by ID is required. Power users might want to do more (or less). If there is a local use case, why not?
