### ISSUE TITLE
Facet arbitrary not displayed if there are less than 2 different facet values

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#429]
I was trying to add a facet to the interface and found it very hard to get to work

See this code:

https://github.com/LibreCat/LibreCat/blob/master/views/facets.tt#L23

I know it can be configured but this seems to be quite an adhoc choice.

Also the code in this line is not clear:

https://github.com/LibreCat/LibreCat/blob/master/views/facets.tt#L27

**Comment by vpeil** [comment]
Introduced by this commit: https://github.com/LibreCat/LibreCat/commit/f392e50c8c83544657282d8546ba0a85d7c06548
Maybe this helps (or maybe @nics remembers the intention behind it)

**Comment by petrakohorst** [comment]
If a facet has only one value (e.g. open_access=1, popular_science=1), set "min:1" for the facet: https://github.com/LibreCat/LibreCat/blob/master/config/features.yml#L14

For example the popular_science facet is currently not displayed (two lines above the referenced line). But if you set "min: 1" for it, it is displayed.

This doesn not answer to the complexity of setting up facets, but it fixes the problem mentioned in the issue's title.
