### ISSUE TITLE
Single Sign On: howto

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#43]
There is now a new branch "feature_sso", with support
for CAS authentication. It works in the following way:
(See LibreCat::Auth::SSO)

There are two controllers:

* one controller that handles all **authentication** with the external login service (CAS, ORCID). This is always a Plack Application. When done, it registers a session key called "auth_sso", that look like this:

```
{
   "type" => "CAS",
   "response" => "<xml response of cas ..>"
}
```

and redirects to the authorization controller.

Example: LibreCat::Auth::SSO::CAS

* one controller that uses the information in "auth_sso" to create a user session. 
    This is called the **authorization** controller. This can be either a Plack app or a dancer route.
   This is typically done by application code. This controller must have access to the
    same session information as the authentication controller.

Control flow (example):

* go to "/auth/cas" ( just an example )
* LibreCat::Auth::SSO::CAS is mounted on "/auth/cas", and checks if the session_key "auth_sso" is present.
   * not present: redirects to CAS, but adds its own url as the service
                         cas returns to this controller with a ticket, and it validates the received ticket
                         and creates "auth_sso" that contains the ticket.
                         redirects to authorization controller "/auth/cas/callback".
   * present: redirects to the authorization_url "/auth/cas/callback"

* authorization controller "/auth/cas/callback":

   * checks if session key "auth_sso" exists:
     * true: create user session
     * false: access denied

This flow is inspired by omniauth.

Does this suit your needs?

P.S. this branch has been created a long time ago, so it probably cannot be merged automatically..

**Comment by vpeil** [comment]
thanks for clarification and the reminder. I just merged the branches `feature_sso` and `feature_sso_orcid` into dev.

The workflow makes sense to me, although we don't have any SSO in production. But this will be a topic soon, I'm sure.

Thanks again for this great progress.

**Comment by vpeil** [comment]
btw: and I have deleted the branches

**Comment by nicolasfranck** [comment]
Thanks! I have also submitted pull request for ORCID as this relayed still on my computer.
