### ISSUE TITLE
Inconsistency between search with q and cql parameter

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#431]
There is always a bit of confusion about the difference between the cql and the q parameter for search.

For example, if you have a dissertation with Albert Einstein as supervisor (http://demo.librecat.org/publication/80).

- If you use the "normal" search with the search field resulting in the q parameter, this dissertation is found: http://demo.librecat.org/publication?q=person%3D%22Einstein,%20Albert%22
- If you use the cql search by using a filter or embedding it on a page which results in the cql parameter it is not found: http://demo.librecat.org/publication?cql=person%3D%22Einstein,%20Albert%22

So the q search covers more fields than the cql search for person.

Furthermore, the cql search requires the exact name. In this example only person="Lastname, Firstname". In contrast the q search is more flexible and allows person="Lastname, Firstname" and person="Albert Einstein":

- cql
  -- working: http://demo.librecat.org/publication?cql=person%3D%22Einstein,%20Albert%22
  -- not working: http://demo.librecat.org/publication?cql=person%3D%22Albert+Einstein%22
- q:
  -- working: http://demo.librecat.org/publication?q=person%3D%22Einstein,%20Albert%22
  -- working: http://demo.librecat.org/publication?q=person%3D%22Albert+Einstein%22

This inconsistency creates a lot of confusion in the usage. Is there any reason for this? Furthermore, how does the q search works in general (for the cql search it is defined by the cql mapping in store.yml, but for the q search?).

**Comment by vpeil** [comment]
As I understand from the code, `cql` as for for CQL (https://www.loc.gov/standards/sru/cql/spec.html), and the parameter `q` is for free text search. I am not sure, why the last to example work, as there's no CQL-Mapping involved when using `q`.
