### ISSUE TITLE
Link to user's homepage

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#439]
There is no possibility to add a link to a user's homepage (for example her university homepage), only external accounts like arxiv, orcid, ... Especially in the context of academia I think this is a must have feature.

I see two different ways to handle this issue:

1. Adding an additional authorId which allows full urls. It can be managed by the user herself like the other links.
2. Adding the homepage to the account profile like her mail adress. It can be shown on the person page (like the mail), but it is only managed by the admin (or automatically through some synchronisation with external database).

I do not have any preference for one of the solutions, but I think one of them is required.

**Comment by vpeil** [comment]
This can be done in a layer:

Set in `config/lists.yml`:

```yaml
author_ids:
  ...
  homepage:
    label: Homepage
```

and in `config/schemas.yml` in the section `user.properties`:

```yaml
homepage:
  type: string
```

@phochste should we include this in the core application?

**Comment by vpeil** [comment]
No reaction, so can close this one. Reopen if there's more to it.
