### ISSUE TITLE
Export uses hits per page limit

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#450]
If you export a list of (filtered) publications from http://demo.librecat.org/publication the export (e.g. http://demo.librecat.org/export?fmt=bibtex) only contains 20 publications (or to be more concrete it always uses the hits per page parameter).

In my opinion, it does not make any sense to have a limit here. For the rendering output, it is useful, but for expert the user exepcts all publications to be exported (so the number of items in the export should be equal to the numer of publications in the headline).

**Comment by vpeil** [comment]
Your suggestion would imply that one could trigger a download of hundred thousand records. That would open a nice door for DOS attacks (as pointed out by @nicolasfranck in issue #294 )
