### ISSUE TITLE
User account is deleted from the /authors pages when updating a user record

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#452]
Steps:

- Go to http://localhost:5001/person?browse=P
- Check Nathalie Portman is there
- Update in the Admin > Manage Accounts something in the Portman record
- Go to http://localhost:5001/person?browse=P
- No Portman there

(need bin/librecat user update_stats to become available again)

**Comment by vpeil** [comment]
I think "publication_count" has to be added as an input hidden field

**Comment by phochste** [comment]
@vpeil  This `publication_count` isn't part of the main record only of the search record. 

The basic problem is that part of the logic is wrong. I see a lot of `update_record` used in the code which is IMO wrong and should be deleted. This doesn't validate the record and will write delete the publication counts or writes them into the main database also. 

I need to look at it deeper

**Comment by phochste** [comment]
I'll try to fix this to make special 'index_user.fix' fixes like 'update_publicaition.fix' that run before you index a record. The 'index_record' will automatically use these fixes. In this way we don't need anymore the special 'update_stats' command. User records will be updated in the index at edit time and reindexation time.

**Comment by vpeil** [comment]
I think this has been fixed by commit ebe80ad.
