### ISSUE TITLE
Supervisor not considered in person mapping

### ISSUE THREAD

**Issue by feldi88** [LibreCat/LibreCat#456]
The person meta field of a publication considers author, editor and translator and not the supervisor field. This choice definitely has its good reason, I personally do not have an opinion, if supervisor should be considered here or not.

The "problem" appears if you have a publication (e.g. a dissertation) with an internal supervisor, e.g. http://demo.librecat.org/publication/83 If you now click on the linked supervisor name in the details view, you reach the person page with her publications (http://demo.librecat.org/person/3), but the publication from which you reached the page is not visible. This behaviour is not traceable by a user.

I see two solutions for this problem:

1. include supervisor also in the person mapping 
1. link the supervisor field not to the person page, but to http://demo.librecat.org/publication?cql=supervisor=3

I have no preferred solution, but I think that one of both has to be implemented.

**Comment by vpeil** [comment]
The person field is used and intended for all publications of a person. This would not include supedvised theses. Therefore, I would prefer solution no. 2.

**Comment by feldi88** [comment]
Another small extension to solution 2 would be the search for all publications as supervisor and as author, e.g. http://demo.librecat.org/publication?cql=(supervisor=3%20OR%20person=3)
