### ISSUE TITLE
Error during publications import - External Id - Expected array - got string

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#459]
1) Exporting all publications
 carton exec bin/librecat publication export > publications.yaml
2) Importing all publications
 carton exec bin/librecat publication add publications.yaml
.. in order to update citation styles.

Error: 
ERROR: not a valid publication
/external_id/pmid: Expected array - got string.
/external_id/isi: Expected array - got string.

Data in yaml-File:
external_id:
  isi: '000356223900015'
  pmid: '25740929'

**Comment by vpeil** [comment]
I think you missed the release notes of version 0.7.0 (in july 2017): https://github.com/LibreCat/LibreCat/releases/tag/0.7.0
