### ISSUE TITLE
Commonmarkjs and Mathjax installation

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#46]
There is in LibreCat a dependency in the templates on CommonMark and MathJax but this is not included in the github, nor part of the install documentation. Is there any preferred version to install or a preferred installation routine? Are there other Javascript dependencies not included in the when cloning the LibreCat git and need extra installation steps?

**Comment by vpeil** [comment]
I think these two are the only missing. No preferred version.
I would like to declare all external js-libraries as dependencies rather then inluding them in this git-repo.
What about a `package.json` + `Gruntfile.js`. Installation would be than as easy as (in theory, never done this before :smile: )

```
$ npm install
$ grunt {do-some-job}
```

Maybe @nilswindisch can give some advise or explain best practices.

**Comment by phochste** [comment]
Before we do into that I can just add some lines to the documentation where to grab the sources and where to drop them in the installation.

**Comment by nilswindisch** [comment]
sry for my belated answer ... vacation and stuff.

My current approach is to define dependencies in package.json - not using grunt or gulp or even bower though, it's all done via npm as see in https://github.com/subugoe/LibreCat/blob/dev/package.json

The question would be if dependencies are available via npm and in the case of MathJax and CommonMark they are.
https://www.npmjs.com/package/commonmark
https://www.npmjs.com/package/mathjax

You may take a look at https://github.com/subugoe/LibreCat/blob/dev/package.json for other dependencies I set already.

Maybe we can discuss this further when we meet in a few days and you can tell me if my approach is feasible for you.

**Comment by njahn82** [comment]
Wonder, if mathjax will be supported. Would be great because we have some records with latex formulas in the title

**Comment by njahn82** [comment]
sorry, wrong place to ask
