### ISSUE TITLE
The target record of related_material links gets too many related_material entries

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#467]
When in a source record I add a related_material to a target, then both the source and target record get one entry in related_material (ok)

When I change in the source record the related_material type (e.g. from Part to  Earlier version) then in the target record another related_material entry will be added (not ok). For every edit in the related_material link in the source record, the target record will get more related material links (not ok)

I would guess the expected behaviour is that the target record will get an updated related_material entry, and not a new entry for every change.

**Comment by vpeil** [comment]
oh, I guess that one is on me :(

**Comment by vpeil** [comment]
@phochste commit 0d431e4 says that this issue is fixed. Is that right?
