### ISSUE TITLE
Delegate function is not working

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#475]
The delegate function is not working correctly. To be more concrete the permission check for delegates' edit rights cannot work correctly:

https://github.com/LibreCat/LibreCat/blob/317480b0fbc5d61d2ada791c4599133bac44feeb/lib/LibreCat/App/Catalogue/Controller/Permission.pm#L114-L126

`@{$user->{delegate}` contains a list of usernames, `@person_ids` contains a list of user ids. Therefore, the equality check can never result in true and therefore a delegate never get edit rights. (In praxis, a delegate user has often the correct rights, because she is also the creator of a publication).

I would suggest to store a list of user ids in the delegate array instead of the list of usernames, but you have to decide how to handle this issue.

**Comment by vpeil** [comment]
Not confimed.

`@{$user->{delegate} ` contains user_ids and so does @person_ids

https://github.com/LibreCat/LibreCat/blob/317480b0fbc5d61d2ada791c4599133bac44feeb/lib/LibreCat/App/Catalogue/Controller/Permission.pm#L52-L62

And for me the UI works as expected.

**Comment by feldi88** [comment]
I debuged into `@{$user->{delegate}` and it definitely contains usernames

The feature works as expected for publications which the delegator created herself, but not for existing ones.

Can you please login in the demo server with delegate/delegate (a new user which is a delegate of einstein) and try to edit an existing publication of einstein, for example the publication with ID 62? You should have the editing rights (as far as I understand the delegation feature), but you get an access denied.

**Comment by vpeil** [comment]
Ok: the problem is that one can add both, id or username, into the delegate field (which is bad). On my Testserver I had IDs, so I couldn't reproduce the error. This has to be changed (either way), and then adapted in Permission.pm

**Comment by feldi88** [comment]
Ok, I see. But then I would suggest to only allow IDs in the delegate array. So that you do not have to consider this inconsistency at different locations in the code (and then the Permission.pm does not have to be adapted).
