### ISSUE TITLE
Update citeproc-node dependency

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#486]
The used citeproc-node dependency is outdated. The wiki (https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language) references the repository https://github.com/citeac/citeproc-node and the corresponding docker image https://hub.docker.com/r/citeac/citeproc-node/ This fork is no longer maintained, see https://github.com/citeac/citeproc-node/issues/1#issuecomment-388549304

Instead the original repository should be used which can be found at https://github.com/zotero/citeproc-node Sadly, there is no Dockerfile included and therefore no docker image in the registry which is ready to use. Additionally, here we also have a fork (https://github.com/LibreCat/citeproc-node) which has a Dockerfile and image (https://hub.docker.com/r/librecat/citeproc-node/). This is already used by travis, but the fork is quite outdated (which is not important for the tests, but for the daily use).

In the last months there are lots of extensions to the csl repositories, including lots of bug fixes (also one to the default short citation style used by LibreCat), so that a more recent version of the server makes much sense and is really required from my point of view. I see two different ways to handle this issue:

1. Providing a pull request with a Docker file to the zotero repository and ask them to maintain a Docker image. Afterwards, we can completely depended on their work.
1. Updating our fork with the recent updates and maintain our own docker image. This mean maintenance work in our fork from time to time, but we do not depend on the zotero team.

You should decide on one of the possibilities (or a third one which I do not have in mind right now), but a more recent version of the server would be very nice (and of course, including updates in the wiki after the decision). If you need any help, just let me know .Thanks!

**Comment by vpeil** [comment]
As a quick solution I have updated the Librecat/citeproc-node repository.

And I have updated the documentation: https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language

**Comment by vpeil** [comment]
I think I have messed something up: As of today I have updated the sources (https://github.com/LibreCat/citeproc-node), which includes a new docker image (https://hub.docker.com/r/librecat/citeproc-node/).

Finally, I opened an issue at the official repo: https://github.com/zotero/citeproc-node/issues/33

That's it.
