### ISSUE TITLE
Possible feature for generating publication coversheets

### ISSUE THREAD

**Issue by ThriceGood** [LibreCat/LibreCat#488]
I want to open a discussion about a possible new feature. It was mentioned in an email discussion that it might be a feature that would be desired in the LibreCat core.

At IST Austria we have a publication type called 'Technical Report' which require coversheet to be generated for them. It is required that a coversheet is generated from a template and prepended to the original PDF document. Currently this is handled in our Eprints repository by a plugin called Coversheets.

https://wiki.eprints.org/w/Coversheets

After you upload the document you navigate to the plugin section and have the option to choose a template to add as a coversheet to the document. 

It was mentioned that a better solution, and I agree on this, is to override the original download link to generate the coversheet on the fly when you want to download the document with a coversheet.

I think the general idea would be to have a HTML template be filled in with values by template toolkit, then converted to PDF and prepended to the original. Our coversheets are basically just information from the publication such as title, authors, dates, etc on a nice IST Austria background.

Template Toolkit can handle the templating.
[PDF::WebKit](http://search.cpan.org/~philip/PDF-WebKit/lib/PDF/WebKit.pm) could do the html->pdf conversion. 
[CAM::PDF](http://search.cpan.org/~cdolan/CAM-PDF-1.60/lib/CAM/PDF.pm) could prepend the pdf coversheet to the existing document.

What are your opinions on this idea? Could it be something welcome to the LibreCat core?

**Comment by vpeil** [comment]
Turned into a nice to have list: https://github.com/LibreCat/LibreCat/wiki/Nice-to-have
