### ISSUE TITLE
Uploaded file with restriction to author/reviewer causes internal error on record overview page

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#492]
I made an update test from 1.1.3 to 1.2.0. Then i started to add a file with restriction to only allow authos/reviewers to access this file. Now when i visit https://hostname.de/record to list all public accesable publications i get "An internal error occured".

In the Log-File:
[2184] error @0.127742> [hit #18]request to GET /record crashed: core - template - undef error - Testdoc1.pdf at /var/librecat/LibreCat/views/links.tt line 18.
 at /var/librecat/LibreCat/local/lib/perl5/Dancer/Template/Abstract.pm line 91. in /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm l. 98

If a user is logged in it works. This user has not privileges to the publication or file.

**Comment by phochste** [comment]
Confirmed.

A patch is available in `LibreCat::App::Catalogue::Controller::Permission::Permissions` line 238
write

```
    return ($can_edit ? 1  : 0, $file_name);
```
