### ISSUE TITLE
Export: Bibtex type for working papers and reports

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#495]
If you export publications as bitex and they have the LibreCat publication type "report" or "working paper", they are given the bibtex type "misc". Since there are also other types available like "techreport" or "unpublished", we should think about using a more fitting type instead of always using the misc type.

What do you think about this issue?

**Comment by vpeil** [comment]
Data mapping improvements are welcome!.

In that special case type mappings are located [here](https://github.com/LibreCat/LibreCat/blob/master/fixes/lookup/bibtex_types.csv)

**Comment by feldi-online** [comment]
Thanks for the hint, I've added a few mappings in #498
