### ISSUE TITLE
Mass Edit

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#497]
I know it would not be easy to design and implement this, but I think at some time it will be required. Therefore, I already write it down here to start the discussion.

There are many use cases as an admin/reviewer or even as an user in which you want to have any kind of mass edit feature. Sample scenarios are for example if someone changes her department, joins a new project, is a new user and imports all her data or simple has some self-caused errors in her data. But that's only a few, I think there are many more.

In each of these cases I do not want to open hundreds of publications separately and edit exact the same properties with exact the same value. Instead of that I only want to select all relevant publications and then have one edit step for all of them.

At the moment I am not sure how to handle this even conceptually as best solution, I only propose here one way (which is definitely not the best one):

1. You can select the relevant publications with the already available filter options in the /librecat route.
1. There is a new button "Mass Edit" which opens a new edit form.
1. In this form you can select the properties to change (e.g. with checkboxes or select boxes) and enter the new value(s).
1. After save, all previously chosen publications will be updated.

In the proposed way there are lots of open questions, for example:
-  How to handle existing values, overwriting everything, skipping them, ...
- What's about lists of entries (e.g. projects and departments): add the new ones only, or overwrite everything?
- How is the user interface managed? Can I see the old data?
- ...

What do you think about this feature in general? Do you also see the same importance?  And do you have perhaps better and/or easier ways to implement it?

**Comment by vpeil** [comment]
Not going into detail, but mass edits are posisble via our CLI (which is available for the system administrator only). I am not sure, if we would like to give people (users) that much power in our system. Maybe, it is easier to let them create an issue...

**Comment by feldi-online** [comment]
Yes, I know about the CLI. But, as you mentioned, it is only usable by system administrators. Given a system with thousands of users and very huge projects with hundereds of publications, it will not be practical to let the system administrator do all bigger chances. In my opinion, at least project reviewers or department reviewers should have some tools to manage multiple publications at once.

**Comment by nics** [comment]
I second the need for a mass edit tool. I made a cli version of this for the old sbcat system, that had the operations change, append, delete. A split pane interface that shows a preview of the effect of the changes would be nice.

**Comment by vpeil** [comment]
Moved to https://github.com/LibreCat/LibreCat/wiki/Nice-to-have
