### ISSUE TITLE
Umlauts from BibTeX are not resolved

### ISSUE THREAD

**Issue by abirke** [LibreCat/LibreCat#499]
When adding new publications using a BibTeX entry (as for example the one below), umlauts like {\"a}, {\"o}, etc. break the imported fields.

from http://dblp.uni-trier.de/rec/bibtex/journals/joc/JagerKSS17
```
@article{DBLP:journals/joc/JagerKSS17,
  author    = {Tibor Jager and
               Florian Kohlar and
               Sven Sch{\"{a}}ge and
               J{\"{o}}rg Schwenk},
  title     = {Authenticated Confidential Channel Establishment and the Security
               of {TLS-DHE}},
  journal   = {J. Cryptology},
  volume    = {30},
  number    = {4},
  pages     = {1276--1324},
  year      = {2017},
  url       = {https://doi.org/10.1007/s00145-016-9248-2},
  doi       = {10.1007/s00145-016-9248-2},
  timestamp = {Fri, 22 Sep 2017 16:30:11 +0200},
  biburl    = {https://dblp.org/rec/bib/journals/joc/JagerKSS17},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}

```

![image](https://user-images.githubusercontent.com/29310187/41094212-c8909772-6a4d-11e8-81f8-f5708db36755.png)

**Comment by vpeil** [comment]
@all any ideas how to solve this?

**Comment by abirke** [comment]
To be honest, this is a bit of a stab in the dark, but it seems like this would be rather specific to bibtex and german umlauts, so maybe they could be replaced in [fixes/bibtex_mapping.fix.](https://github.com/LibreCat/LibreCat/blob/master/fixes/bibtex_mapping.fix). Curly brackets around capital letters in the title are also removed here. Of course, if there is a more generic solution, it might be preferable.

**Comment by vpeil** [comment]
The module https://metacpan.org/pod/LaTeX::Decode could be used here.
