### ISSUE TITLE
Autocompletion does not match across dash

### ISSUE THREAD

**Issue by abirke** [LibreCat/LibreCat#502]
The department autocompletion in the record/edit view does not seem to find results with a dash (or also other special characters?). For example, the suggestion _IT-Sicherheit_ is only found until _IT_ is typed, but not after having typed the dash.

![image](https://user-images.githubusercontent.com/29310187/41155591-f5298d3a-6b1e-11e8-8626-97dd6dbf4f0f.png)

When continuing to write the suggestions disappear, even when typing the exact match.

![image](https://user-images.githubusercontent.com/29310187/41155618-0d6aa30c-6b1f-11e8-9cce-1065efd13962.png)

**Comment by vpeil** [comment]
@petrakohorst I think you did some work on this (or something similar?), right?
