### ISSUE TITLE
User management + password shouldnt be displayed

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#509]
- When creating a new user account the password field is clearly visibile as free text. The contents of this fields should be a "password" type HTML field
- The form should double check if the password is filled out correctly (e.g. like let admin type in password twice)
- The form allows to add double records with the same login name (which should not be possible)

**Comment by phochste** [comment]
There should be two routes ...the value of the password shouldn't be inspected

**Comment by vpeil** [comment]
There are 2 routes

* GET /librecat/admin/account/new
* POST /librecat/admin/account/update

I agree, that the password shouldn't be inspected.

**Comment by nicolasfranck** [comment]
I meant: two routes for the updates

* POST /librecat/admin/account for a new user
   password is required
   password is encrypted
* PUT /librecat/admin/account/:id for an existing user (PUT can be tunneled through POST)
   password is not required. 
   when given, use as is, an encrypt it.

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/526

**Comment by vpeil** [comment]
PR #526 has been merged into dev.
