### ISSUE TITLE
Random bug in own publication list

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#518]
There is a very strange bug in the own publication list which I cannot reproduce on my own system (to have a look into the log), but only on productive or the demo server.

As far as I could find out it happens if you have a publication with yourself as author and an additional non-librecat author. If you then go to your own publication list and search for something (I am not sure for what), an internal error occurs. As already said I was not able to reproduce it locally, therefore this steps are not the whole truth. But at the moment at the demo server, there is a publication (ID 62) which produces this error. You reach the failing page directly with: http://demo.librecat.org/person/1234?q=Test&person=1234#

Perhaps someone with access to the demo server logs could have a look at it.

**Comment by vpeil** [comment]
As far as I see, that bug does not exist on the dev-branch anymore. The Demo-Version has this problem as described. There was some strange use of `p.can_download` in `views/links.tt`. But this has been removed some weeks ago.
