### ISSUE TITLE
Validate ISBN/ISSN etc.

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#52]
use fixes from Catmandu::Identifier.

What we do in case on invalid values? Return the form with an error? Delete the field and save record to db?

**Comment by phochste** [comment]
If one sets too strict validations rules one shoots oneself in the foot. 

As a general rule.. ISBN/ISSN are free text fields ..if you don't allow mistakes (or noise) the application will be very hard to work with.

Some fields need to be very strict. This can be solved with selection lists, or in the Perl code itsef if they are fields generated by software and not by users (date_updated).
Some fields need to be as strict as possible, but allow some level of ..noise.

The JSON schema was written with these things in mind. Records valid against the JSON schema are valid as in "they don't break the application".. not as in "they are the perfect records".

We are dealing with a catalog here. The main task of a catalog is to make pretty data from ugly data.

**Comment by vpeil** [comment]
thanks for explaining.
