### ISSUE TITLE
Supervisor should be able to edit publications

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#520]
At the moment, users are not able to edit publications for which they are tagged as supervisors. In most scenarios this does not make much sense, since often an author of a thesis (especially if you consider bachelor or master theses written by students) is not even a LibreCat user, so nobody (only the creator) is able to edit such a publication afterwards. The supervisor is definitely the person who should be able to maintain it.

I will provide a pull request in a few minutes to enable this. Two changes are required:

- The supervisor of a publication has to have the permission to edit it.
- A publication with supervisor is visible on the backend view of the supervisor (like it is the case for the creator)

**Comment by phochste** [comment]
This ticket needs to be broader in  the scenarios. For my digital archiving project I also need more control (maybe configurable) who can view/edit publications. In some scenarios you want supervisors have these rights, in other scenarios not. In 

There was an attempt to add Configurable roles #137 to code base but this is stalled.  A "supervisor" specific solution is too local.

**Comment by phochste** [comment]
See `config/permissions.yml` in the `dev` branch to set who can see/do what.
