### ISSUE TITLE
External Identifiers in Links section of edit form

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#530]
The grouping of fields in the edit form is a little bit confusing, since the external identifiers are rendered in the "Additional Information" block, instead of in the "Links" block. I would prefer if they are put in the Links block because they are actually external links to other web services like the fulltext url or other external material. What do you think about this suggestion?

**Comment by vpeil** [comment]
Sorry, I do not understand. Please, can you attach a screenshot with a marker?

**Comment by feldi-online** [comment]
Yes, of course. The suggestion is to move the field to the last block (see screenshot):

![image](https://user-images.githubusercontent.com/6943048/42595091-68199168-8551-11e8-964a-db6eb32300af.png)

**Comment by petrakohorst** [comment]
I have made the necessary changes to the external_id template, so that you can now configure this field to be in the links section (but only this field).

For more details, see PR.
