### ISSUE TITLE
Research Data form - Add a contact address for download

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#54]
Data publications can point to the dataset by:
- Uploads in LibreCat
- Links to an external resource

We got a request to add a third option: the researcher can add contact details (email etc) to be displayed. "Please contact .... at <email> ... for access to this dataset"

**Comment by vpeil** [comment]
isnt't the already implemented `request-a-copy` functionality?

**Comment by phochste** [comment]
The `request-a-copy` in LibreCat is for datasets that are uploaded to the application which can be made available when a researcher allows this. What this ticket means is a functionality to do a `request-a-copy` without having to upload the dataset to the application. 

I know..this isn't very open access/ archive minded feature ..but there is a desire for such a thing.

**Comment by vpeil** [comment]
This can be added to the abstract (it's displayed on the frontdoor). But yeah, technically it's not an abstract information....
