### ISSUE TITLE
attribute "file" in before-hook should be array of hashes

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#543]
When using a before-hook during a "publication-update", the attribute "file"
is an array of json encoded strings, instead of an array of hashes. 

This happens when you upload files, and then save the publication.

The reason for this is that the attribute "file" is filled with the literal strings 
as received from the dropzone module.

This should be decoded when added to the attribute.
A writer of a hook shouldn't worry about decoding.

**Comment by vpeil** [comment]
@nicolasfranck I will close this one for now.
