### ISSUE TITLE
Overwrite ajax route in layer

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/LibreCat#562]
There seems to be a difference in visibility between ``get`` and ``ajax`` routes in layers. ``get`` routes can be overwritten in the layer without any problems. But it seems that ``ajax`` routes do not react the same way.

I tried to put the ``/get_department`` route into our layer in a new file ``/pub-librecat/lib/LibreCat/App/Search/Route/localajax.pm``. But the system still uses the route from the core.

Then I changed the type of the route to ``get``, to see if there was any other problem with it (the route or file not being found, for example). But then it is being used just fine.

Could you look into this, please? Is this reproduceable behavior, or am I just doing something wrong?

**Comment by vpeil** [comment]
@petrakohorst that was just a question, right? Do we still need this?

**Comment by vpeil** [comment]
no need for that.
