### ISSUE TITLE
Request a copy of a document results in internal server error

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#570]
After sending the form (modal) with mail address and message i get an internal server error. 

In app-log:

2018/08/28 14:42:47 INFO [30489] - LibreCat.App[46] : loading LibreCat::App::Permission::demo for demo
2018/08/28 14:42:47 INFO [30489] - LibreCat.App[67] : executing handler default for /rc/

in dev-log:

[29786] error @0.004234> [hit #4356]request to POST /rc/3588/3986 crashed: Validation failed for type named Defined declared in package Specio::Library::Builtins (/var/librecat/LibreCat/local/lib/perl5/Specio/Library/Builtins.pm) at line 44 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Defined declared in package Specio::Library::Builtins (/var/librecat/LibreCat/local/lib/perl5/Specio/Library/Builtins.pm) at line 44 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x42c99e8)', 'value', undef) called at (eval 431) line 71
DateTime::Duration::_check_new_params('days', undef) called at /var/librecat/LibreCat/local/lib/perl5/x86_64-linux-gnu-thread-multi/DateTime/Duration.pm line 68
DateTime::Duration::new('DateTime::Duration', 'days', undef) called at /var/librecat/LibreCat/local/lib/perl5/x86_64-linux-gnu-thread-multi/DateTime.pm line 1753
DateTime::_duration_object_from_args('DateTime=HASH(0x90c9610)', 'days', undef) called at /var/librecat/LibreCat/local/lib/perl5/x86_64-linux-gnu-thread-multi/DateTime.pm line 1725
DateTime::add('DateTime=HASH(0x90c9610)', 'days', undef) called at /var/librecat/LibreCat/lib/LibreCat/App/Catalogue/Route/file.pm line 77
LibreCat::App::Catalogue::Route::file::_calc_date at /var/librecat/LibreCat/lib/LibreCat/App/Catalogue/Route/file.pm line 199
LibreCat::App::Catalogue::Route::file::__ANON__ at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 271
Dancer::Route::execute('Dancer::Route=HASH(0x54800e8)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 186
Dancer::Route::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 101
eval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 94
Try::Tiny::try('CODE(0x941b158)', 'Try::Tiny::Catch=REF(0x8fc1f20)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 200
Dancer::Route::run('Dancer::Route=HASH(0x54800e8)', 'Dancer::Request=HASH(0x8fa1a98)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 137
Dancer::Renderer::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 103
eval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 94
Try::Tiny::try('CODE(0x8fe9ae0)', 'Try::Tiny::Catch=REF(0x8ee26d0)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 146
Dancer::Renderer::get_action_response('Dancer::Renderer') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 33
Dancer::Renderer::render_action('Dancer::Renderer') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 84
Dancer::Handler::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 101
eval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 94
Try::Tiny::try('CODE(0x2c6fa00)', 'Try::Tiny::Catch=REF(0x8a2b970)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 113
Dancer::Handler::render_request('Dancer::Request=HASH(0x8fa1a98)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 76
Dancer::Handler::handle_request('Dancer::Handler', 'Dancer::Request=HASH(0x8fa1a98)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer.pm line 491
Dancer::_start('Dancer', 'Dancer::Request=HASH(0x8fa1a98)') called at /var/librecat/LibreCat/bin/app.pl line 64
Plack::Sandbox::_2fvar_2flibrecat_2fLibreCat_2fbin_2fapp_2epl::__ANON__('HASH(0x94365b0)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/App/Cascade.pm line 48
Plack::App::Cascade::__ANON__('CODE(0x90faf60)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339
Plack::Util::__ANON__('CODE(0x943b830)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339
Plack::Util::__ANON__('CODE(0x944b140)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339
Plack::Util::__ANON__('CODE(0xa4aecd0)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339
Plack::Util::__ANON__('CODE(0x8e386c8)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 198
Starman::Server::dispatch_request('Starman::Server=HASH(0x27ad7c8)', 'HASH(0x94365b0)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 298
Starman::Server::process_request('Starman::Server=HASH(0x27ad7c8)', 'Net::Server::Proto::TCP=GLOB(0x827e5d0)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server.pm line 72
Net::Server::run_client_connection('Starman::Server=HASH(0x27ad7c8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 225
eval {...} at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 225
Net::Server::PreFork::run_child('Starman::Server=HASH(0x27ad7c8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 183
Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x27ad7c8)', 1) called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 373
Net::Server::PreFork::coordinate_children('Starman::Server=HASH(0x27ad7c8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 327
Net::Server::PreFork::run_parent('Starman::Server=HASH(0x27ad7c8)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 164
Starman::Server::run_parent('Starman::Server=HASH(0x27ad7c8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 109
Net::Server::PreFork::loop('Starman::Server=HASH(0x27ad7c8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server.pm line 58
Net::Server::run('Starman::Server=HASH(0x27ad7c8)', 'port', 'ARRAY(0x5ec5938)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 0, 'group', '0 0 0', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1, 'setsid', 1, 'background', 1) called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 94
Starman::Server::run('Starman::Server=HASH(0x27ad7c8)', 'CODE(0x59207f8)', 'HASH(0x5eb86d8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Handler/Starman.pm line 25
Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x5eb8618)', 'CODE(0x59207f8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Loader.pm line 84
Plack::Loader::run('Plack::Loader=HASH(0xf11ba0)', 'Plack::Handler::Starman=HASH(0x5eb8618)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Runner.pm line 277
Plack::Runner::run('Plack::Runner=HASH(0xceb3b0)') called at /var/librecat/LibreCat/local/bin/plackup line 7 in /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm l. 98

**Comment by vpeil** [comment]
I am sorry, but I could not reproduce that error, either. And I have never seen that stack trace before, especially the Specio::Library::Builtins  part.

**Comment by datango** [comment]
Problem also in Version 1.2.1. The following error is now displayed in frontend:
{
   "exception" : "Specio::Exception",
   "error" : "Validation failed for type named Defined declared in package Specio::Library::Builtins (/var/librecat/LibreCat/local/lib/perl5/Specio/Library/Builtins.pm) at line 44 in sub named (eval) with value undef\n\nTrace begun at Specio::Exception->new line 57\nSpecio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Defined declared in package Specio::Library::Builtins (/var/librecat/LibreCat/local/lib/perl5/Specio/Library/Builtins.pm) at line 44 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x3a6fee0)', 'value', undef) called at (eval 373) line 75\nDateTime::Duration::_check_new_params('days', undef) called at /var/librecat/LibreCat/local/lib/perl5/x86_64-linux-gnu-thread-multi/DateTime/Duration.pm line 64\nDateTime::Duration::new('DateTime::Duration', 'days', undef) called at /var/librecat/LibreCat/local/lib/perl5/x86_64-linux-gnu-thread-multi/DateTime.pm line 1775\nDateTime::_duration_object_from_args('DateTime=HASH(0x7e01f00)', 'days', undef) called at /var/librecat/LibreCat/local/lib/perl5/x86_64-linux-gnu-thread-multi/DateTime.pm line 1747\nDateTime::add('DateTime=HASH(0x7e01f00)', 'days', undef) called at /var/librecat/LibreCat/lib/LibreCat/App/Catalogue/Route/file.pm line 77\nLibreCat::App::Catalogue::Route::file::_calc_date at /var/librecat/LibreCat/lib/LibreCat/App/Catalogue/Route/file.pm line 207\nLibreCat::App::Catalogue::Route::file::__ANON__ at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 266\nDancer::Route::execute('Dancer::Route=HASH(0x54db168)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 189\nDancer::Route::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 100\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 93\nTry::Tiny::try('CODE(0x7806bb8)', 'Try::Tiny::Catch=REF(0x785a778)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Route.pm line 203\nDancer::Route::run('Dancer::Route=HASH(0x54db168)', 'Dancer::Request=HASH(0x675dae0)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 137\nDancer::Renderer::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 102\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 93\nTry::Tiny::try('CODE(0x32d8448)', 'Try::Tiny::Catch=REF(0x6765ac0)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 146\nDancer::Renderer::get_action_response('Dancer::Renderer') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Renderer.pm line 33\nDancer::Renderer::render_action('Dancer::Renderer') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 84\nDancer::Handler::try {...}  at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 100\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Try/Tiny.pm line 93\nTry::Tiny::try('CODE(0x2f1db50)', 'Try::Tiny::Catch=REF(0x78a44c0)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 113\nDancer::Handler::render_request('Dancer::Request=HASH(0x675dae0)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer/Handler.pm line 76\nDancer::Handler::handle_request('Dancer::Handler', 'Dancer::Request=HASH(0x675dae0)') called at /var/librecat/LibreCat/local/lib/perl5/Dancer.pm line 491\nDancer::_start('Dancer', 'Dancer::Request=HASH(0x675dae0)') called at /var/librecat/LibreCat/bin/app.pl line 64\nPlack::Sandbox::_2fvar_2flibrecat_2fLibreCat_2fbin_2fapp_2epl::__ANON__('HASH(0x63a6e98)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/App/Cascade.pm line 48\nPlack::App::Cascade::__ANON__('CODE(0x63a6bf8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x78a7d18)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x32d82e0)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0xf54b88)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x6771d38)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Util.pm line 339\nPlack::Util::__ANON__('CODE(0x67cd860)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 198\nStarman::Server::dispatch_request('Starman::Server=HASH(0x5b8b2f0)', 'HASH(0x63a6e98)') called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 298\nStarman::Server::process_request('Starman::Server=HASH(0x5b8b2f0)', 'Net::Server::Proto::TCP=GLOB(0x675d8e8)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server.pm line 72\nNet::Server::run_client_connection('Starman::Server=HASH(0x5b8b2f0)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 225\neval {...} at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 225\nNet::Server::PreFork::run_child('Starman::Server=HASH(0x5b8b2f0)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 183\nNet::Server::PreFork::run_n_children('Starman::Server=HASH(0x5b8b2f0)', 5) called at /var/librecat/LibreCat/local/lib/perl5/Net/Server/PreFork.pm line 107\nNet::Server::PreFork::loop('Starman::Server=HASH(0x5b8b2f0)') called at /var/librecat/LibreCat/local/lib/perl5/Net/Server.pm line 58\nNet::Server::run('Starman::Server=HASH(0x5b8b2f0)', 'port', 'ARRAY(0x6464588)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 0, 'group', '0 0 0', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1, 'setsid', 1, 'background', 1) called at /var/librecat/LibreCat/local/lib/perl5/Starman/Server.pm line 94\nStarman::Server::run('Starman::Server=HASH(0x5b8b2f0)', 'CODE(0x5b8e510)', 'HASH(0x5bb01e8)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Handler/Starman.pm line 25\nPlack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x613b0b0)', 'CODE(0x5b8e510)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Loader.pm line 84\nPlack::Loader::run('Plack::Loader=HASH(0xdf9c08)', 'Plack::Handler::Starman=HASH(0x613b0b0)') called at /var/librecat/LibreCat/local/lib/perl5/Plack/Runner.pm line 277\nPlack::Runner::run('Plack::Runner=HASH(0xd89410)') called at /var/librecat/LibreCat/local/bin/plackup line 7\n"
}

**Comment by vpeil** [comment]
Still, not confirmed. Demo server is running version 1.2.1 and this example works totally fine for me http://demo.librecat.org/record/271 (accept that the mailer is not configured....)

**Comment by vpeil** [comment]
This error is due to a missing config parameter: `request_copy.period`. I will submit a patch which will at least provide a default value.

**Comment by vpeil** [comment]
configuration option is already documented in `config/catmandu.local.yml-example`.

PR #636 adds log message.
