### ISSUE TITLE
Naming confusion `Personal Publication lists` on homepage

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#571]
I got feedback here that naming of the menu facet on the LibreCat start page `Personal Publication lists` is confusing. This link points to the `/person` route and is the same as the `Authors` tab.

One could think `Personal Publication lists` as some kind of new feature of LibreCat. Like stored bookmarked lists (which is not the case).

**Comment by vpeil** [comment]
I agree. It should be named "Authors", I think. Or in your layer "{My Institution's} Authors". Wil send PR.
