### ISSUE TITLE
Publication abstract: Info-Link about Markdown has wrong target

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#572]
The link target is
https://librecat-hostname.de/docs/howto/markdown.
This site does not exists. 
Use 
https://pub.uni-bielefeld.de/docs/howto/markdown
or
move this page to the source

**Comment by vpeil** [comment]
We had some internal discussions and decided to deprecate the Markdown feature as it can cause different sorts of problems. If still desired this can be easily added within a layer.

Hence, I will send a PR where we just remove this information.

**Comment by vpeil** [comment]
ah, this has been already fixed by commit 3c45d9728fd81884c93ded22ff5c8e84dce401f3
