### ISSUE TITLE
Problem with subscript and superscript

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#573]
I imported the DOI 10.1103/PhysRevB.93.184305
It results in a publication with the following wrong title: Vibrational properties ofLiNb1−xTaxO3mixed crystals
Correct title: Vibrational properties of LiNb<sub>1−x</sub>Ta<sub>x</sub>O<sub>3</sub> mixed crystals

Markdown like here in Github does not work. DOI-Import should also work correctly.

**Comment by vpeil** [comment]
That's the entry from the crossref api

```yaml
title: Vibrational properties ofLiNb1−xTaxO3mixed crystals
```

Check it yourself:

```bash
bin/librecat publication fetch crossref "10.1103/physrevb.93.184305"
```

Nothing to do here for us.
