### ISSUE TITLE
Lingering generator fields that are not used (and do not work anymore)?

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#577]
What should we do with generator fields that are not used in the forms (and probably still are defined also in the schema.yml)? As is, they seem to be conflict with the schema:

E.g.

* link.tt
* msc_class.tt
* pacs_class.tt

**Comment by vpeil** [comment]
cleanup is needed here. Or is anybody planning to use these in their forms?

**Comment by nics** [comment]
I'm using the links field but have overriden the config in our layer, so removing them should have no consequences.

**Comment by vpeil** [comment]
I think `link` is replace by main_file_link or so (with OA option flag).  @petrakohorst knows better.

**Comment by vpeil** [comment]
fixed by merge of PR #592
