### ISSUE TITLE
Compatibility with ElasticSearch version > 5.5.x

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#579]
For the next debian version librecat needs to support elasticsearch > 5.5.x

[Elastic Support Matrix](https://www.elastic.co/de/support/matrix)

**Comment by nics** [comment]
I've released a new version (0.0511) of Catmandu::Store::Elasticsearch that supports recent versions of es without the need for id_key or key_prefix. I'll also add some notes to this comment on how to migrate queries and the mapping.

**Comment by nics** [comment]
### mapping
- the `standard` analyzer filter does nothing and gives a warning, I removed it
- `include_in_all` is deprecated, there is no `_all` field anymore, make your own instead:
```a
aAALLL
```

**Comment by nics** [comment]
work on this is being done in the feature/es65_support branch. Catmandu::Store::Elasticsearch also needs some big changes (bag_index branch)

**Comment by nics** [comment]
The feature/es65_support branch combined with dev release 0.9_02 of Catmandu::Store::ElasticSearch supports Elasticsearch 6.5, all tests pass.

**Comment by vpeil** [comment]
That's amazing! What's the next step? Should we test this on our own dev-machines?
