### ISSUE TITLE
File download for files with spaces in name results in error

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#582]
If you have an attached file with a space in the name., the download results in an ERR_INCOMPLETE_CHUNKED_ENCODING exception.

For example, have a look at the demo server at record 62 and there the second file ("a b.txt"). See http://demo.librecat.org/record/62 and then http://demo.librecat.org/download/62/105/a%20b.txt

**Comment by vpeil** [comment]
I believe this problem has been addressed and solved in PR #525 . Needs to be merged.

**Comment by vpeil** [comment]
Fixed by 75838539cfe72ece1def057f3eb4ba0c9cdc1e9b (currently on dev branch)
