### ISSUE TITLE
Supervisor worker logs get endless "daemon already running" warnings

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#584]
This fills my log partition

```
cat log/librecat-cmd-worker-mailer.supervisor.log

daemon already running: librecat-cmd-worker-mailer
daemon already running: librecat-cmd-worker-mailer
daemon already running: librecat-cmd-worker-mailer
daemon already running: librecat-cmd-worker-mailer
```

**Comment by nicolasfranck** [comment]
cf. https://github.com/wu/Proc-Launcher/issues/6

**Comment by nicolasfranck** [comment]
Better to exchange the Proc::Launcher for something else: last update dates from 2015, and the author does not react anymore..

**Comment by vpeil** [comment]
Any suggestion which module to pick?

**Comment by vpeil** [comment]
We are moving away from Gearman and Proc::Launcher, see PR #826
