### ISSUE TITLE
Editing admin record of a local user throws away the password 

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#587]
@nicolasfranck  is this related to #526?

Check on the command line the user record for `james`

```
bin/librecat user get 3
```

Notice a password field available.

Now:

* login into the website as `einstein`
* Manage users 
* Edit `james`
* Don't do anything, just save the record

Check again the user record:

```
bin/librecat user get 3
```

The password is gone

**Comment by nicolasfranck** [comment]
@phochste : that pull request does not solve that issue. It was like that before, and also in the dev branch. The reason here is that the old data from the store is neglected, and the posted parameters are treated as the "full record".
