### ISSUE TITLE
Centos7 plackup warning watch failed: No such file or directory 

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#593]
When starting the plackup daemon on CentOS 7 a warning will be generated:

```
$ plackup -R lib --port 5001  bin/app.pl
Watching lib bin/lib bin/app.pl for file updates.
watch failed: No such file or directory at /opt/librecat/local/lib/perl5/Plack/Loader/Restarter.pm line 79.
```

Which will go away when creating `mkdir bin/lib`

**Comment by vpeil** [comment]
I don't see this behaviour on debian 9.

```bash
$ carton exec -- plackup -R lib --port 5001  bin/app.pl
Watching lib bin/lib bin/app.pl for file updates.
HTTP::Server::PSGI: Accepting connections at http://0:5001/
```
It's watching the non-existent directory bin/lib, but no errors/warnings.

**Comment by vpeil** [comment]
that is a plackup issue, see https://github.com/plack/Plack/pull/620 (But that repo seems to be a bit inactive)
