### ISSUE TITLE
Librecat needs a layout and code stripped from Bielefeld specific logos names

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#6]
Bielefeld specifics

- Logos, banners, text on the homepage
- HRZ specific fields in login screen
- Explicit connections to the Bielefeld Information System in the App controllers and routes
- PubTheses services, links to Research Data Management etc

**Comment by vpeil** [comment]
see branch `clean_layouts` for progress on this issue

**Comment by vpeil** [comment]
done (at least from my perspective)
