### ISSUE TITLE
Feature: Mark for deletion

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#612]
It would be nice to allow users with access to a publication (owner/author/reviewer) to mark a publication for deletion. Also there could be a checkbox to select a reason. For example "Duplicate Entry". 

Ther should be a option to filter this publications, which is default active.

For cleanup reviewers or other roles could have the permission to accept this request for deletion.

**Comment by vpeil** [comment]
This is how we do that: The user can return a publication record, this a in fact a sign for deletion. One can delete these records manually or by using a cronjob with the librcat CLI.

@datango do you angree?

**Comment by datango** [comment]
To whom will the publication be returned? Wasn't that the sign to the reviewer or the author to revise the entry? Is "returned" clear enough to do a automatic deletion?

**Comment by vpeil** [comment]
Returned publications will be visible to the admins. Reasons for a "return" can be different:

- oopos, i did a mistake
- duplicate
- published too early, data missing,
- etc.

I think it is a matter of what we would like to mean "return".

**Comment by datango** [comment]
That is what i would like to have. Getting a reason (duplicate/please delete) - then i can delete by script.
