### ISSUE TITLE
Catmandu::Sane missing?

### ISSUE THREAD

**Issue by ArSa-Apps** [LibreCat/LibreCat#62]
Hi,
did anyone forget to put this one in the **cpanfile**?
Cheers,
A.

**Comment by nics** [comment]
it comes with the Catmandu install

**Comment by ArSa-Apps** [comment]
Hi, well in my case it didn't...
Is there any problem with perl 5.18? Should I upgrade to 5.2x?

**Comment by nics** [comment]
no 5.18 is fine
maybe something wnet wring with the install?

**Comment by phochste** [comment]
@ArSa-Apps Then there has to be something missing the install steps. Catmandu::Sane is already part of the Catmandu installation since  very first 0.01 version. 

Make sure you use the carton install installation.

    $ pwd
    /opt/librecat
    $ find local -name Sane.pm
    local/lib/perl5/Catmandu/Sane.pm

**Comment by ArSa-Apps** [comment]
Well, I can't say why, but it won't install automatically. Even after I added the requirement to the end of cpanfile, it's been ignored completely. As of last friday using the core-build, I'm stuck at the step for generating forms...
