### ISSUE TITLE
Request a copy also for Closed and Local Access

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#638]
At the moment, the access level of a publication file is one of the following options: "Open Access", "Local Access", "Closed Access" or "Request a Copy".

Especially as a user, you are not able to request a copy for a local or closed access file. In my opinion the feature of requesting a copy should also be enabled for these two access levels.

**Comment by vpeil** [comment]
I am not sure what you mean. Maybe you have misunderstood this functionality? I am trying to explain a bit: One has the following levels
- open access
- embargo (switch to open access at date X)
- local
- closed (with option to select request-a-copy)

And request-a-copy is not that sort of a feature which should push, because if a user leaves the institution (which happens often) the request mails are sent to nirvana

**Comment by feldi-online** [comment]
As far as I can see, your description of the levels does not correspond to the current status, but describes nearly the behavior which I would assume.

At the moment, you have the following options for the access level: 
![image](https://user-images.githubusercontent.com/6943048/48302178-52af2600-e4f9-11e8-8425-1df8c359fa76.png)

The difference to your list is the option closed access vs. request-a-copy. The request is not an additional option to closed access, but a completly different access level. That results in publications which have a close access level, a no possiblity to have an option to request a copy.

I would propose the following levels:

- Open Access
- Local Access (with request-a-copy option or mandatory)
- Closed Access (with request-a-copy option or mandatory)
- Request a Copy
(and additionally the embargo option as it is at the moment)

I hope my issues is clear now. Especially, you assumed a behavior in your answer that is not possible at the moment.

**Comment by vpeil** [comment]
I am not convinced that we should make our access levels more complex.
Our focus is defnitely on open access, request-a-copy was introduced because some people asked for that.
