### ISSUE TITLE
My Publications list and export lists do not have the same publications

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#639]
The request of "My Publication list" with url like https://hostname.de/person/1234 results in all publikations where the user 1234 is author. But when i export the list for example as Json with url https://hostname.de/export?fmt=json&person=1112 - i get all publications.

The export of a list and the displayed list on the website must show the same publications.

**Comment by ThriceGood** [comment]
i believe the url should be:

https://hostname.de/export?fmt=json&cql=person=1112

'person' needs to be in a cql query

**Comment by vpeil** [comment]
This has been fixed by PR #611 (merged into dev 2 hours ago)
