### ISSUE TITLE
Layout issues with new assets generated stylesheet

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#64]
The default layout of Librecat contains now next to every button a small square (sometimes in front and end of the button). The icon for 'help' is missing in the top bar. The icon 'flag' next to the language switch is missing. Etc etc for all the top navigation bar icons. Same for arrow icons missing for the facets.

The 'add new publication' button is too small for the text.
The author firstname/last name field is too small for the text.
The volume/page select overflows the text field next to it.

**Comment by vpeil** [comment]
is this still an issue? (I think this has been fixed)

**Comment by vpeil** [comment]
looks like oudated.
