### ISSUE TITLE
Installation of Gearman::XS fails during first install

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#641]
Reason: Module::Install is missing and causes the error "inc::Module::Install not found".

This module is available in the cpanfile, but a cpanfile does not enforce any kind
of dependency installation order. So it cannot be fixed there.

Issue reported: https://rt.cpan.org/Ticket/Display.html?id=110739&results=e72413f9c529e37dd5e82ea9633d053d

Version of Gearman::XS should be increased when done.

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/654

**Comment by vpeil** [comment]
has been merged into dev a while ago.
