### ISSUE TITLE
Reindexing records get painfully slow when the number of record into order O(100 000)

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#642]
In Ghent I have a database with 500 000 records. Reindexing all these records gets quite slow (+/- 3 hours and speed drops with number of record) with our current MySQL/Catmandu setup which uses UUID _id identifiers

There are two issues:

1. The Catmandu DBI iterator goes through the database using LIMIT + OFFSET 
2. The Catmandu DBI iterator does a ORDER BY on the _id field for every batch of records

The 2nd point can be solved when a new version of Catmandu::DBI is published on CPAN (hint @nics ). The 1st point can't be easily solved with Catmandu. LIMIT/OFFSET is a very slow process in relational databases. 

Another algorithm/solution is needed in LibreCat to provide fast indexation of data.

**Comment by phochste** [comment]
This trick http://devoluk.com/mysql-limit-offset-performance.html makes (to be implemeted in Catmandu::Store::DBI::Iterator) makes the scan 20 times faster, but still slows down for large queries.

**Comment by nics** [comment]
This optimization is now in the dev branch of Catmandu::DBI

**Comment by nics** [comment]
Released as Catrmandu::DBI 0.08
