### ISSUE TITLE
Creator visible for other internal users

### ISSUE THREAD

**Issue by feldi-online** [LibreCat/LibreCat#643]
If someone in the system (e.g., support staff) adds new publications with me as author, but does not map anyone as internal author (and also no departments, projects, etc.), I have no chance to identify a responsible person to contact her for adding missing data and correcting errors.

One easy approach to handle this and similar issues would to show the creator of a record for all internal users. Therefore you have always at least one contact person for a publication (next to the superadmin). But perhaps there are other solutions as well I am not aware of at the moment.

**Comment by vpeil** [comment]
Well, one can always contact the support team. No need to spam researchers with data issues.
Besides that, by displaying publicly the email and name of the creator one could run into GDPR issues. And currently I would avoid those discussion at all costs.

The easiest solution is: every installation can decide on their own, by overrind one template to display this information publicly.

Therefore, I'm closing this one.
