### ISSUE TITLE
LibreCat-CLI as separate project

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#645]
As our code basis grows it would be more suitable to split the project into separate parts.

Any opinions?

**Comment by nicolasfranck** [comment]
Indeed. Putting all of the model-related stuff into a separate project. LibreCat should be an implementation of that. A sort of rails_admin for perl. That way one can use it for its own need, instead of commenting out things that you do not need.

**Comment by phochste** [comment]
For now I moved it to https://github.com/LibreCat/LibreCat/wiki/Roadmap-(1.X.X) ..to be discussed when we talk about next roadmap
