### ISSUE TITLE
'Fulltext URL' field link in tab_details has internal location prefix 

### ISSUE THREAD

**Issue by ThriceGood** [LibreCat/LibreCat#662]
After setting the 'Fulltext URL' field of a record, which I believe is an external file link, the link in tab_details has a prefix for an internal location: **http://demo.librecat.org/record/**www.test-location.com%2Frecord%2F123

Here is the example record: http://demo.librecat.org/record/296

Am I right in thinking that this is an external file link that should not have this internal prefix?

**Comment by patrickda** [comment]
Yes we discovered this bug also, would be nice if it got be fixed.

**Comment by phochste** [comment]
There is not a prefix added to the URL (that is what the browser does). What happens is that the example records URL field doesn't contain a Full URL. It has `www.test-location.com/record/123` instead of `http://www.test-location.com/record/123` (or is it `https://www.test-location.com/record/123`?)

**Comment by phochste** [comment]
Maybe the ticket should be : "Add default http://" to the Full text URL when no scheme has been provided.

**Comment by patrickda** [comment]
We providing  a scheme our URL is saved as:

http://othes.univie.ac.at/51113/

The external download link is correct but on the linking page it becomes:
https://research-explorer.app.ist.ac.at/record/http%3A%2F%2Fothes.univie.ac.at%2F51113%2F

it can be seen here:
https://research-explorer.app.ist.ac.at/record/278
We are just preparing to go live (today)

**Comment by phochste** [comment]
Weird. https://research-explorer.app.ist.ac.at/record/278 looks ok to me..also the link to the external page seems to work. Also the HTML is correct:

```
   <a itemprop="url" href="http://othes.univie.ac.at/51113/">http://othes.univie.ac.at/51113/</a>
```

**Comment by patrickda** [comment]
Yes but if you go to the links page it and look there the link to the  main file the link is wrong generated.

**Comment by ThriceGood** [comment]
Great, its working now. Thanks!
