### ISSUE TITLE
Bibtex Export shows HASH for authors and language

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#664]
The Bibtex export produces wrong output:
@journal_article{1234,
  author       = {HASH(0x816df08) and HASH(0x7c120e8) and HASH(0x92ea7a8) and HASH(0x902b080) and HASH(0x91cf928) and HASH(0x8f84258)},
  language     = {HASH(0x9394330)},
  publisher    = {Demopublisher},
  title        = {Demotitle},
  type         = {journal_article},
  doi          = {123.324234/sjdflkjsdlf},
  volume       = {12},
  year         = {2018},
}

**Comment by phochste** [comment]
@vpeil the previous remark is a problem, but not the source of this issue

**Comment by phochste** [comment]
@vpeil The global $config options were changed in the code to delete/add some features. On a second run the 'fixes' was missing from the global options. Changed it to requesting a clone of options at every run
