### ISSUE TITLE
All LibreCat::Cmd-s that accept an ID should also support FILE(of ID) or multiple ID's

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#688]
Starting a Perl process (and reading the configuration files) is relative slow process. Starting a new Perl process for every ID required for a particular command is slow, when processing many thousands of IDs.

Support loadings IDs from File. E.g.

```
 if (-r $id) {
      for (path($id)->lines) {
           chomp;
           process($_);
      }
 }
 else {
    process($id);
 }
```

**Comment by vpeil** [comment]
Do you have an example which of the commands does not support the above? To me it seems that they all do the above.
