### ISSUE TITLE
Importers in web gui do not work

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#706]
1) Importing Bibtex
2) Error Message: Import from bibtex failed - try later again

Hotfix:
Copying old version of LibreCat/lib/LibreCat/App/Catalogue/Route/importer.pm (from Version 1.2.3) to same path.

The following commits are related to this file:
All Catmandu::Importer::getJSON require to have 'warn => 0' as parame…
Removed debug statements
Harden the CrossRef exporter against network errors #564

**Comment by datango** [comment]
The Problem is in "Harden the CrossRef exporter against network errors #564". If i revert this commit  the import works.

**Comment by phochste** [comment]
Fixed in dev. Preparing small release
