### ISSUE TITLE
"Search > Display > Hits per Page" broken

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#71]
changing from default 20 to e. g. 10 does nothing (not even a console log message).

Test URL: http://demo.librecat.org/publication

**Comment by petrakohorst** [comment]
Fixed on demoserver: there was a typo in filters.tt It said pq instead of the right variable name qp. (I know... bad variable naming...)
Again: gitting and pushing to github left to Vitali

**Comment by vpeil** [comment]
fixed on dev branch
