### ISSUE TITLE
use template layout?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#713]
LibreCat does not use a template layout, but resides to header.tt and footer.tt.

That way one has to add those to every template.

Now 90% of header.tt is filled with information that only applies to a single publication
record, and so does nothing when loaded in another context (e.g. publication list, admin account ..),
which messes up the code ..

The layout should only add generic things like css and javascript files, provided a footer and header ..

Those who do not wish this layout can always override it in the controller.

**Comment by nicolasfranck** [comment]
A second option is to fill the header.tt and footer.tt with minimal as possible. So in that case every template that needs to add something to the header, has to write its own specific template, and include that.

The same should apply to other templates like hits.tt, that is now used in  variety of ways, leading to number of if-statements for no good reason ("if this is used in the controller /marked, then ..").

**Comment by nics** [comment]
Inside out templating generally works well, where the inner template tells the wrapping template what the content for specific zones is.
It's pretty easy to make a construct like this:

```
[% WRAPPER layout foo=bar %]
  [% FILTER $content_for_head %]
    <meta foo="bar">
  [% END%]
  [% FILTER $content_for_sidebar %]
    <aside>
    </aside>
  [% END%]
  <article>
    <h1>My page</h1>
 </article>
[% END %]
```
