### ISSUE TITLE
Import & Quick and easy upload results in an 404 error when editing the record

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#714]
Steps:

- Login as 'einstein'
- Add a quick and easy publication
- Click on 'edit' to edit the metadata
- Set the DDC to some value
- Click on 'Submit'

I see a 404-page.

**Comment by phochste** [comment]
Same issue happens with any import

**Comment by vpeil** [comment]
The records are stored correclty, though.

The problem is that after "POST /record/update" it tries to redirect to the previous route.

**Comment by phochste** [comment]
It is not a nice way to be directed to `/librecat/record/import` or `/librecat/upload/qae/submit` after a successfull upload. It would be nicer to see the `/librecat/record/new` page + URL after any successfull import. Alas, one can be redirected to `/librecat/record/new` after a successful upload, but there is no code available to inform then which records were uploaded.

There is a quick and dirty solution just to add a GET route for the import and qae urls. A better solution would be as I described above.

Also in the current form the import procedure is not really great for large imports. When one imports a file with hundreds or thousands of records the interface will break. 

This part of the code should be marked as need for a rewrite anyhow.
