### ISSUE TITLE
Alias is displayed as "undefined undefined" if firstname and lastname are not completely given

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#715]
- Edit publication
- Insert author name with an alias entry (User Max Mustermann, Alias Maximilian Mustermann) by giving Ma Mustermann or Maximilian Musterma (some missing chars)
- Click on "Internal"/LibrecatAuthor.
- Select-Box "Choose name" pops up.
- One of the items is "undefined undefinded (now Max Mustermann)

![grafik](https://user-images.githubusercontent.com/30523869/54990356-d0606380-4fba-11e9-8860-d162db739177.png)

**Comment by vpeil** [comment]
fixed by merge of #725 into dev.
