### ISSUE TITLE
support of OpenAIRE Guidelines v4

### ISSUE THREAD

**Issue by joschirr** [LibreCat/LibreCat#718]
Hi,
is there any chance to have support for OpenAIRE Guidelnes v4, released in November-2018

* https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/introduction.html
* http://dx.doi.org/10.5281/zenodo.1299203

which introduces a new application profile build on elements from DublinCore, DataCite and OpenAIRE, makes use of COAR Vocabularies and integrates with identifier systems such as ORCID and FundRef.

**Comment by vpeil** [comment]
Hi @joschirr, if it's not a april's fool, I will definitely have a look at it.

**Comment by vpeil** [comment]
@joschirr question w.r.t embargo data:
The [documentation](https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_embargoenddate.html) does not allow repeated fields here (except for the case "accepted" and "available"). In our data model one can set the embargo date for every file. Or should we consider this output if and only if **one** file exists?

**Comment by joschirr** [comment]
embargo is considered for the whole record rather than on the file level.

**Comment by vpeil** [comment]
But that's not an answer to my question. Just take the first file with embargo then?

**Comment by joschirr** [comment]
so to say. Or the file with the earliest embargo start date and the longest embargo end date
