### ISSUE TITLE
LibreCat::Search implies model specific facets, but not configured anywhere

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#721]
LibreCat::Search implies model specific facets:

https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Search.pm#L60

where a merge happens between the supplied facets and the default_facets,
but I cannot find anywhere where those first are supplied..

**Comment by vpeil** [comment]
You are right. I think there were some special modifications of the facets in the past. Obviously they are gone.

I suppose your question is: can we cleanup this code?

**Comment by nicolasfranck** [comment]
yup

**Comment by vpeil** [comment]
I can prepare a PR.

**Comment by vpeil** [comment]
@nicolasfranck I found a place where I actually use it, although it's still a PR: https://github.com/LibreCat/LibreCat/pull/683/files

If removed I need to rework the PR.

**Comment by phochste** [comment]
@vpeil  What is the status of this pull request? It is unclear for me if this is a WIP or not. If it is a WIP, then please close the PR and work on the branch.

**Comment by vpeil** [comment]
@phochste I have closed the PR #683 some time ago. The PR #746 does what @nicolasfranck suggested, hence can be merged.

**Comment by nicolasfranck** [comment]
@phochste in that PR Vitali removed something that could never work, i.e. preconfigured facets per model, because now there is no way to supply these.

**Comment by vpeil** [comment]
Aha! For now only publication facets are supported, i.e. there's still no way of declaring model-specific facets.

**Comment by phochste** [comment]
@nicolasfranck @vpeil I'm still confused by these answers. Simply: Yes or No : is this PR read to be merged?

**Comment by vpeil** [comment]
NO. (I'll discuss with @nicolasfranck )

**Comment by vpeil** [comment]
Please have a look now.
