### ISSUE TITLE
no need to put "audit" into a worker

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#730]
The worker "audit" doesn't do anything more than just adding a record to a table.

**Comment by nicolasfranck** [comment]
some inconsistencies are bothering me:

* according the mapping in config/store.yml the attribute "time" is supposed to be an "integer". This is enforced on database level
* according to the test "t/LibreCat/Cmd/audit.t" it is supposed to be an UTC formatted string
* controller LibreCat::App::Catalogue::Route::audit sorts the audits using the function "cmp" (used for string comparison!), and then maps the attribute "time" to "date" treating it as an integer (because gmtime is used). 

Strange ?

**Comment by nicolasfranck** [comment]
Who is actually using this route ..
```
post '/audit/:bag/:id'
```
in LibreCat::App::Catalogue::Route::audit

In the old code it starts a new job of type "audit",
and returns the job_id in a json response

I'm trying to deprecate this worker, so I'm trying
to get rid of this also.

**Comment by nicolasfranck** [comment]
apparently, the test 't/LibreCat/Cmd/audit.t' does not fail because SQLite accepts anything:

https://sqlite.org/faq.html#q3

but this is not the case for example postgres.

**Comment by nicolasfranck** [comment]
LibreCat::Worker::Audit->work also tests wether
```
Catmandu->store("main")->bag("audit")
```
returns a bag or not..

This is not really needed:

* if Catmandu->store("main") returns undef, this call will fail with something like "cannot call method work on undef", and nothing in the application will function anymore (publications, departments ..)

* if the latter does exist, but the mapping for bag "audit" is not present, then  Catmandu will create a default mapping.

**Comment by vpeil** [comment]
We do not use this feature at all.

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/LibreCat/pull/733

**Comment by vpeil** [comment]
PR #733 has been merged into dev.
