### ISSUE TITLE
Typing for department selection list not working

### ISSUE THREAD

**Issue by snorri** [LibreCat/LibreCat#74]
Selecting with arrow keys works, but it doesn't work to type anything - nothing is found. Also the input field looses focus if you type something when the list is displayed (same behavior on demo server).

**Comment by phochste** [comment]
This works in the 'dev' branch

**Comment by vpeil** [comment]
I had some issues with that problem, too. So, it is fixed now, **but** recreate your index to make it work due to some changes in `config/store.yml`. Will be soon on demo server....
