### ISSUE TITLE
hook "add_urn": does it work?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#740]
I tried to make a librecat hook that adds an attribute before the record is added during update.

But when I tried to iterate over the publication files, I see that they are json strings.
But in the hook "add_urn" those publication files are treated as normal perl hashes,
while that hook also tries to add something before saving.

So where is "add_urn" supposed to be used? Shouldn't the list of files not be decoded before applying any hooks?

**Comment by vpeil** [comment]
yes, it does. It is used in our local layer in fixes/update_publication.fix

**Comment by vpeil** [comment]
just noticed that in our local layer in is a classic fix (hence it is in fix file) and not as a hook. Probably, you are right, that it wouldn't work as a hook_before.
