### ISSUE TITLE
Editing records simultaneously in multiple browser windows is dangerous

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#751]
Reviewer and secretaries often open many windows simultaneously to import and edit data in LibreCat. This can lead to data getting lost when by mistake two or more windows have the same record opened.  

E.g. when Window1 has uploaded files and Window2 not yet, these files will get lost when Window1 saves the record earlier than Window2.

**Comment by nics** [comment]
Solving this will require locking records when they are being edited, or at least keeping timestamps
