### ISSUE TITLE
"Make public" not working (dev branch)

### ISSUE THREAD

**Issue by snorri** [LibreCat/LibreCat#76]
Clicking on "Make public" doesn't work. The value of the "finalSubmit" button gets removed before being processed by update_publication.fix so the status never gets changed to public.

**Comment by vpeil** [comment]
not confirmed

**Comment by phochste** [comment]
There was indeed a finalSubmit in the  update_publication.fix  that doesn't have any effect. It never reaches this fix. This only had an effect on the records with status 'saved' -> 'submitted'. 

The code was fixed to move this 'finalSubmit' logic to the controller.
