### ISSUE TITLE
version 2.0.0_01: mojo_app.pl implicitly creates dbi connections before forking

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#764]
in the latest version 2.0.0_01, mojo_app.pl implicitly creates dbi connections before a fork is done by starman. That way it complains about reused connections after a fork.

Reproduce:

* use Starman
* use Pg (postgres) as backend

Disabling mojo_app.pl in bin/app.pl removes the problem of course.

**Comment by phochste** [comment]
@vpeil @nics can't the mojo be started in a separate process? What is the consequence of all this?

**Comment by vpeil** [comment]
Starting the API in a separate process (on a different port) could work. It would also have the advantage that you don't have to run the API if you don't need to.

@nics I think there are no interaction between the mojo and the starman, the mojo app uses the LibreCat::Models, so separating the two should be fine.

**Comment by nicolasfranck** [comment]
I do not see connection between "starting mojo in a separate process" and the problem that is described. 

The main problem is that DBI connections are created before any fork happens. So if someone happens to start mojo with a forking server, it will have the same problem. 

In Catmandu::DBI a connection is created once the bag created (used to pre-create the tables). @nics is working on a solution in Catmandu::DBI by making those table-creations lazy, but it is something we have to watch out for: one should not create dbi connections before the fork.

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/767
