### ISSUE TITLE
what is the use for the /search sub routes in admin.pm?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#770]
/admin/account does almost the same thing as /admin/account/search,
meaning that it does not execute a search, and shows an empty list.

The same for /admin/project and /admin/research_group.

Why not simply merge this into one? When the query is empty,
it should be interpreted as a catch all query.

**Comment by vpeil** [comment]
and we should use dynamic routing for this, like in our mojo api (which is model-agnostic)

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/LibreCat/pull/783

**Comment by vpeil** [comment]
Routes have been merged into one via PR #783.
