### ISSUE TITLE
Need a stricter check on `new_record` in publication  updates

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#772]
`new_record` should only be possible for records that don't exist in the database. In all other cases, someone is messing around with the HTML form.

**Comment by nicolasfranck** [comment]
`new_record` is only part of the problem. Now both new records and existing records are added by calling `POST /librecat/record/update`. 

What should happen for now:

* remove any reference to `new_record`
  difference between old and new records is the existence of an `_id`
* `_id` should only be generated when added to the bag, not when you open a web form.
    in case of UUID it doesn't matter, but it can be problematic for id generators that are
    number based, and just take the highest number, and add one to it.
    the models already have this built in, so need to replicate this.
* create route for posting new records: `POST /librecat/record`
   this should remove `_id` when present
* create route for updating existing records: `PUT /librecat/record/:_id`
   this should check for a matching record, and merge data with it.

willing to implement this, if everyone agrees.

**Comment by phochste** [comment]
@nicolasfranck I agree. But you need to be very carefull. When uploading content to a 'new' record , LibreCat needs to know in some way the relation of the content to the metadata record. In the current implementation this relation is the record identifier. But please suggest a solution

**Comment by nicolasfranck** [comment]
> @nicolasfranck I agree. But you need to be very carefull. When uploading content to a 'new' record , LibreCat needs to know in some way the relation of the content to the metadata record. In the current implementation this relation is the record identifier. But please suggest a solution

Are you referring to the file upload? The route `/upload` generates a new record id in the temp-store for every file that is uploaded, so when you upload 2 files, you get 2 directories with  each one file in it. That is the `tempid` that is referred to in `LibreCat::App::Catalogue::Route::upload`. So there is no need for `_id` to preexist in the form for this to work. Right?

**Comment by phochste** [comment]
@nicolasfranck yes please I was referring to this. It will probably work indeed as you said, but please also test the file uploads when you start working on this

**Comment by nicolasfranck** [comment]
see https://github.com/LibreCat/LibreCat/pull/888

**Comment by nicolasfranck** [comment]
@phochste you were right about the need to insert the `_id` in the form. I saw that this is not required by the uploading module, but by `LibreCat::App::Catalogue::Controller::File::handle_file`. So I did not change that.
