### ISSUE TITLE
metadata whitelisting not consistent 

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#782]
The LibreCat currently only has a whitelisting of fields in the root level of a model. Any
other deeper nested data just passes by the whitelisting as if nothing is wrong. E.g.

```
good_field_1: A
good_field_2: [ 1,2,3,4 ]
good_field_3: 
     good_subfield_1 : abcd
     bad_subfield_2 : AAARGH
```

The whitelisting checks good_field_1,good_field_2,good_field_3 but not good_subfield_1 and bad_subfield_2.

In practice this means e.g. that a bad user can send whatever JSON metadata in the file metadata and it will be added to the database.

**Comment by phochste** [comment]
Setting

```
additionalProperties: true
```

Doesn't seem to work for the JSON::Schema implementation

**Comment by vpeil** [comment]
Did commit a0cb304e209d4620484c5950db004c50fd770e56 solve this issue?

**Comment by phochste** [comment]
Yup this is solved
