### ISSUE TITLE
Project publications - Missing options

### ISSUE THREAD

**Issue by datango** [LibreCat/LibreCat#788]
Using the project tab you get an url like /project/99. On that page you can see the project publications. But there are no options available to sort or export these publications.

As a workaround you can use /record?cql=project=99.

**Comment by vpeil** [comment]
Well, I would consider this an overkill feature. If it is more plausible I would remove the publications at all from the project page and link to ` /record?cql=project={ID}`.

**Comment by vpeil** [comment]
I guess it's just a `won't fix`
