### ISSUE TITLE
"access denied" should be different for content

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#790]
Now there is one page that says "access denied",
surrounded by menu bars. But if you received
a download link to a file, it is strange to land on
an end user page.

I guess there are other examples

**Comment by phochste** [comment]
@nicolasfranck Can you elaborate a bit further. "But if you recieved a download link" , I guess the [you] in this sentence is an enduser. A machine will get a HTTP 403 status code. It is a service to the enduser to show that something has happend to the link that makes it not available.

What do you have in mind to send to the enduser in case of a 403?

**Comment by nicolasfranck** [comment]
@phochste yes I mean an end user. If you receive a download link to a file, for example extracted from the OAI, then you don't expect (read: it should not) ending up in a user interface. The same goes for a 404.

**Comment by phochste** [comment]
@nicolasfranck I still do not understand what you would send back to the enduser? She/he should be informed in one way or another the file is not available, not? What should the body a 404 or 403 contain? And XML file ? A JSON response? And the enduser will be happy?
