### ISSUE TITLE
files deleted when submit is clicked while page is still loading

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#793]
Steps to reproduce:

* you have an existing record with a lot of files (typically around 2000 or more)
* load the edit page
* before it is fully loaded, you hit the save button
* as not all file inputs were loaded at the time you hit the submit button,
  just a part was sent. LibreCat decides to throw away the "missing" files.

**Comment by vpeil** [comment]
fixed by PR #795
