### ISSUE TITLE
"starMandatory" added to label of field "DDC" for every uploaded file

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#794]
When you upload 10 files,
10 "*" are appended to the label of field.
If the upload is slow, you actually see it appending..

<img width="1440" alt="Screenshot 2019-09-06 at 11 38 23" src="https://user-images.githubusercontent.com/494636/64419202-a00a0e80-d09c-11e9-8b25-9db4e94bd137.png">

Funny bug by the way

**Comment by phochste** [comment]
@nicolasfranck  The source of this code is here:

https://github.com/LibreCat/LibreCat/blob/dev/public/javascripts/librecat_dropzones.js#L153

I don't know enough about JavaScript to fix this issue elegantly. Can you take a look?

**Comment by vpeil** [comment]
@petrakohorst can you have look too, please?

**Comment by petrakohorst** [comment]
I fixed this in a PR.   
It's a simple check: if the star is already present, don't add another one.
