### ISSUE TITLE
Inconsistencies in schema/code

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#797]
* date_deleted is set in code, but not defined in schema:
https://github.com/LibreCat/LibreCat/search?q=date_deleted&unscoped_q=date_deleted

what is the use of this field? Eithter remove it or extend the schema?

**Comment by vpeil** [comment]
Do we want to store `date_deleted`? Any opinions on that?

**Comment by phochste** [comment]
@vpeil I'll extend the schema
