### ISSUE TITLE
Record storage in ElasticSearch and Mongo/MySQL 

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#8]
In the current branched all publications are stored in ElasticSearch first and optionally backupped in Mongo/MySQL later. This workflow has the wrong order. Records should be first stored in the secure/permanent store (Mongo/MySQL) and indexed in an ElasticSearch as a second step.

**Comment by vpeil** [comment]
We need to figure out which fields should be stored in the permanent store and which fields are used for indexing only...and which field should be "looked up" at indexing time.
