### ISSUE TITLE
Error when clicking on file link with closed access when not logged in

### ISSUE THREAD

**Issue by snorri** [LibreCat/LibreCat#80]
When you click on a link to file with closed access you get a rather cryptic error:
{
    "error": "view not found"
}

Example: http://demo.librecat.org/publication/2737386

In the error log it there is an entry, something like:
[hit #12]Supplied view (websites/403) not found -  does not exist

So it seems it is because there is no view defined for 403 errors.

Should the the closed access file links even be clickable (when not logged in as author/reviewer) if clicking just results in an error page? Instead I think it should rather be one of the following:
- file download option not shown at all
- filename shown but not clickable (probably makes most sense)
- like now but link goes to a page that prompts you to log in to the registration to view the file

**Comment by vpeil** [comment]
the "view not found" error was my mistake.... can fix this quickly...

but more interesting are the options 2 and 3

**Comment by petrakohorst** [comment]
I have made the following changes on dev (both in the download area at the top and on the file details tab):

Case open_access: show linked filename
Case closed_access: filename shown but not linked
Case local_access:
- if user's ip is within range, show linked filename
- if user's ip is not within range, show filename only

**Comment by vpeil** [comment]
thanks.
