### ISSUE TITLE
typo: use $p instead of p

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#800]
https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Route/publication.pm#L163
https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Route/publication.pm#L170

use `p->{finalSubmit}` instead of `$p->{finalSubmit}`. It "works", it is the wrong place.

btw.

https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Route/publication.pm#L163

shouldn't that be:

`$p->{finalSubmit} //= "recSave"`

I do not see a reason for a use case were `finalSubmit` is empty, and you get
an "access denied"

https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Route/publication.pm#L208

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/LibreCat/pull/801

**Comment by vpeil** [comment]
What confuses me here are the two different meanings of `$p` and `p`, which proves a bad style of coding (probably introduced by myself). We should clean this up and be more explicit, e.g. 

`$p` :arrow_right: `$params` (we have autocomplete in our editors....)

**Comment by vpeil** [comment]
Has been fixed in veresion 2.0.2
