### ISSUE TITLE
make thumbnail generation optional

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#803]
Thumbnail generation is now hardcoded into `LibreCat::App::Catalogue::Controller::File`.
Shouldn't this be optional? The thumbnail controller already takes care of records
without a thumbnail.

BTW. https://github.com/LibreCat/LibreCat/pull/515 covers a different topic

**Comment by phochste** [comment]
@nicolasfranck If you comment in `etc/files.yml` the `access_thumbnailer`, then nu thumbnails will be generated
