### ISSUE TITLE
stricter validation in schema.yml should have been documented

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#809]
Since commit https://github.com/LibreCat/LibreCat/commit/a0cb304e209d4620484c5950db004c50fd770e56

old records cannot be saved anymore, because they contain undocumented
fields like `request_a_copy` (not present in schema!), leading a strange like this:

![SharedCanvas_error](https://user-images.githubusercontent.com/494636/65589362-34bfa800-df89-11e9-82e6-8803bff4ee23.png)

Of course, the undocumented fields should have been documented too;-).

**Comment by vpeil** [comment]
these issues have been addressed in PR #802

**Comment by vpeil** [comment]
fixed as PR #802 has been merged
