### ISSUE TITLE
change in facet configuration should be documented

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#812]
cf. https://github.com/LibreCat/LibreCat/wiki/Add-Change-facet

In the past, all facet configuration for ElasticSearch was configured in `default_facets` (see link above). Those facets were added to the search of every model, regardless of the model.

Now facets need to configured in `facets.$model` instead of `default_facets`. The format hasn't changed.

**Comment by vpeil** [comment]
Thanks for the hint. I have updated to corresponding wiki page.
