### ISSUE TITLE
Template Error after login

### ISSUE THREAD

**Issue by nilswindisch** [LibreCat/LibreCat#82]
1. http://demo.librecat.org/
2. Click "Login"
3. fill in credentials
4. click "login"
5. Page reloads and throw the following error
`{
   "exception" : "Core::Template",
   "error" : "core - template - undef error - [Unavailable] ** [http://localhost:9200]-[503] NoShardAvailableActionException[[librecat][2] null], called from sub Search::Elasticsearch::Transport::try {...}  at /home/bup/LibreCat/local/lib/perl5/Try/Tiny.pm line 103. With vars: {'body' => {'status' => 503,'error' => 'NoShardAvailableActionException[[librecat][2] null]'},'status_code' => 503,'request' => {'path' => '/librecat/department/9996/_source','qs' => {},'ignore' => [],'method' => 'GET','body' => undef,'serialize' => 'std'}}\n at /home/bup/LibreCat/local/lib/perl5/Dancer/Template/Abstract.pm line 91.\n"
}`

**Comment by vpeil** [comment]
fixed. problems with the search index...
thanks for reporting!

**Comment by nilswindisch** [comment]
thank you for the quick fix!
