### ISSUE TITLE
Separate citation feature from LibreCat

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#830]
This would benefit our overall strategy to split this application into smaller chunks.

1. It is a optional feature. A lot of use cases do not need it. 
2. It can be done in a separate repository.
3. Citations should be stored in a separate database. Switching to new styles, improving the CSL mapping, etc. would then **not** result in updated records in the main store.

**Comment by vpeil** [comment]
See PR #877

**Comment by phochste** [comment]
PR #877 was closed with unmerged commits.
