### ISSUE TITLE
download file crashes starting from Catmandu::FileStore 1.15

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#848]
When you have the dependency `Catmandu::FileStore` 1.15 (or higher) installed,
and you use the `Catmandu::Store::File::Simple`
in your LibreCat environment, then all file downloads result in an incomplete response,
due to the error `incomplete write to $file` in `Catmandu::Store::File::Simple::Bag`, which makes the worker crash with exit code 255.

Downgrading to version 1.14 helps.

This error does not happen in the command `file_store`, so it must be related to the streaming environment of Plack/Dancer.

**Comment by phochste** [comment]
I can't yet repeat this bug on my system

**Comment by phochste** [comment]
Although I can't repeat the specific bug I am working on an update for Catmandu::FileStore. I hope you can test the 1.16 release on your local environment.

**Comment by nicolasfranck** [comment]
Update: I've pulled the newest master branch (https://github.com/LibreCat/LibreCat/commit/f670e5e738bbd4e67b0c66d035ff48cec87b0089),
and now version 1.151 seems to be working. 

Why it crashed on my computer, is probably this:

* It still used an outdated version of the method `Dancer::App::Helper::io_from_plack_writer`, i.e. the one before commit 57be79b8573815198f8877ba1c33b2614957c3c8
* that older version only worked for versions of filestore < 1.151, for some reason

**Comment by nicolasfranck** [comment]
version 1.16 of the filestore is ok also
