### ISSUE TITLE
LibreCat::Search isn't accessible in layer mode

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#85]
When using LibreCat::Search.pm in a layer it is not available for the main code.

The reason is it think because of adding a 'searcher' method in the LibreCat.pm before the layers mechanism has a change to dynamically load the correct LibreCat::Search.pm:

    sub searcher {
        state $searcher = do {
            LibreCat::Search->new(store => Catmandu->store('search'));
        };
    }

**Comment by nics** [comment]
you want to be able to override the LibreCat::Search package?

**Comment by phochste** [comment]
This was an issue for Lund. Don't know if this is still required

On 11 Nov 2016, at 08:44, Nicolas Steenlant <notifications@github.com<mailto:notifications@github.com>> wrote:


you want to be able to override the LibreCat::Search package?

-

**Comment by vpeil** [comment]
I think @snorri was happy with the default_facets moved to config, right?

**Comment by snorri** [comment]
Right. We don't need to do that anymore. The problem was the default_facets were hard coded in that module and we needed to change them. Since we can now just do it in the catmandu config file there is no problem.
