### ISSUE TITLE
customizing fields in librecat

### ISSUE THREAD

**Issue by Kuyela** [LibreCat/LibreCat#856]
i have installed librecat but i dont know how to add my own fields, please help.

**Comment by vpeil** [comment]
Hi @Kuyela! Pleae, have a look at these articles:

https://github.com/LibreCat/LibreCat/wiki/Add-Change-Fields

https://github.com/LibreCat/LibreCat/wiki/Add-Change-Fields---Front-End

You might find other topics of interest in our wiki: https://github.com/LibreCat/LibreCat/wiki

**Comment by Kuyela** [comment]
this is what i am getting

nexus@NEXUS:~/LibreCat$ cat layers.yml
cat: layers.yml: No such file or directory
nexus@NEXUS:~/LibreCat$

**Comment by vpeil** [comment]
As a first step, you should do 

```bash
nexus@NEXUS:~/LibreCat$ cp layers.yml-example layers.yml
```
