### ISSUE TITLE
Demo XML exports contain errors

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#857]
http://demo.librecat.org/record/2737384.dc

**Comment by nicolasfranck** [comment]
That url returns two records (with same identifier). See line 28 where the first record ends:

    </oai_dc:dc>

That leads me to the following question: why do this records return an array of results,
if it is meant to represent one record? Internally this is implemented as a forward to `/export`, but should be done differently?

**Comment by nicolasfranck** [comment]
Fixed by https://github.com/LibreCat/LibreCat/commit/438401fd236b2b2fd211bea01e71486edd9fb821 ?

**Comment by vpeil** [comment]
Yes, I can confirm that it is solved. The demo server runs on the latest dev branch (if you'd like to test something else).
