### ISSUE TITLE
Exports of multiple MODS or DataCite records fail due to  malformed XML

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#858]
There are no `template_before` / `template_after` defined for these exports in `config/route.yml`.
The mods standard has a `modsCollection` as envelope. But I don't know the envelope format for datacite. @vpeil ?

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/LibreCat/pull/859

@vpeil I've made a not about a possible bug in `Catmandu::Exporter::Template`

**Comment by vpeil** [comment]
Concerning datacite: https://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf does not include anything about an envelope or list format. Not sure what to do here.

**Comment by vpeil** [comment]
> #859
> 
> @vpeil I've made a note about a possible bug in `Catmandu::Exporter::Template`

Thanks, will have a look at it.

**Comment by vpeil** [comment]
fixed by #859
