### ISSUE TITLE
Field value for "publication type" doesn't revert when canceling change (demo + dev version)

### ISSUE THREAD

**Issue by snorri** [LibreCat/LibreCat#86]
If you select a different _publication type_ in any publication form you get the a dialog box:
**Changing the publication type may result in loss of data if the new type uses different fields from the previous one! Proceed with caution.**", with buttons "**OK**" and "**Cancel**". If you click "Cancel" the field value for _publication type_ doesn't revert to the value that was there before, as one would expect.

**Comment by vpeil** [comment]
oha! confirmed. that's a bug!

**Comment by vpeil** [comment]
fixed on dev. Don't forget to regenerate your forms.
