### ISSUE TITLE
Problems with mount of mojo part

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#864]
@nics @nicolasfranck 

It's good that we solved the cascading problem. But the PR #822 introduces a new problem (for the future).
Please, correct me if am wrong. As I understand it all mojo routes are collected by [LibreCat::Application](https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/Application.pm), this file get loaded by [bin/mojo_app.pl](https://github.com/LibreCat/LibreCat/blob/dev/bin/mojo_app.pl) and this mounted at [api](https://github.com/LibreCat/LibreCat/blob/dev/bin/app.pl#L107).

Now, if I am goint to add new mojo routes (e.g. for files) they will appear under `/api`.

**Comment by nicolasfranck** [comment]
mm, yes, you're right. Wasn't `/openapi.yml` not the original path ( instead of `/api/openapi.yml` which it is now due to the mount )?

**Comment by nicolasfranck** [comment]
update: openapi is already server on path `/api/v1/openapi.yml` in the master branch. See https://github.com/LibreCat/LibreCat/blob/37b91ad69e9cfcfa8f71ce80cde550aa91817384/lib/Mojolicious/Plugin/LibreCat/Api.pm#L19

**Comment by nicolasfranck** [comment]
Better not serve this separately?

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/LibreCat/pull/881

**Comment by vpeil** [comment]
solved by PR #881
