### ISSUE TITLE
let LibreCat::Model handle method "last_errors" from its validator

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#883]
`LibreCat::Model` already handles the method `is_valid` from its validator, but is missing the method `last_errors` to retrieve the errors. Of course one can use `$model->validator->last_errors`, but that's strange if you provide `$model->is_valid`.

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/LibreCat/pull/884

**Comment by vpeil** [comment]
Fixed by PR #884
