### ISSUE TITLE
use Dancer function "var" to store additional data for the template

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#887]
Now data is now often sent to a template in the wrong way: the hash IS the record. This makes it hard
to distinguish between record and additional information/flags. Maybe a record attribute has the same name as the flag?

Possible solution for future additions: use the Dancer method `var`:

```
var my_flag => 1;
```

These variables are exposed in the templates as follows:

```
[% vars.my_flag %]
```

Or does this make things all the more complicated?

**Comment by vpeil** [comment]
:+1:  I am using the same technique in another project with Dancer2.

**Comment by nicolasfranck** [comment]
@vpeil well, it is rather a hack here so we can move forward.

**Comment by vpeil** [comment]
Has been adpoted in the meantime: cf. https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/App/Catalogue/Route/publication.pm#L129
