### ISSUE TITLE
Use colon as layer directory seperator

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#89]
On *nix systems the colon (:) is used as path seperator, but LibreCat uses a comma (,) for the layers. Since good system design tend to reuses existing conventions, when it's possible and they are widely used, LibreCat should adhere such conventions. Please change https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Layers.pm#L104

Use a ':' instead of ',' and adjust the documentation.

**Comment by nics** [comment]
Using a colon is potentially problematic on some file systems like hfs where it is the directory separator. Many unix tools use comma separated values for repeated options (e.g. cut).

**Comment by vpeil** [comment]
@nics thanks for pointing this out.
