### ISSUE TITLE
Add documentation how to install/activate the citation style processor (CSL)

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#9]
The configuration is available in:

     catmandu.citation.yml

But where to find the software, what is required,...

**Comment by nichtich** [comment]
I'd also like to know how CSL could be used in plain Catmandu. Can I convert a CSL-JSON record to formatted citation string in a fix?

**Comment by njahn82** [comment]
Actually, the csl functionality needs re-work. We should interface it with a more current processor and with the csl style repository to get formatted citation strings.

@petrakohorst

**Comment by vpeil** [comment]
Indeed, it needs a refactoring, since we are using old php csl processor.
Alternative: https://github.com/zotero/citeproc-node

**Comment by vpeil** [comment]
I have forked the citeproc-node repo and added a Dockerfile: https://github.com/vpeil/citeproc-node

Running this one is easy:
```
$ docker run -d -p 8085:8085 -t ....
```
Now you can use the example from the Readme:
```
curl --header "Content-type: application/json" \
  --data @sampledata.json -X POST \
  'http://127.0.0.1:8085?responseformat=html&style=modern-language-association'
```

This is a sandboxed microservices which makes documentation and maintainance easy, and is independent of the LibreCat app.

**Comment by phochste** [comment]
What is exact docker command I need to run? Sorry I'm a docker newbie what is the "...." that should be filled in?

**Comment by vpeil** [comment]
Ok. (It's not on docker hub, so a few steps are required.

1. clone the repo:
`$ git clone https://github.com/vpeil/citeproc-node`

2. `$ cd citeproc-node`

3. Build the image and give it a name, e.g. myciteproc:
`$ docker build -t myciteproc .` (don't forget the dot at the end)

4. `$ docker run -d -p 8085:8085 -t myciteproc`

And then you should be able to run the curl command example above.

**Comment by vpeil** [comment]
**CORRECTION**:
Please run the above `git clone` command with `--recursive` option!

**Comment by phochste** [comment]
Added to the install documentation

**Comment by vpeil** [comment]
Are you sure this works? I thought the Librecat code needs adaptions (at least the mapping fixes/to_csl.fix ?)
