### ISSUE TITLE
Implement the Signposting protocol

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#90]
http://signposting.org/

See also the presentation by Herbert Van de Sompel: https://www.slideshare.net/mobile/hvdsomp/pid-signposting-pattern

**Comment by vpeil** [comment]
I have released https://metacpan.org/release/VPEIL/Plack-Middleware-Signposting-0.03 on CPAN.

This thing can talk to a Catmandu store. Basically, this issue is solved.

Do we want this module as a dependency or she we leave this feature for layers?

**Comment by phochste** [comment]
Great! IMO it would be best to start with providing it as an layer/example how this could be added to LibreCat as a feature. We need a way to slim the core a bit down to improve basic functionality before adding more weight.

**Comment by vpeil** [comment]
yes, that's also my concern: be careful with adding deps und functionaliy. I will document this in the wiki.

**Comment by vpeil** [comment]
Pushed version of the module to metacpan.

Added documentation how to enable this in Librecat: https://github.com/LibreCat/LibreCat/wiki/Signposting

**Comment by joschirr** [comment]
Any chance to support the "publication boundary" pattern? 
Could LibreCat be added to the adopters list?
https://signposting.org/adopters/
