### ISSUE TITLE
Is the `publication` model name appropriate in all parts of the application?

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#905]
We switched some time ago from the `publication` paths to the `record` paths (because in LibreCat we are dealing with more than just publications). Still, internally the `publication` model name stays in use for Perl modules but also the command line tools. Also in the REST API the `record` model is not use and the `publication` must be used. This feels a bit confusing.

What can be done?
Or, what is the rational to don't do anything about this?

**Comment by vpeil** [comment]
One can change this, but be aware of a huge PR then. I guess a lot of files have to be changed.

**Comment by vpeil** [comment]
Since we are now in a phase of bug fixes only I wouldn't do anything about it.
