### ISSUE TITLE
LibreCat::Search::search should not implicitly add facets/aggregations

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#906]
The method `search` in `LibreCat::Search` now implicitly requests aggregations from ElasticSearch, based on the configuration option `facets.${bag_name}`, even where this does not make sense.

See https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/Search.pm#L59

Examples where facets are not needed:

* https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/Dedup/Publication.pm#L21
* https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/Model/User.pm#L56
* https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/App/Helper.pm#L200
* https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/App/Helper.pm#L248
* https://github.com/LibreCat/LibreCat/blob/dev/lib/LibreCat/Cmd/publication.pm#L211
...

Of course, one can switch off the aggregations, but the implications are too wide.

Why not simply let the requester add this option?
Other options like `default_page_size` and `default_sort_backend` have..

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/907

**Comment by vpeil** [comment]
merged into dev.
