### ISSUE TITLE
Catmandu::Store::ElasticSearch should throw error when an error occurs

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#913]
Now LibreCat unknowingly relies on a default setting of `LibreCat::Store::ElasticSearch::Bag` that sets `on_error` to `log`. This way any error disappears into the logs, at least if `Log::Any` is configured, in which case no traces can be found.

cf. https://metacpan.org/pod/Catmandu::Store::ElasticSearch#ERROR-HANDLING

Should be set explicitly to `throw`, or at least should be explicitly to any value so all is clear.

**Comment by vpeil** [comment]
See also #374 .
