### ISSUE TITLE
validation fails on "file_json"

### ISSUE THREAD

**Issue by ThriceGood** [LibreCat/LibreCat#918]
I noticed that validation fails due to the existence of "file_json" after I change publication type from the publication form.  

It's being set here:

https://github.com/LibreCat/LibreCat/blob/f670e5e738bbd4e67b0c66d035ff48cec87b0089/lib/LibreCat/App/Catalogue/Route/publication.pm#L529

This is not in the schema.yml file so I presume this is not needed any more?

**Comment by vpeil** [comment]
It has been cleaned up on the dev branch. A release is to come within the next few days.
