### ISSUE TITLE
Anchor placement in filters.tt ??

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/LibreCat#923]
In views/filters.tt there is an anchor which probably has some role in filter functions. https://github.com/LibreCat/LibreCat/blob/6652a5ef0d037852e334cfdaee97b769d0559cfd/views/filters.tt#L7
In an of itself no problem, but this anchor has a css style:
```
div.anchor {
    padding-top: 52px;
    margin-top: -52px;
}
```
Which causes it to be placed above the filters and on top of the tabs bar. Links in this area in the tabs bar do not work correctly anymore because the div overlays them. See screenshot below.
![filters_anchor_div](https://user-images.githubusercontent.com/1527799/93747981-ce02b800-fbf7-11ea-99e1-c7d83d35e8f0.png)

I have overwritten it with 0 margin and 0 padding in our local layer, filter placement looks the same. And the links work again.

Does anyone know if there is a reason for this particular div-placement in the css?

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/blame/master/views/filters.tt. @feldi-online ?

**Comment by nicolasfranck** [comment]
Update: I see links to [#filters](https://github.com/LibreCat/LibreCat/blob/6652a5ef0d037852e334cfdaee97b769d0559cfd/views/hits.tt#L12) and [#export](https://github.com/LibreCat/LibreCat/search?q=href%3D%22%23export%22)

But those should not elements that take up space. Make a `span` of it?

**Comment by nicolasfranck** [comment]
@petrakohorst does this fix it: https://github.com/LibreCat/LibreCat/pull/952?

**Comment by petrakohorst** [comment]
Yes, that fixes it.
