### ISSUE TITLE
repeatable form fields generate empty element, even when not wanted

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#938]
Repeated form fields (especially the complex ones) like `abstract`
generate useless array entries in the record. 

The reason for this that always one
element for input (e.g. combination of "language" and "text") is shown.

This way unwanted empty values slip in, and one cannot distinguish
anymore between wanted and unwanted empty values..

Why no separate the "add" button from the input element,
and leave the "remove" element with the element?

Now you have

<input> - +

**Comment by petrakohorst** [comment]
For this purpose we have the fix ```clean_preselects()```, which removes the abstract field if it detects that there is no content in the text field, but only the preselected language field - which means that there is no abstract.   
The same goes for related_material.link. It's a combined field of a relation and a url and the relation is always preselected. The fix removes it if there is not also content in the url field when the record is submitted.

For all other repeatable fields we have the ```vacuum()``` fix, which removes empty arrays, empty hashes and empty strings before saving/returning the record.

How exactly would you separate the add button from the input field? And what would change in the form data when doing this?
