### ISSUE TITLE
Quick and Easy not working anymore as normal user

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#94]
Only as super user a quick and easy result in a new record. As normal user only the files get uploaded but no record created.

**Comment by vpeil** [comment]
*Cannot* reproduce! Can you check again, please?

**Comment by phochste** [comment]
Confirmed. If a superuser uploads a QAE, then no problem. When a user uploads a QAE then it is oly added to the backup bag but not in the search engine

**Comment by phochste** [comment]
This is only in installation, like UGent, that use UUID-s for user identifiers. The ElasticSearch index automatically assumes in the first test that a user_id is an integer, when in a later test a new record with a UUID user_id is added, the  ElasticSearch will fail to map the data.
