### ISSUE TITLE
Why use try-catch in LibreCat::Index?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#946]
The package `LibreCat::Index` uses `try` and `catch` both in `remove_alias` and in `_do_index`.
The return from the call to `remove_alias` is ignored, the return from the call to `_do_index` not,
but the content is still printed to the console. 

So why not simply let the client code decide whether to use
try and catch? The only time this can fails is if there is something
misconfigured, index has become read-only, or if there something
else seriously wrong. In my opinion, the code should just carp/die
and let the client code handle the rest.

It would also make `coveralls` happy, as it reports [uncovered lines](https://coveralls.io/builds/38681211/source?filename=lib%2FLibreCat%2FIndex.pm#L171), which are hard to test against;

**Comment by vpeil** [comment]
Agreed. I can prepare a PR.

**Comment by vpeil** [comment]
fixed by #973
