### ISSUE TITLE
Choose a LICENSE

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#96]
Which one would you like? See here for some choices:  http://choosealicense.com/
I like it simple and permissive....

But before attaching a LICENSE file to this repo we need to check how to deal with software we use (like js libraries, bootstrap, etc.)... any suggestions?

**Comment by pietsch** [comment]
For CPAN modules there are these: guidelines: http://www.perlfoundation.org/cpan_licensing_guidelines

For consistency, it is recommended to release Perl software under the same licensing terms as Perl itself, i.e. "Artistic license or GPL": https://www.gnu.org/licenses/license-list.html#PerlLicense

**Comment by dsheroh** [comment]
Agreed.  Perl license is most likely the way to go unless there's a 
specific reason to choose something else.

**Comment by vpeil** [comment]
see 31bb0afba5a5fc80d2803ac7fb7f57b0edbf6b7b
