### ISSUE TITLE
filters.tt makes wrong assumptions about id of department in url

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#966]
When you land on the reviewer page on one of your departments (e.g. `/librecat/search/reviewer/my_dep`),
the export links are all wrong: `/librecat/export?cql=department%3D&fmt=yaml`.

Reason are these lines:

https://github.com/LibreCat/LibreCat/blob/master/views/filters.tt#L128
https://github.com/LibreCat/LibreCat/blob/master/views/filters.tt#L129

They assume that the id of a department is an integer, and only then extract it.

Should be done like this

```
[% dept = request.path_info().split("/").last %]
```

**Comment by nicolasfranck** [comment]
It also seems that a statement like `tmp = {}; tmp.import(qp)` does not copy the hash recursively.

Test:

* add a `cql` filter to the url
* when you apply `tmp.cql.push("department=$dept")`, the old `qp.cql` is also affected. If `qp.cql` was a string, then not. Looks like both `tmp.cql` and `qp.cql` refer to the same underlying array.

**Comment by nicolasfranck** [comment]
TODO:

* add `LibreCat::App::Helpers::Helpers#dup` that clones data
* replace `tmp.import(qp)` in templates

@nicolasfranck

**Comment by vpeil** [comment]
fixed by PR #974
