### ISSUE TITLE
skip_commit not enough to skip transactions?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#968]
When adding/deleting records from a `LibreCat::Model`,
it seems like option `skip_commit` is used to skip commits.
This way we can insert/delete multiple records at once,
and then issue the commit ourselves.

But https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Model.pm#L124 shows
that method `add` expects option `skip_transaction` for this to happen.
Meaning: a method like [add_many](https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Model.pm#L106)
tries to add multiple records all in one transaction, and uses `add` (instead of `_add`).
Result: a commit happens for every insert..

**Comment by vpeil** [comment]
Mainly intended for batch imports, but it used nor documented in `lib/LibreCat/Cmd/*.pm`.

And I found 3 different notions, probably meaning the same?
1. skip_commit https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Model.pm#L112
2. skip_transaction https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Model.pm#L124
3. skip_index https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Model.pm#L147

Rename everything to skip_commit, @nicolasfranck ?
