### ISSUE TITLE
LibreCat::Model::*#add returns indexed version of record, not the one from the main bag

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#969]
If you add a record to a model like this

```
my $model = LibreCat->instance->model("publication");
$rec = $model->add($rec);
```

then you get the record back as stored in ElasticSearch,
not as it is stored in the backend DBI store.

The reason is this line: https://github.com/LibreCat/LibreCat/blob/master/lib/LibreCat/Model.pm#L147

That line applies the fix `index_publication` that changes the `$rec`
before adding it to the ElasticSearch store. 

Reproduce:

* add `remove("year")` to `fixes/index_publication.fix` (or in your local layer)
* add a record with a valid year to model publication
* you'll get back a record without a year if you retrieve it as `$rec = $model->add($rec)`
* you'll get back the correct version if you retrieve as `$rec = $model->add($rec); $rec = $model->get($rec->{_id})`

**Comment by nicolasfranck** [comment]
Possible solution:

```
- $self->index($rec, %opts) unless $opts{skip_index};
+ $self->index(Clone::clone($rec), %opts) unless $opts{skip_index};
```

**Comment by vpeil** [comment]
I came across this issue some days ago. I noticed that some fields I've added during indexation were found in the main store. Could make any sense of it.

Thanks for finding this problem (and the solution!).
