### ISSUE TITLE
Implement the Memento protocol

### ISSUE THREAD

**Issue by vpeil** [LibreCat/LibreCat#98]
See also #90. This would make our app more **webbish** (stolen from a SWIB16 slide) :laughing:

**Comment by vpeil** [comment]
There's [Plack::Middleware::Memento](https://metacpan.org/pod/Plack::Middleware::Memento) and [Plack::Middleware::Memento::Handler::Catmandu::Bag](https://metacpan.org/pod/Plack::Middleware::Memento::Handler::Catmandu::Bag) by @nics 

If they are ready to use we only need to provide a basic configuration example.

**Comment by phochste** [comment]
Moved to https://github.com/LibreCat/LibreCat/wiki/Roadmap
