### ISSUE TITLE
Bug in search on person page

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/LibreCat#981]
An interesting phenomenon has occurred on the person page in the LibreCat core. This bug can be recreated on the LibreCat Demo-Server.

When searching on a person page (```/person/ID```) with **more than one search term AND reaching more than one hit**, an error happens. The error message says "core - template - undef error - cql error: unknown first class relation".   
Unfortunately there is no more info to be found in logs or anywhere as to which template threw this error.

Example: James Dean's Person page on the Demo-Server: http://demo.librecat.org/person/3

- Search for "retrospective relative" and you will find one hit.
- Search for "assessing" and you will find two hits.

But:

- Search for "james dean" and you should find three hits - but you get an error
- Search for "assessing genetic" and you should find two hits - but you get an error
- Search for "retrospective space" and you should find two hits - but you get an error

It has nothing to do with the returned hits, it has nothing to do with the actual search terms.

I have tried to check templates for the error source (tried to remove several included templates or parts of templates), but to no avail.   
I removed the filters.tt and the mark_all_js.tt from being included in the other templates - but the errors are still there.

Any idea what might cause this?

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/pull/983

So it is the function `all_marked` from the librecat helper that is causing
this behaviour. That function adds the user query (`q`) to `cql` which
can never work. `q` is already added btw by `extract_params`

I removed that one line; `q` and `cql` are kept separate, and `LibreCat::Search`
treats them as user query and filter respectively.

**Comment by petrakohorst** [comment]
Yes, it works!

Multiple search terms on person page leading to multiple search entries - works.   
Mark all - still works as expected.

**Comment by petrakohorst** [comment]
Closing this issue, because its fix in #983 was merged.
