### ISSUE TITLE
Support reverse ORCID -> ArXiv imports

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat#99]
Ref Simeon Warner's email

My ORCID iD is

http://orcid.org/0000-0002-7970-7855

and you can get a list of my articles on arXiv from:

https://arxiv.org/a/0000-0002-7970-7855

which supports Atom or HTML, see bottom of HTML page for links/notes.

A bogus/missing ORCID id will give you an HTTP 404 (after a 303 I'm afraid :-( ), e.g.

https://arxiv.org/a/0000-0002-7970-785X

With this facility it is easy to check one ORCID to see if we know a mapping to an arXiv author.

There is a public dump of all ORCID to arXiv article mappings available from:

http://export.arxiv.org/data/authors/orcid_ids_to_articles.json

It is a slightly odd JSON format [1] and about 60MB, updated weekly I think. From this you can easily pull out the 18441 distinct author ids

simeon@RottenApple ~> grep 'http://orcid.org/' ~/Downloads/orcid_ids_to_articles.json | sort | uniq | wc -l
  18441

Interestingly we now have 21872 ORCID <-> user account associations and 17316 arXiv author id <-> user account associations. However, only 5522 accounts have both. These 5522 associations are also available in a weekly dump at http://export.arxiv.org/data/authors/arxiv_to_orcid_ids.json (same odd format) but that probably isn't very useful now that it is possible to have an ORCID without an arXiv author id.

**Comment by vpeil** [comment]
fetching article via ORCID ID is now supported by the latest https://github.com/LibreCat/Catmandu-ArXiv

**Comment by vpeil** [comment]
fixed. Run `carton install` to get the latest Catmandu::ArXiv needed for this feature
